
create or replace type tCode as object (
  type varchar2(1),
  code  varchar2(8),
  descr varchar2(50) 
);
/  
declare
    v_appl_id		integer;
    v_header_seq	integer;
    v_detail_seq	integer;
    v_date		    varchar2(10);
    v_user          varchar2(20);
    v_idx           integer;

    TYPE tCodeList IS TABLE OF tCode;
    
    codes tCodeList := tCodeList(

        -- ****     ADDRESS TYPE   ****
        tCode('L', 'ADDRTYPE', 'ADDRESS TYPE'),
        tCode('V', 'O', 'OFFICE'),
        tCode('V', 'H', 'HOME'),
        tCode('V', 'V', 'VACATION'),
        tCode('V', 'H2', 'HOME 2'),
        tCode('V', 'M', 'MAILING'),
        tCode('V', 'W', 'WORK'),
        tCode('V', 'W2', 'WORK 2'),
        tCode('V', 'T', 'TEMPORARY'),
        
        -- ****     CITIZENSHIP   ****        
        tCode('L', 'CITIZEN', 'CITIZENSHIP'),
        tCode('V', 'USA', 'UNITED STATES'),
        tCode('V', 'CAN', 'CANADA'),
        tCode('V', 'MEX', 'MEXICO'),
        
        -- ****     COUNTRY CODE   ****        
        tCode('L', 'COUNTRY', 'COUNTRY CODE'),
        tCode('V', 'AFGH', 'AFGHANISTAN'),
        tCode('V', 'ALBA', 'ALBANIA'),
        tCode('V', 'ALGE', 'ALGERIA'),
        tCode('V', 'AMSA', 'AMERICAN SAMOA'),
        tCode('V', 'ANDO', 'ANDORRA'),
        tCode('V', 'ANGO', 'ANGOLA'),
        tCode('V', 'ANGU', 'ANGUILLA'),
        tCode('V', 'ANTA', 'ANTARCTICA'),
        tCode('V', 'ANTI', 'ANTIGUA AND BARBUDA'),
        tCode('V', 'ARGN', 'ARGENTINA'),
        tCode('V', 'ARMN', 'ARMENIA'),
        tCode('V', 'ARUB', 'ARUBA'),
        tCode('V', 'AUST', 'AUSTRALIA'),
        tCode('V', 'AUSA', 'AUSTRIA'),
        tCode('V', 'AZER', 'AZERBAIJAN'),
        tCode('V', 'AZOR', 'AZORES'),
        tCode('V', 'BAHA', 'BAHAMAS'),
        tCode('V', 'BAHR', 'BAHRAIN'),
        tCode('V', 'BANG', 'BANGLADESH'),
        tCode('V', 'BARB', 'BARBADOS'),
        tCode('V', 'BELA', 'BELARUS'),
        tCode('V', 'BELG', 'BELGIUM'),
        tCode('V', 'BELI', 'BELIZE'),
        tCode('V', 'BENE', 'BENIN'),
        tCode('V', 'BERM', 'BERMUDA'),
        tCode('V', 'BEQU', 'BEQUIA'),
        tCode('V', 'BHUT', 'BHUTAN'),
        tCode('V', 'BOLI', 'BOLIVIA'),
        tCode('V', 'BOSN', 'BOSNIA'),
        tCode('V', 'BOTS', 'BOTSWANA'),
        tCode('V', 'BRAZ', 'BRAZIL'),
        tCode('V', 'BRIO', 'BRITISH INDIAN OCEAN'),
        tCode('V', 'BRWI', 'BRITISH WEST INDIES'),
        tCode('V', 'BRUN', 'BRUNEI DARUSSALAM'),
        tCode('V', 'BULG', 'BULGARIA'),
        tCode('V', 'BURK', 'BURKINA FASO'),
        tCode('V', 'BURM', 'BURMA'),
        tCode('V', 'BURN', 'BURUNDI'),
        tCode('V', 'CAMB', 'CAMBODIA'),
        tCode('V', 'CAME', 'CAMEROON'),
        tCode('V', 'CANA', 'CANADA'),
        tCode('V', 'CAPE', 'CAPE VERDE'),
        tCode('V', 'CAYM', 'CAYMAN ISLANDS'),
        tCode('V', 'CENT', 'CENTRAL AFRICAN REPUBLIC'),
        tCode('V', 'CEYL', 'CEYLON'),
        tCode('V', 'CHAD', 'CHAD'),
        tCode('V', 'CHIL', 'CHILE'),
        tCode('V', 'CHIN', 'CHINA'),
        tCode('V', 'CRIS', 'CHRISTMAS ISLAND'),
        tCode('V', 'CCIS', 'COCOS (KEELING) ISLAND'),
        tCode('V', 'COLU', 'COLOMBIA'),
        tCode('V', 'COMO', 'COMOROS'),
        tCode('V', 'CONG', 'CONGO'),
        tCode('V', 'COOK', 'COOK ISLANDS'),
        tCode('V', 'COST', 'COSTA RICA'),
        tCode('V', 'COEL', 'COTE ELVOIRE'),
        tCode('V', 'CROA', 'CROATIA'),
        tCode('V', 'CUBA', 'CUBA'),
        tCode('V', 'CYPR', 'CYPRUS'),
        tCode('V', 'CZER', 'CZECH REPUBLIC'),
        tCode('V', 'CZEC', 'CZECHOSLOVAKIA'),
        tCode('V', 'DENM', 'DENMARK'),
        tCode('V', 'DJIB', 'DJIBOUTI'),
        tCode('V', 'DOMI', 'DOMINICA'),
        tCode('V', 'DOMR', 'DOMINICAN REPUBLIC'),
        tCode('V', 'ESTM', 'EAST TIMOR'),
        tCode('V', 'ECUA', 'ECUADOR'),
        tCode('V', 'EGYP', 'EGYPT'),
        tCode('V', 'ELSA', 'EL SALVADOR'),
        tCode('V', 'ENGL', 'ENGLAND'),
        tCode('V', 'EQUA', 'EQUATORIAL GUINEA'),
        tCode('V', 'ENTR', 'ERITREA'),
        tCode('V', 'ESTO', 'ESTONIA'),
        tCode('V', 'ETHI', 'ETHIOPIA'),
        tCode('V', 'FKIS', 'FALKLAND ISLANDS'),
        tCode('V', 'FRIS', 'FAROE ISLANDS'),
        tCode('V', 'FIJI', 'FIJI'),
        tCode('V', 'FINL', 'FINLAND'),
        tCode('V', 'FRAN', 'FRANCE'),
        tCode('V', 'FANT', 'FRENCH ANTILLES'),
        tCode('V', 'FRGU', 'FRENCH GUIANA'),
        tCode('V', 'FRPO', 'FRENCH POLYNESIA'),
        tCode('V', 'GABO', 'GABON'),
        tCode('V', 'GAMB', 'GAMBIA'),
        tCode('V', 'GEOR', 'GEORGIA'),
        tCode('V', 'GERM', 'GERMANY'),
        tCode('V', 'GHAN', 'GHANA'),
        tCode('V', 'GIBR', 'GIBRALTOR'),
        tCode('V', 'GRAN', 'GRANADA'),
        tCode('V', 'GRBR', 'GREAT BRITAIN'),
        tCode('V', 'GREE', 'GREECE'),
        tCode('V', 'GRNL', 'GREENLAND'),
        tCode('V', 'GREN', 'GRENADA'),
        tCode('V', 'GUAD', 'GUADELOUPE'),
        tCode('V', 'GUAM', 'GUAM'),
        tCode('V', 'GUAT', 'GUATEMALA'),
        tCode('V', 'GUIN', 'GUINEA'),
        tCode('V', 'GUBI', 'GUINEA-BISSAU'),
        tCode('V', 'GUYA', 'GUYANA'),
        tCode('V', 'HAIT', 'HAITI'),
        tCode('V', 'HRMD', 'HEARD AND MCDONALD'),
        tCode('V', 'HOLL', 'HOLLAND'),
        tCode('V', 'HOND', 'HONDURAS'),
        tCode('V', 'HONG', 'HONG KONG'),
        tCode('V', 'HUNG', 'HUNGARY'),
        tCode('V', 'ICEL', 'ICELAND'),
        tCode('V', 'INDI', 'INDIA'),
        tCode('V', 'INDO', 'INDONESIA'),
        tCode('V', 'IRAN', 'IRAN'),
        tCode('V', 'IRAQ', 'IRAQ'),
        tCode('V', 'IREL', 'IRELAND'),
        tCode('V', 'ISRA', 'ISRAEL'),
        tCode('V', 'ITAL', 'ITALY'),
        tCode('V', 'IVOR', 'IVORY COAST'),
        tCode('V', 'JAMA', 'JAMAICA'),
        tCode('V', 'JAPA', 'JAPAN'),
        tCode('V', 'JORD', 'JORDAN'),
        tCode('V', 'KAZK', 'KAZAKHSTAN'),
        tCode('V', 'KENY', 'KENYA'),
        tCode('V', 'KIRI', 'KIRIBATI'),
        tCode('V', 'KORE', 'KOREA'),
        tCode('V', 'KORR', 'KOREA, REPUBLIC OF'),
        tCode('V', 'KUWA', 'KUWAIT'),
        tCode('V', 'KYRG', 'KYRGYZSTAN'),
        tCode('V', 'LAOP', 'LAO PEOPLES DEMOCR'),
        tCode('V', 'LAOS', 'LAOS'),
        tCode('V', 'LATV', 'LATVIA'),
        tCode('V', 'LEBA', 'LEBANON'),
        tCode('V', 'LESO', 'LESOTHO'),
        tCode('V', 'LIBE', 'LIBERIA'),
        tCode('V', 'LIBY', 'LIBYA'),
        tCode('V', 'LICH', 'LIECHTENSTEIN'),
        tCode('V', 'LITH', 'LITHUANIA'),
        tCode('V', 'LUXE', 'LUXEMBOURG'),
        tCode('V', 'MACU', 'MACAU'),
        tCode('V', 'MACE', 'MACEDONIA'),
        tCode('V', 'MADA', 'MADAGASCAR'),
        tCode('V', 'MALW', 'MALAWI'),
        tCode('V', 'MALA', 'MALAYSIA'),
        tCode('V', 'MALD', 'MALDIVES'),
        tCode('V', 'MALI', 'MALI'),
        tCode('V', 'MALT', 'MALTA'),
        tCode('V', 'MALV', 'MALAVIVA'),
        tCode('V', 'MARS', 'MARSHALL ISLANDS'),
        tCode('V', 'MART', 'MARTINIQUE'),
        tCode('V', 'MAUN', 'MAURITANIA'),
        tCode('V', 'MAUT', 'MAURITIUS'),
        tCode('V', 'MAYT', 'MAYOTTE'),
        tCode('V', 'MEXI', 'MEXICO'),
        tCode('V', 'MICR', 'MICRONISIA, FEDERATION'),
        tCode('V', 'MOLD', 'MOLDOVA, REPUBLIC OF'),
        tCode('V', 'MONA', 'MONACO'),
        tCode('V', 'MONG', 'MONGOLIA'),
        tCode('V', 'MONT', 'MONTSERRAT'),
        tCode('V', 'MORO', 'MOROCCO'),
        tCode('V', 'MOZA', 'MOZAMBIQUE'),
        tCode('V', 'MUST', 'MUSTIQUE'),
        tCode('V', 'MYAN', 'MYANMAR'),
        tCode('V', 'NAMI', 'NAMIBIA'),
        tCode('V', 'NAUR', 'NAURU'),
        tCode('V', 'NEPA', 'NEPAL'),
        tCode('V', 'NETH', 'NETHERLANDS'),
        tCode('V', 'NEAN', 'NETHERLANDS ANTILLES'),
        tCode('V', 'NCAL', 'NEW CALEDONIA'),
        tCode('V', 'NEWG', 'NEW GUINEA'),
        tCode('V', 'NEWZ', 'NEW ZEALAND'),
        tCode('V', 'NICA', 'NICARAGUA'),
        tCode('V', 'NIGR', 'NIGER'),
        tCode('V', 'NIGE', 'NIGERIA'),
        tCode('V', 'NIUE', 'NIUE'),
        tCode('V', 'NORF', 'NORFOLK ISLAND'),
        tCode('V', 'NKOR', 'NORTH KOREA'),
        tCode('V', 'NMAR', 'NORTHERN MARIANA ISLANDS'),
        tCode('V', 'NORW', 'NORWAY'),
        tCode('V', 'OMAN', 'OMAN'),
        tCode('V', 'PAKI', 'PAKISTAN'),
        tCode('V', 'PALU', 'PALAU'),
        tCode('V', 'PANA', 'PANAMA'),
        tCode('V', 'PAPU', 'PAPUA NEW GUINEA'),
        tCode('V', 'PARA', 'PARAGUAY'),
        tCode('V', 'PERU', 'PERU'),
        tCode('V', 'PHIL', 'PHILIPPINES'),
        tCode('V', 'PITN', 'PITCAIRN'),
        tCode('V', 'POLA', 'POLAND'),
        tCode('V', 'PORT', 'PORTUGAL'),
        tCode('V', 'PURC', 'PUERTO RICO'),
        tCode('V', 'QATA', 'QATAR'),
        tCode('V', 'REUN', 'REUNION'),
        tCode('V', 'ROMA', 'ROMANIA'),
        tCode('V', 'RUMN', 'RUMANIA'),
        tCode('V', 'RUSS', 'RUSSIA'),
        tCode('V', 'RWAN', 'RWANDA'),
        tCode('V', 'SVCT', 'SAINT VINCENT AND T'),
        tCode('V', 'SAMO', 'SAMOA'),
        tCode('V', 'SANM', 'SAN MARINO'),
        tCode('V', 'SAOT', 'SAO TOME AND PRINCIPE'),
        tCode('V', 'SDOM', 'SANTO DOMINGO'),
        tCode('V', 'SAUD', 'SAUDI ARABIA'),
        tCode('V', 'SCOT', 'SCOTLAND'),
        tCode('V', 'SENE', 'SENEGAL'),
        tCode('V', 'SEYC', 'SEYCHELLES'),
        tCode('V', 'SIER', 'SIERRA LEONE'),
        tCode('V', 'SING', 'SINGAPORE'),
        tCode('V', 'SLOK', 'SLOVAKIA'),
        tCode('V', 'SLOV', 'SLOVENIA'),
        tCode('V', 'SOLO', 'SOLOMON ISLANDS'),
        tCode('V', 'SOMA', 'SOMALIA'),
        tCode('V', 'SAFR', 'SOUTH AFRICA'),
        tCode('V', 'SGEG', 'SOUTH GEORGIA AND T'),
        tCode('V', 'SKOR', 'SOUTH KOREA'),
        tCode('V', 'SOVT', 'SOVIET UNION'),
        tCode('V', 'SPAI', 'SPAIN'),
        tCode('V', 'STKI', 'ST. KITTS AND NEVIS'),
        tCode('V', 'STLU', 'SAINT LUCIA'),
        tCode('V', 'SRIL', 'SRI LANKA'),
        tCode('V', 'SHEL', 'ST HELENA'),
        tCode('V', 'SPIR', 'ST PIERRE AND MIQU'),
        tCode('V', 'STVI', 'ST VINCENT AND GRENADINES'),
        tCode('V', 'SUDA', 'SUDAN'),
        tCode('V', 'SURI', 'SURINAME'),
        tCode('V', 'SVAL', 'SVALBARD AND JAN MA'),
        tCode('V', 'SWAZ', 'SWAZILAND'),
        tCode('V', 'SWED', 'SWEDEN'),
        tCode('V', 'SWIT', 'SWITZERLAND'),
        tCode('V', 'SYRI', 'SYRIA'),
        tCode('V', 'SYRA', 'SYRIAN ARAB REPUBLIC'),
        tCode('V', 'TAIW', 'TAIWAN'),
        tCode('V', 'TAJI', 'TAJIKISTAN'),
        tCode('V', 'TANZ', 'TANZANIA'),
        tCode('V', 'THAI', 'THAILAND'),
        tCode('V', 'TIBE', 'TIBET'),
        tCode('V', 'TOBA', 'TOBAGO'),
        tCode('V', 'TOGO', 'TOGO'),
        tCode('V', 'TOKL', 'TOKELAU'),
        tCode('V', 'TONG', 'TONGA'),
        tCode('V', 'TRIN', 'TRINIDAD'),
        tCode('V', 'TRTB', 'TRINIDAD AND TOBAGO'),
        tCode('V', 'TUNI', 'TUNISIA'),
        tCode('V', 'TURK', 'TURKEY'),
        tCode('V', 'TURM', 'TURKMENISTAN'),
        tCode('V', 'TURC', 'TURKS AND CAICOS IS'),
        tCode('V', 'TUVA', 'TUVALU'),
        tCode('V', 'UGAN', 'UGANDA'),
        tCode('V', 'UKRA', 'UKRAINE'),
        tCode('V', 'UAEM', 'UNITED ARAB EMIRATES'),
        tCode('V', 'UNIS', 'UNION ISLANDS'),
        tCode('V', 'UNIT', 'UNITED KINGDOM'),
        tCode('V', 'UNST', 'UNITED STATES'),
        tCode('V', 'URUG', 'URUGUAY'),
        tCode('V', 'USBE', 'UZBEKISTAN'),
        tCode('V', 'VANU', 'VANUATU'),
        tCode('V', 'VATI', 'VATICAN CITY'),
        tCode('V', 'VENE', 'VENEZUELA'),
        tCode('V', 'VTNM', 'VIET NAM'),
        tCode('V', 'VIET', 'VIETNAM'),
        tCode('V', 'VIRG', 'VIRGIN ISLANDS'),
        tCode('V', 'BRVI', 'BRITISH VIRGIN ISLAND'),
        tCode('V', 'VIRU', 'US VIRGIN ISLANDS'),
        tCode('V', 'WALE', 'WALES'),
        tCode('V', 'WALF', 'WALLIS AND FUTUN'),
        tCode('V', 'WSTS', 'WESTERN SAHARA'),
        tCode('V', 'WSAM', 'WESTERN SAMOA'),
        tCode('V', 'YEME', 'YEMEN'),
        tCode('V', 'YEMR', 'YEMEN ARAB REBUPLIC'),
        tCode('V', 'YUGO', 'YUGOSLAVIA'),
        tCode('V', 'ZAIR', 'ZAIRE'),
        tCode('V', 'ZAMB', 'ZAMBIA'),
        tCode('V', 'ZIMB', 'ZIMBABWE'),
        tCode('V', 'UNKN', 'UNKNOWN'),
        
        -- ****     DEPARTMENT   ****        
        tCode('L', 'DEPT', 'DEPARTMENT'),
        tCode('V', 'ER', 'EMERGENCY ROOM'),
        tCode('V', 'LAB', 'LABORATORY'),
        tCode('V', 'PHAR', 'PHARMACY'),
        
        -- ****     DISTRICT OF RESIDENCE   ****        
        tCode('L', 'DISTRICT', 'DISTRICT OF RESIDENCE'),
        tCode('V', 'ESSX', 'ESSEX'),
        tCode('V', 'SHEF', 'SHEFFIELD'),
        tCode('V', 'HTZ', 'HANTZ'),
        
        -- ****     DRIVER LICENSE ISSUER   ****        
        tCode('L', 'DLISSUER', 'DRIVER LICENSE ISSUER'),
        tCode('V', 'CA', 'CALIFORNIA'),
        tCode('V', 'NV', 'NEVADA'),
        tCode('V', 'MEX', 'MEXICO'),
        
        -- ****     ETHNIC   ****        
        tCode('L', 'ETHNIC', 'ETHNIC'),
        tCode('V', '1', 'PUERTO RICAN'),
        tCode('V', '10', 'FILIPINO'),
        tCode('V', '11', 'KOREAN'),
        tCode('V', '12', 'VIETNAMESE'),
        tCode('V', '13', 'CAMBODIAN'),
        tCode('V', '14', 'LAOTIAN'),
        tCode('V', '15', 'THAI'),
        tCode('V', '16', 'HAWAIIAN'),
        tCode('V', '17', 'OTHER ASIAN/PACIFIC'),
        tCode('V', '18', 'ASIAN INDIAN'),
        tCode('V', '19', 'PAKISTANI'),
        tCode('V', '2', 'CUBAN'),
        tCode('V', '20', 'CAPE VERDEAN'),
        tCode('V', '21', 'OTHER PORTUGUESE'),
        tCode('V', '22', 'HAITIAN'),
        tCode('V', '23', 'JAMAICAN'),
        tCode('V', '24', 'BARBADIAN'),
        tCode('V', '25', 'OTHER W INDIAN'),
        tCode('V', '26', 'ARMENIAN'),
        tCode('V', '27', 'AUSTRIAN'),
        tCode('V', '28', 'ENGLISH'),
        tCode('V', '29', 'EGYPTIAN'),
        tCode('V', '3', 'DOMINICAN'),
        tCode('V', '30', 'FRENCH'),
        tCode('V', '31', 'FRENCH CANADIAN'),
        tCode('V', '32', 'GERMAN'),
        tCode('V', '33', 'GREEK'),
        tCode('V', '34', 'IRANIAN'),
        tCode('V', '35', 'IRISH'),
        tCode('V', '36', 'LEBANESE'),
        tCode('V', '37', 'LITHUANIAN'),
        tCode('V', '38', 'POLISH'),
        tCode('V', '39', 'RUSSIAN'),
        tCode('V', '4', 'MEXICAN'),
        tCode('V', '40', 'SCOTTISH'),
        tCode('V', '41', 'AMERICAN'),
        tCode('V', '42', 'OTHER'),
        tCode('V', '43', 'EUROPEAN'),
        tCode('V', '44', 'COLOMBIAN'),
        tCode('V', '45', 'SALVADORAN'),
        tCode('V', '46', 'AFRICAN AMERICAN'),
        tCode('V', '47', 'NIGERIAN'),
        tCode('V', '48', 'OTHER AFRICAN'),
        tCode('V', '5', 'CENTRAL AMERICAN'),
        tCode('V', '50', 'ISRAELI'),
        tCode('V', '51', 'OTHER MIDDLE EASTER'),
        tCode('V', '52', 'NATIVE AMER INDIAN'),
        tCode('V', '6', 'OTHER HISPANIC LATIN'),
        tCode('V', '8', 'JAPANESE'),
        tCode('V', '9', 'CHINESE'),
        
        -- ****     GENDER   ****        
        tCode('L', 'GENDER', 'GENDER'),
        tCode('V', 'M', 'MALE'),
        tCode('V', 'F', 'FEMALE'),
        tCode('V', 'O', 'OTHER'),
        tCode('V', 'U', 'UNKNOWN'),
        
        -- ****     LANGUAGE   ****        
        tCode('L', 'LANGUAGE', 'LANGUAGE'),
        tCode('V', 'ARAB', 'ARABIC'),
        tCode('V', 'ARME', 'ARMENAIN'),
        tCode('V', 'CAMB', 'CAMBODIAN'),
        tCode('V', 'CHIN', 'CHINESE'),
        tCode('V', 'CZEK', 'CZECH'),
        tCode('V', 'CAPE', 'CAPE VERDEAN'),
        tCode('V', 'CAPP', 'CAPE VERDEAN PORTUG'),
        tCode('V', 'CREO', 'CREOLE FRENCH'),
        tCode('V', 'DANE', 'DANISH'),
        tCode('V', 'ENGL', 'ENGLISH'),
        tCode('V', 'FRN', 'FRENCH'),
        tCode('V', 'GERM', 'GERMAN'),
        tCode('V', 'GREK', 'GREEK'),
        tCode('V', 'HATI', 'HATIAN'),
        tCode('V', 'HEBR', 'HEBREW'),
        tCode('V', 'HNDI', 'HINDI'),
        tCode('V', 'HUNG', 'HUNGARIAN'),
        tCode('V', 'ISLE', 'ISLANDIC'),
        tCode('V', 'ITAL', 'ITALIAN'),
        tCode('V', 'JAPA', 'JAPANESE'),
        tCode('V', 'KORE', 'KOREAN'),
        tCode('V', 'LAOT', 'LAOTIAN'),
        tCode('V', 'LATV', 'LATVIAN'),
        tCode('V', 'LITH', 'LITHUANIAN'),
        tCode('V', 'MONG', 'HMONG'),
        tCode('V', 'NORW', 'NORWEGIAN'),
        tCode('V', 'OTHE', 'OTHER'),
        tCode('V', 'PORT', 'PORTUGUESSE'),
        tCode('V', 'POPO', 'PORTUGESE-PORTUGUESE'),
        tCode('V', 'PRCI', 'PERSIAN FARSI'),
        tCode('V', 'RUSS', 'RUSSIAN'),
        tCode('V', 'SIGN', 'SIGN LANGUAGE'),
        tCode('V', 'SWED', 'SWEDISH'),
        tCode('V', 'THAI', 'THAI'),
        tCode('V', 'TURK', 'TURKISH'),
        tCode('V', 'UKRA', 'UKRANIAN'),
        tCode('V', 'UNKN', 'UNKNOWN'),
        tCode('V', 'VIET', 'VIETNAMESE'),
        tCode('V', 'YDSH', 'YIDDISH'),
        tCode('V', 'YUGO', 'YOGOSLAVIAN'),
        
        -- ****     MARITAL STATUS   ****        
        tCode('L', 'MSTATUS', 'MARITAL STATUS'),
        tCode('V', 'D', 'DIVORCED'),
        tCode('V', 'L', 'LEGALLY SEPARATED'),
        tCode('V', 'M', 'MARRIED'),
        tCode('V', 'P', 'PARTNER'),
        tCode('V', 'S', 'SINGLE'),
        tCode('V', 'U', 'UNKNOWN'),
        tCode('V', 'W', 'WIDOWED'),
        
        -- ****     NATIONALITY   ****        
        tCode('L', 'NATIONAL', 'NATIONALITY'),
        tCode('V', 'USA', 'AMERICAN'),
        tCode('V', 'CAN', 'CANADIAN'),
        tCode('V', 'MEX', 'MEXICAN'),
        
        -- ****     PERSON CATEGORY   ****        
        tCode('L', 'PERCAT', 'PERSON CATEGORY'),
        tCode('V', 'P', 'PERSON'),
      
        -- ****     PHONE TYPE   ****        
        tCode('L', 'PHONTYPE', 'PHONE TYPE'),
        tCode('V', 'CH', 'HOME'),
        tCode('V', 'CO', 'OFFICE'),
        tCode('V', 'CF', 'FAX'),
        tCode('V', 'CB', 'BUSINESS'),
        tCode('V', 'CBD', 'BUSINESS DIRECT'),
        tCode('V', 'CBA', 'BUSINESS ALTERNATE'),
        tCode('V', 'CP', 'PAGER'),
        tCode('V', 'CC', 'CELLULAR'),
        
        -- ****     RACE   ****        
        tCode('L', 'RACE', 'RACE'),
        tCode('V', 'I', 'AMERICAN INDIAN'),
        tCode('V', 'A', 'ASIAN'),
        tCode('V', 'B', 'BLACK'),
        tCode('V', 'H', 'HISPANIC'),
        tCode('V', 'O', 'OTHER'),
        tCode('V', 'R', 'REFUSED'),
        tCode('V', 'U', 'UNKNOWN'),
        tCode('V', 'W', 'WHITE'),
        
        -- ****     RELIGION   ****        
        tCode('L', 'RELIGION', 'RELIGION'),
        tCode('V', 'AC', 'ADVENT CHRISTIAN'),
        tCode('V', 'AG', 'AGNOSTIC'),
        tCode('V', 'AN', 'ANGLICAN'),
        tCode('V', 'AT', 'ATHEIST'),
        tCode('V', 'BA', 'BAHAI'),
        tCode('V', 'BP', 'BAPTIST'),
        tCode('V', 'BU', 'BUDHIST'),
        tCode('V', 'CH', 'CHRISTIAN'),
        tCode('V', 'CO', 'CONGREGATIONAL'),
        tCode('V', 'CS', 'CHRISTIAN SCIENTIST'),
        tCode('V', 'DC', 'DISCIPLES OF CHRIST'),
        tCode('V', 'DE', 'DEFERRED'),
        tCode('V', 'EC', 'EVANGELICAL CHRISTI'),
        tCode('V', 'EP', 'EPISCOPAL'),
        tCode('V', 'GO', 'GREEK ORTHODOX'),
        tCode('V', 'HI', 'HINDU'),
        tCode('V', 'JV', 'JEHOVAHS WITNESS'),
        tCode('V', 'JH', 'JEWISH'),
        tCode('V', 'LU', 'LUTHERAN'),
        tCode('V', 'ME', 'METHODIST'),
        tCode('V', 'MO', 'MORMON'),
        tCode('V', 'MS', 'MOSLEM'),
        tCode('V', 'MU', 'MUSLIM'),
        tCode('V', 'NO', 'NONE'),
        tCode('V', 'NP', 'NO PREFERENCE'),
        tCode('V', 'OR', 'ORTHODOX'),
        tCode('V', 'OT', 'OTHER'),
        tCode('V', 'PE', 'PENTECOSTAL HOLINES'),
        tCode('V', 'PR', 'PROTESTANT'),
        tCode('V', 'PS', 'PRESBYTERIAN'),
        tCode('V', 'QU', 'QUAKER'),
        tCode('V', 'RC', 'ROMAN CATHOLIC'),
        tCode('V', 'RO', 'RUSSIAN ORTHODOX'),
        tCode('V', 'SB', 'SOUTHERN BAPTIST'),
        tCode('V', 'SD', 'SEVENTH DAY ADVENTI'),
        tCode('V', 'UA', 'UNAFFILIATED'),
        tCode('V', 'UN', 'UNKNOWN'),
        tCode('V', 'UU', 'UNITARIAN'),
        
        -- ****     STATE CODE   ****        
        tCode('L', 'STATE', 'STATE CODE'),
        tCode('V', 'AL', 'ALABAMA'),
        tCode('V', 'AK', 'ALASKA'),
        tCode('V', 'AZ', 'ARIZONA'),
        tCode('V', 'AR', 'ARKANSAS'),
        tCode('V', 'CA', 'CALIFORNIA'),
        tCode('V', 'CO', 'COLORADO'),
        tCode('V', 'CT', 'CONNECTICUT'),
        tCode('V', 'DE', 'DELAWARE'),
        tCode('V', 'DC', 'DISTRICT OF COLUMBIA'),
        tCode('V', 'FL', 'FLORIDA'),
        tCode('V', 'GA', 'GEORGIA'),
        tCode('V', 'HI', 'HAWAII'),
        tCode('V', 'ID', 'IDAHO'),
        tCode('V', 'IL', 'ILLINOIS'),
        tCode('V', 'IN', 'INDIANA'),
        tCode('V', 'IA', 'IOWA'),
        tCode('V', 'KS', 'KANSAS'),
        tCode('V', 'KY', 'KENTUCKY'),
        tCode('V', 'LA', 'LOUISIANA'),
        tCode('V', 'ME', 'MAINE'),
        tCode('V', 'MD', 'MARYLAND'),
        tCode('V', 'MA', 'MASSACHUSETTS'),
        tCode('V', 'MI', 'MICHIGAN'),
        tCode('V', 'MN', 'MINNESOTA'),
        tCode('V', 'MS', 'MISSISSIPPI'),
        tCode('V', 'MO', 'MISSOURI'),
        tCode('V', 'MT', 'MONTANA'),
        tCode('V', 'NE', 'NEBRASKA'),
        tCode('V', 'NV', 'NEVADA'),
        tCode('V', 'NH', 'NEW HAMPSHIRE'),
        tCode('V', 'NJ', 'NEW JERSEY'),
        tCode('V', 'NM', 'NEW MEXICO'),
        tCode('V', 'NY', 'NEW YORK'),
        tCode('V', 'NC', 'NORTH CAROLINA'),
        tCode('V', 'ND', 'NORTH DAKOTA'),
        tCode('V', 'OH', 'OHIO'),
        tCode('V', 'OK', 'OKLAHOMA'),
        tCode('V', 'OR', 'OREGON'),
        tCode('V', 'PA', 'PENNSYLVANIA'),
        tCode('V', 'PR', 'PUERTO RICO'),
        tCode('V', 'RI', 'RHODE ISLAND'),
        tCode('V', 'SC', 'SOUTH CAROLINA'),
        tCode('V', 'SD', 'SOUTH DAKOTA'),
        tCode('V', 'TN', 'TENNESSEE'),
        tCode('V', 'TX', 'TEXAS'),
        tCode('V', 'UT', 'UTAH'),
        tCode('V', 'VT', 'VERMONT'),
        tCode('V', 'VI', 'VIRGIN ISLANDS'),
        tCode('V', 'VA', 'VIRGINIA'),
        tCode('V', 'WA', 'WASHINGTON'),
        tCode('V', 'WI', 'WISCONSIN'),
        tCode('V', 'WV', 'WEST VIRGINIA'),
        tCode('V', 'WY', 'WYOMING'),
        tCode('V', 'BC', 'BRITISH COLUMBIA'),
        tCode('V', 'YK', 'YUKON'),
        tCode('V', 'AB', 'ALBERTA'),
        tCode('V', 'SK', 'SASKATCHEWAN'),
        tCode('V', 'MB', 'MANITOBA'),
        tCode('V', 'ON', 'ONTARIO'),
        tCode('V', 'QU', 'QUEBEC'),
        tCode('V', 'NT', 'NORTHWEST TERRITORIES'),
        tCode('V', 'NF', 'NEWFOUNDLAND'),
        tCode('V', 'PE', 'PRINCE EDWARD ISLAND'),
        tCode('V', 'NB', 'NEW BRUNSWICH'),
        tCode('V', 'NS', 'NOVA SCOTIA'),
        
        -- ****     REGION CODE   ****        
        tCode('L', 'REGION', 'REGION CODE'),
        tCode('V', 'ABC', 'ABC REGION'),
        tCode('V', 'LMN', 'LMN REGION'),
        
        -- ****     SUFFIX   ****        
        tCode('L', 'SUFFIX', 'SUFFIX'),
        tCode('V', '2ND', '2ND'),
        tCode('V', '3RD', '3RD'),
        tCode('V', 'DDS', 'DDS'),
        tCode('V', 'DMD', 'DMD'),
        tCode('V', 'DVM', 'DVM'),
        tCode('V', 'ESQ', 'ESQ'),
        tCode('V', 'II', 'II'),
        tCode('V', 'III', 'III'),
        tCode('V', 'IV', 'IV'),
        tCode('V', 'JR', 'JR'),
        tCode('V', 'JRDDS', 'JRDDS'),
        tCode('V', 'JRESQ', 'JRESQ'),
        tCode('V', 'JRMD', 'JRMD'),
        tCode('V', 'JRPHD', 'JRPHD'),
        tCode('V', 'MD', 'MD'),
        tCode('V', 'MDESQ', 'MDESQ'),
        tCode('V', 'MDPHD', 'MDPHD'),
        tCode('V', 'RN', 'RN'),
        tCode('V', 'SR', 'SR'),
        tCode('V', 'SRDDS', 'SRDDS'),
        tCode('V', 'SRESQ', 'SRESQ'),
        tCode('V', 'SRMD', 'SRMD'),
        tCode('V', 'SRPHD', 'SRPHD'),
        
        -- ****     SOURCE   ****        
        tCode('L', 'SYSTEM', 'SOURCE'),
        tCode('V', 'HDQ', 'HEADQUARTERS'),
        tCode('V', 'FAC', 'FACILITY'),
        
        -- ****     TITLE   ****        
        tCode('L', 'TITLE', 'TITLE'),
        tCode('V', 'MD', 'MEDICAL DOCTOR'),
        tCode('V', 'PHD', 'PHD'),
        tCode('V', 'RN', 'REGISTERED NURSE'),
        tCode('V', 'CNA', 'CERTIFIED NURSES AID'),
        tCode('V', 'LVN', 'LVN'),
        
        -- ****     VETERAN STATUS   ****        
        tCode('L', 'VETSTS', 'VETERAN STATUS'),
        tCode('V', 'N', 'NONE'),
        tCode('V', 'Y', 'YES'),
        tCode('V', 'U', 'UNKNOWN'),
        
        -- ****     VIP FLAG   ****        
        tCode('L', 'VIPFLAG', 'VIP FLAG'),
        tCode('V', 'V', 'VIP'),
        tCode('V', 'E', 'EMPLOYEE'),
        tCode('V', 'N', 'NONE')
    );

begin

    select TO_CHAR(sysdate, 'MM/DD/YYYY') into v_date from dual;
    select user into v_user from dual;
    
    select appl_id into v_appl_id from sbyn_appl where code = 'EV';
    if SQL%NOTFOUND then
        dbms_output.put_line('ERROR: appl_id not found for EV.');
        goto abort;
    end if;

    delete from sbyn_common_detail where common_header_id in 
        (select common_header_id from sbyn_common_header
        where appl_id = v_appl_id);

    delete from sbyn_common_header 
    where appl_id = v_appl_id;

    update sbyn_seq_table set seq_count = seq_count + 1 
    where seq_name = 'SBYN_COMMON_HEADER';

    select seq_count - 1 into v_header_seq from sbyn_seq_table 
    where seq_name = 'SBYN_COMMON_HEADER';

    update sbyn_seq_table set seq_count = seq_count + 1 
    where seq_name = 'SBYN_COMMON_DETAIL';

    select seq_count - 1 into v_detail_seq from sbyn_seq_table 
    where seq_name = 'SBYN_COMMON_DETAIL';

    v_idx := codes.FIRST;
    WHILE v_idx <= codes.LAST LOOP
        IF codes(v_idx).type = 'L' THEN
            insert into sbyn_common_header (common_header_id, appl_id, code, descr, read_only, max_input_len, typ_table_code, create_date, create_userid)
            values (v_header_seq, v_appl_id, codes(v_idx).code, codes(v_idx).descr , 'Y', 8, 'XX', TO_DATE(v_date, 'MM/DD/YYYY'), v_user );
            v_header_seq := v_header_seq + 1;
        ELSE
            insert into sbyn_common_detail (common_detail_id, common_header_id, code, descr, read_only, create_date, create_userid)
            values (v_detail_seq, v_header_seq-1, codes(v_idx).code , codes(v_idx).descr, 'N', TO_DATE(v_date, 'MM/DD/YYYY'), v_user );
            v_detail_seq := v_detail_seq + 1;
        END IF;
        v_idx := codes.NEXT(v_idx);
    END LOOP;

    update sbyn_seq_table set seq_count =  v_header_seq
    where seq_name = 'SBYN_COMMON_HEADER';

    update sbyn_seq_table set seq_count =  v_detail_seq
    where seq_name = 'SBYN_COMMON_DETAIL';

    commit;

<<abort>>
    rollback;
end;
/