/*
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 *
 * Copyright 2003-2007 Sun Microsystems, Inc. All Rights Reserved.
 *
 * The contents of this file are subject to the terms of the Common 
 * Development and Distribution License ("CDDL")(the "License"). You 
 * may not use this file except in compliance with the License.
 *
 * You can obtain a copy of the License at
 * https://open-dm-mi.dev.java.net/cddl.html
 * or open-dm-mi/bootstrap/legal/license.txt. See the License for the 
 * specific language governing permissions and limitations under the  
 * License.  
 *
 * When distributing the Covered Code, include this CDDL Header Notice 
 * in each file and include the License file at
 * open-dm-mi/bootstrap/legal/license.txt.
 * If applicable, add the following below this CDDL Header, with the 
 * fields enclosed by brackets [] replaced by your own identifying 
 * information: "Portions Copyrighted [year] [name of copyright owner]"
 */
package com.sun.mdm.multidomain.ejb.service;

import javax.ejb.Stateless;
import javax.ejb.SessionContext;
import javax.ejb.Local;
import javax.ejb.Remote;
import javax.ejb.TransactionManagement;
import javax.ejb.TransactionManagementType;
import javax.ejb.TransactionAttributeType;
import javax.ejb.TransactionAttribute;

import javax.annotation.PostConstruct;
import javax.annotation.PreDestroy;
import javax.annotation.Resource;
import javax.annotation.Resources;
import javax.annotation.security.DeclareRoles;
        
import com.sun.mdm.index.master.UserException;
import com.sun.mdm.index.master.ProcessingException;
import com.sun.mdm.index.objects.epath.EPathArrayList;
import com.sun.mdm.index.objects.ObjectNode;
import com.sun.mdm.index.master.search.enterprise.EOSearchCriteria;
import com.sun.mdm.index.master.search.enterprise.EOSearchOptions;

import com.sun.mdm.multidomain.relationship.Relationship;
import com.sun.mdm.multidomain.relationship.HierarchyObject;

import com.sun.mdm.multidomain.query.MultiObject;
import com.sun.mdm.multidomain.query.MultiFieldValuePair;
import com.sun.mdm.multidomain.query.PageIterator;
import com.sun.mdm.multidomain.query.MultiDomainSearchCriteria;
import com.sun.mdm.multidomain.query.MultiDomainSearchOptions;


/**
 * The enterprise beans implementation of MultiDomainService that is explpsed to the clients.
 * The application-specific class will be generated by multidomain project during design time.
 * @author cye
 */
@Stateless(mappedName="ejb/MULTIDOMAIN_APPLICATION_TOKEN_MultiDomainService")
@Remote(MultiDomainServiceRemote.class)
@Local(MultiDomainServiceLocal.class)
@TransactionManagement(TransactionManagementType.CONTAINER)
@TransactionAttribute(value=TransactionAttributeType.REQUIRED)
@DeclareRoles({"MultiDomain.Admin","MultiDomain.User"})
/*
@EJB will be decided.
@Resources will be decided.
*/
public class MultiDomainServiceBean implements MultiDomainServiceRemote, MultiDomainServiceLocal {

    private SessionContext sessionContext;
      
    /**
     * Set SessionContext and called by the container when the bean is created.
     * @param sessionContext SessionContext.
     */
    @Resource
    public void setSessionContext(SessionContext sessionContext){
    	  this.sessionContext = sessionContext;
    }
     
    /**
     * Initialize resources.And onInitialization invocation occurs before the first 
     * business method invocation.
     * @throws ProcessingException Thrown if an error occurs during processing.
     */
    @PostConstruct
    public void onInitialization() 
        throws ProcessingException {
    }
    
    /**
     * Clean resources. And onTermination invocation occurs before the instance is 
     * removed by the container.
     */
    @PreDestroy
    public void onTermination(){
    }    
    
    /**
     * @see com.sun.mdm.multidomain.ejb.service.MultiDomainService#createRelationship()
     */        
    public String createRelationship(String sourceEUDI, String targetEUID, Relationship relationshp)
        throws ProcessingException, UserException {
        throw new ProcessingException("Not Implemented Yet.");
    }

    /**
     * @see com.sun.mdm.multidomain.ejb.service.MultiDomainService#createRelationship()
     */            
    public String createRelationship(String sourceSystemCode, String sourceLID, 
                                     String targetSystemCode, String targetLID, 
                                     Relationship relationship) 
        throws ProcessingException, UserException {
        throw new ProcessingException("Not Implemented Yet.");
    }

    /**
     * @see com.sun.mdm.multidomain.ejb.service.MultiDomainService#createRelationship()
     */            
    public String createRelationship(MultiFieldValuePair sourceMultiPairValue, MultiFieldValuePair targetMultiPairValue, 
                                     Relationship relationship) 
        throws ProcessingException, UserException {
        throw new ProcessingException("Not Implemented Yet.");
    }
    
    /**
     * @see com.sun.mdm.multidomain.ejb.service.MultiDomainService#updateRelationship()
     */            
    public void updateRelationship(String sourceEUID, String targetEUID, Relationship relationship) 
        throws ProcessingException, UserException {
        throw new ProcessingException("Not Implemented Yet.");
    }
    
    /**
     * @see com.sun.mdm.multidomain.ejb.service.MultiDomainService#deleteRelationship()
     */            
    public void deleteRelationship(String sourceEUID, String targetEUID, Relationship relationshp) 
        throws ProcessingException, UserException {
        throw new ProcessingException("Not Implemented Yet.");
    }

    /**
     * @see com.sun.mdm.multidomain.ejb.service.MultiDomainService#deleteRelationship()
     */                
    public void deleteRelationship(String sourceSystemCode, String sourceLID, 
                                     String targetSystemCode, String targetLID, Relationship relationship)
        throws ProcessingException, UserException {
        throw new ProcessingException("Not Implemented Yet.");
    }

    /**
     * @see com.sun.mdm.multidomain.ejb.service.MultiDomainService#searchRelationships()
     */                
    public PageIterator<MultiObject> searchRelationships(MultiDomainSearchOptions searchOptions, MultiDomainSearchCriteria searchCriteria) 
        throws ProcessingException, UserException {
        throw new ProcessingException("Not Implemented Yet.");
    }

    /**
     * @see com.sun.mdm.multidomain.ejb.service.MultiDomainService#searchRelationships()
     */                    
    public PageIterator<MultiObject> searchRelationships(String sourceDomain, EPathArrayList[] sourceEPathList, 
                                                 String targetDomain, EPathArrayList[] targetEPathList, MultiDomainSearchCriteria searchCriteria) 
        throws ProcessingException, UserException {
        throw new ProcessingException("Not Implemented Yet.");
    }
    
    /**
     * @see com.sun.mdm.multidomain.ejb.service.MultiDomainService#searchEnterprises()
     */                    
    public PageIterator<ObjectNode> searchEnterprises(String domain, EOSearchOptions searchOptions, EOSearchCriteria searchCriteria)
        throws ProcessingException, UserException {
        throw new ProcessingException("Not Implemented Yet.");
    }

    /**
     * @see com.sun.mdm.multidomain.ejb.service.MultiDomainService#createHierarchy()
     */                        
    public String createHierarchy(String parentEUID, String childEUID, Relationship hierarchy)
        throws ProcessingException, UserException {
        throw new ProcessingException("Not Implemented Yet.");
    }

    /**
     * @see com.sun.mdm.multidomain.ejb.service.MultiDomainService#createHierarchy()
     */                            
    public String createHierarchy(String parentEUID, String[] childEUIDs, Relationship hierarchy)
        throws ProcessingException, UserException {
        throw new ProcessingException("Not Implemented Yet.");
    }
    
    /**
     * @see com.sun.mdm.multidomain.ejb.service.MultiDomainService#createHierarchy()
     */                            
    public String createHierarchy(MultiFieldValuePair parentFieldValues, MultiFieldValuePair[] childFieldValues, Relationship hierarchy)
        throws ProcessingException, UserException {
        throw new ProcessingException("Not Implemented Yet.");
    }

    /**
     * @see com.sun.mdm.multidomain.ejb.service.MultiDomainService#deleteHierarchy()
     */                            
    public void deleteHierarchy(String parentEUID, String childEUID, Relationship hierarchy)
        throws ProcessingException, UserException {
        throw new ProcessingException("Not Implemented Yet.");
    }

    /**
     * @see com.sun.mdm.multidomain.ejb.service.MultiDomainService#deleteHierarchy()
     */                                
    public void deleteHierarchy(String parentEUID, String[] childEUIDs, Relationship hierarchy)
        throws ProcessingException, UserException {
        throw new ProcessingException("Not Implemented Yet.");
    }

    /**
     * @see com.sun.mdm.multidomain.ejb.service.MultiDomainService#updateHierarchy()
     */                                
    public void updateHierarchy(String parentEUID, String childEUID, Relationship hierarchy)
        throws ProcessingException, UserException {
        throw new ProcessingException("Not Implemented Yet.");
    }

    /**
     * @see com.sun.mdm.multidomain.ejb.service.MultiDomainService#updateHierarchy()
     */                                    
    public void updateHierarchy(String parentEUID, String[] childEUIDs, Relationship hierarchy)
        throws ProcessingException, UserException {
        throw new ProcessingException("Not Implemented Yet.");
    }
    
    /**
     * @see com.sun.mdm.multidomain.ejb.service.MultiDomainService#searchHierarchy()
     */                                    
    public HierarchyObject searchHierarchy(String domain, String EUID, EPathArrayList ePathFields)
        throws ProcessingException, UserException {
        throw new ProcessingException("Not Implemented Yet.");
    }
            
    /**
     * @see com.sun.mdm.multidomain.ejb.service.MultiDomainService#createGroup()
     */                                    
    public String createGroup(Relationship group)
        throws ProcessingException, UserException {
        throw new ProcessingException("Not Implemented Yet.");
    }

    /**
     * @see com.sun.mdm.multidomain.ejb.service.MultiDomainService#createGroupMembers()
     */                                        
    public String[] createGroupMembers(String groupId, String EUIDs[], Relationship relationship)
        throws ProcessingException, UserException {
        throw new ProcessingException("Not Implemented Yet.");
    }
            
    /**
     * @see com.sun.mdm.multidomain.ejb.service.MultiDomainService#deleteGroup()
     */                                        
    public void deleteGroup(Relationship group)
            throws ProcessingException, UserException {
        throw new ProcessingException("Not Implemented Yet.");
    }

    /**
     * @see com.sun.mdm.multidomain.ejb.service.MultiDomainService#deleteGroup()
     */                                            
    public void deleteGroup(String domain, String groupId)
        throws ProcessingException, UserException {
        throw new ProcessingException("Not Implemented Yet.");
    }

    /**
     * @see com.sun.mdm.multidomain.ejb.service.MultiDomainService#deleteGroupMember()
     */                                            
    public void deleteGroupMember(String domain, String groupId, String EUID)
        throws ProcessingException, UserException {
        throw new ProcessingException("Not Implemented Yet.");
    }
    
    /**
     * @see com.sun.mdm.multidomain.ejb.service.MultiDomainService#updateGroup()
     */                                            
    public void updateGroup(Relationship group)
            throws ProcessingException, UserException {
        throw new ProcessingException("Not Implemented Yet.");
    }
            
    /**
     * @see com.sun.mdm.multidomain.ejb.service.MultiDomainService#searchGroup()
     */                                            
    public Relationship[] searchGroup(Relationship relationship)
            throws ProcessingException, UserException {
        throw new ProcessingException("Not Implemented Yet.");
    }

    /**
     * @see com.sun.mdm.multidomain.ejb.service.MultiDomainService#getGroupMembers()
     */                                            
    public ObjectNode[] getGroupMembers(String domain, String groupId, EPathArrayList fields) 
            throws ProcessingException, UserException {
        throw new ProcessingException("Not Implemented Yet.");
    }
            
    /**
     * @see com.sun.mdm.multidomain.ejb.service.MultiDomainService#getGroups()
     */                                            
    public Relationship[] getGroups(String domain, String EUID)
            throws ProcessingException, UserException {
        throw new ProcessingException("Not Implemented Yet.");
    }

    /**
     * @see com.sun.mdm.multidomain.ejb.service.MultiDomainService#updateGroupMember()
     */                                            
    public void updateGroupMember(String domain, String EUID, Relationship relationship) 
            throws ProcessingException, UserException {
        throw new ProcessingException("Not Implemented Yet.");
    }
                    
}
