/*
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 *
 * Copyright 2003-2007 Sun Microsystems, Inc. All Rights Reserved.
 *
 * The contents of this file are subject to the terms of the Common 
 * Development and Distribution License ("CDDL")(the "License"). You 
 * may not use this file except in compliance with the License.
 *
 * You can obtain a copy of the License at
 * https://open-dm-mi.dev.java.net/cddl.html
 * or open-dm-mi/bootstrap/legal/license.txt. See the License for the 
 * specific language governing permissions and limitations under the  
 * License.  
 *
 * When distributing the Covered Code, include this CDDL Header Notice 
 * in each file and include the License file at
 * open-dm-mi/bootstrap/legal/license.txt.
 * If applicable, add the following below this CDDL Header, with the 
 * fields enclosed by brackets [] replaced by your own identifying 
 * information: "Portions Copyrighted [year] [name of copyright owner]"
 */
package com.sun.mdm.multidomain.ejb.service;

import javax.ejb.EJB;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.ejb.Stateless;

import com.sun.mdm.index.master.ProcessingException;
import com.sun.mdm.index.master.UserException;

import com.sun.mdm.multidomain.group.Group;

/**
 * MultiDomainWebService class. The application-specific class will be generated by multidomain project 
 * during design time. Defining MultiDomainWebService is in progress. Here is a template only.
 * @author cye
 */
@WebService()
@Stateless()
public class MultiDomainWebService {
    /* @EJB */
    private MultiDomainServiceLocal multiDomainServiceLocal;

    /**
     * @see com.sun.mdm.multidomain.ejb.service.MultiDomainService#getGroups() 
     */            
    @WebMethod(operationName = "searchGroups")
    public Group[] getGroups( @WebParam(name = "group")
    Group group) throws ProcessingException, UserException {        
        return multiDomainServiceLocal.searchGroup(group);
    }
    
}
