/*
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 *
 * Copyright 2003-2007 Sun Microsystems, Inc. All Rights Reserved.
 *
 * The contents of this file are subject to the terms of the Common 
 * Development and Distribution License ("CDDL")(the "License"). You 
 * may not use this file except in compliance with the License.
 *
 * You can obtain a copy of the License at
 * https://open-dm-mi.dev.java.net/cddl.html
 * or open-dm-mi/bootstrap/legal/license.txt. See the License for the 
 * specific language governing permissions and limitations under the  
 * License.  
 *
 * When distributing the Covered Code, include this CDDL Header Notice 
 * in each file and include the License file at
 * open-dm-mi/bootstrap/legal/license.txt.
 * If applicable, add the following below this CDDL Header, with the 
 * fields enclosed by brackets [] replaced by your own identifying 
 * information: "Portions Copyrighted [year] [name of copyright owner]"
 */
package com.sun.mdm.multidomain.ejb.service;

import javax.ejb.Stateless;
import javax.ejb.SessionContext;
import javax.ejb.Local;
import javax.ejb.Remote;
import javax.ejb.TransactionManagement;
import javax.ejb.TransactionManagementType;

import javax.annotation.PostConstruct;
import javax.annotation.PreDestroy;
import javax.annotation.Resource;
import javax.annotation.Resources;
import javax.annotation.security.DeclareRoles;
        
import com.sun.mdm.index.master.UserException;
import com.sun.mdm.index.master.ProcessingException;
import com.sun.mdm.index.objects.epath.EPathArrayList;
import com.sun.mdm.index.objects.ObjectNode;

import com.sun.mdm.multidomain.relationship.Relationship;
import com.sun.mdm.multidomain.relationship.HierarchyObject;

import com.sun.mdm.multidomain.query.MultiFieldValuePair;
import com.sun.mdm.multidomain.query.PageMultiIterator;
import com.sun.mdm.multidomain.query.PageSingleIterator;
import com.sun.mdm.multidomain.query.MultiDomainSearchCriteria;
import com.sun.mdm.multidomain.query.MultiDomainSearchOptions;


/**
 * The enterprise beans implementation of MultiDomainService that is explpsed to the clients.
 * The class will be generated by multidomain project during design time for the application-specific.
 * @author cye
 */
@Stateless(mappedName="ejb/MultiDomainService")
@Remote(MultiDomainServiceRemote.class)
@Local(MultiDomainServiceLocal.class)
@TransactionManagement(TransactionManagementType.CONTAINER)
@DeclareRoles({"MultiDomain.Admin","MultiDomain.User"})
public class MultiDomainServiceBean implements MultiDomainServiceRemote, MultiDomainServiceLocal {

    private SessionContext sessionContext;
      
    @Resource
    public void setSessionContext(SessionContext sessionContext){
    	  this.sessionContext = sessionContext;
    }
     
    @PostConstruct
    public void onInitialization(){
    }
    
    @PreDestroy
    public void onTermination(){
    }    
    
    /**
     * @see com.sun.mdm.multidomain.ejb.service.MultiDomainService#createRelationship()
     */        
    public String createRelationship(String sourceEUDI, String targetEUID, Relationship relationshp)
        throws ProcessingException, UserException {
        throw new ProcessingException("Not Implemented Yet.");
    }
    
    /**
     * @see com.sun.mdm.multidomain.ejb.service.MultiDomainService#createRelationship()
     */        
    public String createRelationship(String sourceSystemCode, String sourceLID, 
                                     String targetSystemCode, String targetLID, 
                                     Relationship relationship) 
        throws ProcessingException, UserException {
        throw new ProcessingException("Not Implemented Yet.");
    }

    /**
     * @see com.sun.mdm.multidomain.ejb.service.MultiDomainService#createRelationship()
     */            
    public String createRelationship(MultiFieldValuePair sourceMultiPairValue, MultiFieldValuePair targetMultiPairValue, 
                                     Relationship relationship) 
        throws ProcessingException, UserException {
        throw new ProcessingException("Not Implemented Yet.");
    }
    
    /**
     * @see com.sun.mdm.multidomain.ejb.service.MultiDomainService#updateRelationship()
     */            
    public String updateRelationship(String sourceEUID, String targetEUID, Relationship relationship) 
        throws ProcessingException, UserException {
        throw new ProcessingException("Not Implemented Yet.");
    }
    
    /**
     * @see com.sun.mdm.multidomain.ejb.service.MultiDomainService#deleteRelationship()
     */            
    public String deleteRelationship(String sourceEUID, String targetEUID, Relationship relationshp) 
        throws ProcessingException, UserException {
        throw new ProcessingException("Not Implemented Yet.");
    }
            
    /**
     * @see com.sun.mdm.multidomain.ejb.service.MultiDomainService#deleteRelationship()
     */            
    public String deleteRelationship(String sourceSystemCode, String sourceLID, 
                                     String targetSystemCode, String targetLID, Relationship relationship)
        throws ProcessingException, UserException {
        throw new ProcessingException("Not Implemented Yet.");
    }

    /**
     * @see com.sun.mdm.multidomain.ejb.service.MultiDomainService#searchRelationships()
     */            
    public PageMultiIterator searchRelationships(MultiDomainSearchOptions searchOptions, MultiDomainSearchCriteria searchCriteria) 
        throws ProcessingException, UserException {
        throw new ProcessingException("Not Implemented Yet.");
    }
            
    /**
     * @see com.sun.mdm.multidomain.ejb.service.MultiDomainService#searchRelationships()
     */            
    public PageMultiIterator searchRelationships(String sourceDomain, EPathArrayList[] sourceEPathList, 
                                                 String targetDomain, EPathArrayList[] targetEPathList, MultiDomainSearchOptions searchOptions) 
        throws ProcessingException, UserException {
        throw new ProcessingException("Not Implemented Yet.");
    }
    
    /**
     * @see com.sun.mdm.multidomain.ejb.service.MultiDomainService#searchEnterprise()
     */            
    public PageSingleIterator searchEnterprise(MultiDomainSearchOptions searchOptions, MultiDomainSearchCriteria searchCriteria)
        throws ProcessingException, UserException {
        throw new ProcessingException("Not Implemented Yet.");
    }

    /**
     * @see com.sun.mdm.multidomain.ejb.service.MultiDomainService#createHierarchy()
     */                
    public String createHierarchy(String parentEUID, String childEUID, Relationship relationship)
        throws ProcessingException, UserException {
        throw new ProcessingException("Not Implemented Yet.");
    }

    /**
     * @see com.sun.mdm.multidomain.ejb.service.MultiDomainService#createHierarchy()
     */                    
    public String createHierarchy(String parentEUID, String[] childEUIDs, Relationship relationship)
        throws ProcessingException, UserException {
        throw new ProcessingException("Not Implemented Yet.");
    }
    
    /**
     * @see com.sun.mdm.multidomain.ejb.service.MultiDomainService#createHierarchy()
     */                    
    public String createHierarchy(MultiFieldValuePair parentFieldValues, MultiFieldValuePair[] childFieldValues, Relationship relationship)
        throws ProcessingException, UserException {
        throw new ProcessingException("Not Implemented Yet.");
    }

    /**
     * @see com.sun.mdm.multidomain.ejb.service.MultiDomainService#deleteHierarchy()
     */                    
    public String deleteHierarchy(String parentEUID, String childEUID, Relationship relationship)
        throws ProcessingException, UserException {
        throw new ProcessingException("Not Implemented Yet.");
    }
    
    /**
     * @see com.sun.mdm.multidomain.ejb.service.MultiDomainService#deleteHierarchy()
     */                    
    public String deleteHierarchy(String parentEUID, String[] childEUIDs, Relationship relationship)
        throws ProcessingException, UserException {
        throw new ProcessingException("Not Implemented Yet.");
    }
    
    /**
     * @see com.sun.mdm.multidomain.ejb.service.MultiDomainService#updateHierarchy()
     */                    
    public String updateHierarchy(String parentEUID, String childEUID, Relationship relationship)
        throws ProcessingException, UserException {
        throw new ProcessingException("Not Implemented Yet.");
    }
    
    /**
     * @see com.sun.mdm.multidomain.ejb.service.MultiDomainService#updateHierarchy()
     */                    
    public String updateHierarchy(String parentEUID, String[] childEUIDs, Relationship relationship)
        throws ProcessingException, UserException {
        throw new ProcessingException("Not Implemented Yet.");
    }
    
    /**
     * @see com.sun.mdm.multidomain.ejb.service.MultiDomainService#searchHierarchy()
     */                    
    public HierarchyObject searchHierarchy(String domain, String EUID, EPathArrayList ePathFields)
        throws ProcessingException, UserException {
        throw new ProcessingException("Not Implemented Yet.");
    }
            
    /**
     * @see com.sun.mdm.multidomain.ejb.service.MultiDomainService#createGroup()
     */                    
    public String createGroup(Relationship relationship)
        throws ProcessingException, UserException {
        throw new ProcessingException("Not Implemented Yet.");
    }
            
    /**
     * @see com.sun.mdm.multidomain.ejb.service.MultiDomainService#createGroup()
     */                        
    public String[] createGroups(String groupId, String EUIDs[], Relationship relationship)
        throws ProcessingException, UserException {
        throw new ProcessingException("Not Implemented Yet.");
    }
            
    /**
     * @see com.sun.mdm.multidomain.ejb.service.MultiDomainService#deleteGroup()
     */                        
    public String deleteGroup(Relationship group)
            throws ProcessingException, UserException {
        throw new ProcessingException("Not Implemented Yet.");
    }
    
    /**
     * @see com.sun.mdm.multidomain.ejb.service.MultiDomainService#deleteGroup()
     */                        
    public String deleteGroup(String domain, String groupId)
        throws ProcessingException, UserException {
        throw new ProcessingException("Not Implemented Yet.");
    }

    /**
     * @see com.sun.mdm.multidomain.ejb.service.MultiDomainService#deleteGroup()
     */                        
    public String deleteGroup(String domain, String groupId, String EUID)
        throws ProcessingException, UserException {
        throw new ProcessingException("Not Implemented Yet.");
    }
    
    /**
     * @see com.sun.mdm.multidomain.ejb.service.MultiDomainService#updateGroup()
     */                        
    public String updateGroup(Relationship group)
            throws ProcessingException, UserException {
        throw new ProcessingException("Not Implemented Yet.");
    }
            
    /**
     * @see com.sun.mdm.multidomain.ejb.service.MultiDomainService#searchGroup()
     */                        
    public Relationship[] searchGroup(Relationship group)
            throws ProcessingException, UserException {
        throw new ProcessingException("Not Implemented Yet.");
    }
    
    /**
     * @see com.sun.mdm.multidomain.ejb.service.MultiDomainService#searchGroupMember()
     */                        
    public ObjectNode[] getGroupMembers(String domain, String groupId, EPathArrayList fields) 
            throws ProcessingException, UserException {
        throw new ProcessingException("Not Implemented Yet.");
    }
            
    /**
     * @see com.sun.mdm.multidomain.ejb.service.MultiDomainService#getGroups()
     */                        
    public Relationship[] getGroups(String domain, String EUID)
            throws ProcessingException, UserException {
        throw new ProcessingException("Not Implemented Yet.");
    }

    /**
     * @see com.sun.mdm.multidomain.ejb.service.MultiDomainService#updateGroup()
     */                        
    public String updateGroup(String domain, String EUID, Relationship group) 
            throws ProcessingException, UserException {
        throw new ProcessingException("Not Implemented Yet.");
    }
    
}
