CREATE TABLE SBYN_SYSTEMS
(
    SYSTEMCODE		VARCHAR2(20)	NOT NULL,
    DESCRIPTION		VARCHAR2(50)	NOT NULL,
    STATUS		CHAR		NOT NULL,
    ID_LENGTH		INTEGER		NOT NULL,
    FORMAT		VARCHAR2(60)	NULL    ,
    INPUT_MASK		VARCHAR2(60)	NULL    ,
    VALUE_MASK		VARCHAR2(60)	NULL    ,
    CREATE_DATE		DATE		NOT NULL,
    CREATE_USERID	VARCHAR2(20)	NOT NULL,
    UPDATE_DATE		DATE		NULL    ,
    UPDATE_USERID	VARCHAR2(20)	NULL    ,
    CONSTRAINT PK_SBYN_SYSTEM PRIMARY KEY (SYSTEMCODE)
        USING INDEX
);

CREATE TABLE SBYN_USER_CODE
(
    CODE_LIST		VARCHAR2(20)	NOT NULL,
    CODE			VARCHAR2(20)	NOT NULL,
    DESCR			VARCHAR2(50)	NOT NULL,
    FORMAT			VARCHAR2(60)	NULL    ,
    INPUT_MASK		VARCHAR2(60)	NULL    ,
    VALUE_MASK		VARCHAR2(60)	NULL    ,
    CONSTRAINT PK_SBYN_USER_CODE PRIMARY KEY (CODE_LIST, CODE)
        USING INDEX
);

CREATE TABLE SBYN_SYSTEMOBJECT (
	SYSTEMCODE VARCHAR2(20),
	LID VARCHAR2(25),
	CHILDTYPE VARCHAR2(20),
	CREATEUSER VARCHAR2(30),
	CREATEFUNCTION VARCHAR2(20),
	CREATEDATE DATE,
	UPDATEUSER VARCHAR2(30),
	UPDATEFUNCTION VARCHAR2(20),
	UPDATEDATE DATE,
	STATUS VARCHAR2(15));

ALTER TABLE SBYN_SYSTEMOBJECT ADD CONSTRAINT PK_SBYNSYSTEMOBJECT PRIMARY KEY (SYSTEMCODE, LID);
ALTER TABLE SBYN_SYSTEMOBJECT ADD CONSTRAINT FK_SYSTEMOBJECT_SYSTEMCODE FOREIGN KEY (SYSTEMCODE) REFERENCES SBYN_SYSTEMS(SYSTEMCODE);

CREATE TABLE SBYN_SYSTEMSBR (
	EUID VARCHAR2(20),
	CHILDTYPE VARCHAR2(20),
	CREATESYSTEM VARCHAR2(20),
	CREATEUSER VARCHAR2(30),
	CREATEFUNCTION VARCHAR2(20),
	CREATEDATE DATE,
	UPDATESYSTEM VARCHAR2(20),
	UPDATEUSER VARCHAR2(30),
	UPDATEFUNCTION VARCHAR2(20),
	UPDATEDATE DATE,
	STATUS VARCHAR2(15),
      REVISIONNUMBER NUMBER(38));

ALTER TABLE SBYN_SYSTEMSBR ADD CONSTRAINT PK_SBYNSYSTEMSBR PRIMARY KEY (EUID);

CREATE TABLE SBYN_OVERWRITE (
	EUID VARCHAR2(20),
	PATH VARCHAR2(200),
	TYPE VARCHAR2(20),
	INTEGERDATA NUMBER(38),
	BOOLEANDATA NUMBER(38),
	STRINGDATA VARCHAR2(200),
	BYTEDATA CHAR(2),
	LONGDATA LONG,
	DATEDATA DATE,
	FLOATDATA NUMBER(38, 4),
	TIMESTAMPDATA DATE);

ALTER TABLE SBYN_OVERWRITE ADD CONSTRAINT FK_SYSTEMSBR_EUID FOREIGN KEY (EUID) REFERENCES SBYN_SYSTEMSBR(EUID) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE SBYN_OVERWRITE ADD CONSTRAINT PK_SBROVERWRITE PRIMARY KEY (EUID, PATH);

CREATE TABLE SBYN_ENTERPRISE (
	SYSTEMCODE VARCHAR2(20),
	LID VARCHAR2(25),
	EUID VARCHAR2(20));

ALTER TABLE SBYN_ENTERPRISE ADD CONSTRAINT FK_ENTERPRISE_SYSTEMCODE_LID FOREIGN KEY (SYSTEMCODE, LID) REFERENCES SBYN_SYSTEMOBJECT(SYSTEMCODE, LID) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE SBYN_ENTERPRISE ADD CONSTRAINT FK_ENTERPRISE_EUID FOREIGN KEY (EUID) REFERENCES SBYN_SYSTEMSBR(EUID) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE SBYN_ENTERPRISE ADD CONSTRAINT PK_ENTERPRISE PRIMARY KEY (SYSTEMCODE, LID, EUID);

CREATE TABLE SBYN_TRANSACTION (
	TRANSACTIONNUMBER VARCHAR2(20),
	LID1 VARCHAR2(25),
	LID2 VARCHAR2(25),
	EUID1 VARCHAR2(20),
	EUID2 VARCHAR2(20),
	FUNCTION VARCHAR2(20),
	SYSTEMUSER VARCHAR2(30),
	TIMESTAMP TIMESTAMP,
	DELTA BLOB,
	SYSTEMCODE VARCHAR2(20),
	LID VARCHAR2(25),
	EUID VARCHAR2(20));

ALTER TABLE SBYN_TRANSACTION ADD CONSTRAINT PK_TRANSACTION PRIMARY KEY (TRANSACTIONNUMBER);
ALTER TABLE SBYN_TRANSACTION ADD CONSTRAINT AK_TRANSACTION UNIQUE (EUID, EUID2, TRANSACTIONNUMBER);

CREATE TABLE SBYN_ASSUMEDMATCH (
    ASSUMEDMATCHID VARCHAR2(20),
    EUID VARCHAR2(20),
    SYSTEMCODE VARCHAR2(20),
	LID VARCHAR2(25),
    WEIGHT VARCHAR2(20),
    TRANSACTIONNUMBER VARCHAR(20));
    

ALTER TABLE SBYN_ASSUMEDMATCH ADD CONSTRAINT FK_AM_TRANSACTIONNUMBER FOREIGN KEY (TRANSACTIONNUMBER) REFERENCES SBYN_TRANSACTION(TRANSACTIONNUMBER);

CREATE TABLE SBYN_POTENTIALDUPLICATES (
	POTENTIALDUPLICATEID VARCHAR2(20),
	WEIGHT VARCHAR2(20),
	TYPE VARCHAR2(15),
	DESCRIPTION VARCHAR2(120),
	STATUS VARCHAR2(15),
	HIGHMATCHFLAG VARCHAR2(15),
	RESOLVEDUSER VARCHAR2(30),
	RESOLVEDDATE DATE,
	RESOLVEDCOMMENT VARCHAR2(120),
	EUID2 VARCHAR2(20),
	TRANSACTIONNUMBER VARCHAR2(20),
	EUID1 VARCHAR2(20));

ALTER TABLE SBYN_POTENTIALDUPLICATES ADD CONSTRAINT PK_POTENTIALDUPLICATES PRIMARY KEY (POTENTIALDUPLICATEID);

CREATE TABLE SBYN_AUDIT (
	AUDIT_ID VARCHAR2(20) NOT NULL,
	PRIMARY_OBJECT_TYPE VARCHAR2(20) ,
	EUID VARCHAR2(20) ,
	EUID_AUX VARCHAR2(20),
	FUNCTION VARCHAR2(32) NOT NULL,
	DETAIL VARCHAR2(120),
	CREATE_DATE DATE NOT NULL,
	CREATE_BY VARCHAR2(20) NOT NULL);

ALTER TABLE SBYN_AUDIT ADD CONSTRAINT PK_SBYN_AUDIT PRIMARY KEY (AUDIT_ID);

CREATE TABLE SBYN_MERGE (
	MERGE_ID VARCHAR2(20) NOT NULL,
    KEPT_EUID VARCHAR2(20) NOT NULL,
    MERGED_EUID VARCHAR2(20),
    MERGE_TRANSACTIONNUM VARCHAR2(20) NOT NULL,
    UNMERGE_TRANSACTIONNUM VARCHAR2(20));

ALTER TABLE SBYN_MERGE ADD CONSTRAINT FK_SBYN_MERGE FOREIGN KEY (KEPT_EUID, MERGED_EUID, MERGE_TRANSACTIONNUM) REFERENCES SBYN_TRANSACTION(EUID, EUID2, TRANSACTIONNUMBER) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE SBYN_MERGE ADD CONSTRAINT PK_SBYN_MERGE PRIMARY KEY (MERGE_ID);

CREATE TABLE SBYN_APPL
(
    APPL_ID                  NUMBER(10)             NOT NULL,
    CODE                     VARCHAR2(8)            NOT NULL,
    DESCR                    VARCHAR2(30)           NOT NULL,
    READ_ONLY                CHAR(1)                DEFAULT 'N' NOT NULL
        CONSTRAINT CHK_SBYN_APPL CHECK (READ_ONLY IN ('Y','N')),
    CREATE_DATE              DATE                   NOT NULL,
    CREATE_USERID            VARCHAR2(20)           NOT NULL,
    CONSTRAINT PK_UP_SBYN_APPL PRIMARY KEY (APPL_ID)
)
;
CREATE UNIQUE INDEX SBYN_APPL_IDX1 ON SBYN_APPL (CODE ASC);

CREATE TABLE SBYN_COMMON_HEADER
(
    COMMON_HEADER_ID         NUMBER(10)             NOT NULL,
    APPL_ID                  NUMBER(10)             NOT NULL,
    CODE                     VARCHAR2(8)            NOT NULL,
    DESCR                    VARCHAR2(50)           NOT NULL,
    READ_ONLY                CHAR(1)                DEFAULT 'N' NOT NULL,
    MAX_INPUT_LEN            NUMBER(10)             DEFAULT 1 NOT NULL,
    TYP_TABLE_CODE           VARCHAR2(3)            NOT NULL,
    CREATE_DATE              DATE                   NOT NULL,
    CREATE_USERID            VARCHAR2(20)           NOT NULL,
    CONSTRAINT PK_SBYN_COMMON_HEADER PRIMARY KEY (COMMON_HEADER_ID)
)
;
CREATE INDEX FK_SBYN_COMMON_HEADER ON SBYN_COMMON_HEADER (APPL_ID ASC);
CREATE UNIQUE INDEX SBYN_COMMOM_HEADER_IDX1 ON SBYN_COMMON_HEADER (APPL_ID ASC, CODE ASC);

CREATE TABLE SBYN_COMMON_DETAIL
(
    COMMON_DETAIL_ID         NUMBER(10)             NOT NULL
        CONSTRAINT CHK_COMMON_DETAIL_ID CHECK (COMMON_DETAIL_ID >= 0),
    COMMON_HEADER_ID         NUMBER(10)             NOT NULL,
    CODE                     VARCHAR2(20)           NOT NULL,
    DESCR                    VARCHAR2(50)           NOT NULL,
    READ_ONLY                CHAR(1)                DEFAULT 'N' NOT NULL
        CONSTRAINT CHK_SBYN_COMMON_DETAIL CHECK (READ_ONLY IN ('Y','N')),
    CREATE_DATE              DATE                   NOT NULL,
    CREATE_USERID            VARCHAR2(20)           NOT NULL,
    CONSTRAINT PK_SBYN_COMMON_DETAIL PRIMARY KEY (COMMON_DETAIL_ID)
)
;
CREATE UNIQUE INDEX SBYN_COMMOM_DETAIL_IDX1 ON SBYN_COMMON_DETAIL (COMMON_HEADER_ID ASC, CODE ASC);

ALTER TABLE SBYN_COMMON_DETAIL
    ADD CONSTRAINT FK_COMM_DET_COMM_HEAD FOREIGN KEY  (COMMON_HEADER_ID)
       REFERENCES SBYN_COMMON_HEADER (COMMON_HEADER_ID)
;

CREATE INDEX SBYN_ENTERPRISE1 on SBYN_ENTERPRISE (EUID ASC);
CREATE INDEX SBYN_TRANSACTION1 on SBYN_TRANSACTION (TIMESTAMP ASC);
CREATE INDEX SBYN_TRANSACTION2 on SBYN_TRANSACTION (FUNCTION ASC);
CREATE INDEX SBYN_TRANSACTION4 on SBYN_TRANSACTION (EUID2 ASC, TIMESTAMP ASC);
CREATE INDEX SBYN_TRANSACTION3 on SBYN_TRANSACTION (TIMESTAMP ASC, TRANSACTIONNUMBER ASC);
ALTER TABLE SBYN_ASSUMEDMATCH ADD CONSTRAINT PK_ASSUMEDMATCH PRIMARY KEY (ASSUMEDMATCHID);
CREATE INDEX SBYN_ASSUMEDMATCH1 on SBYN_ASSUMEDMATCH (EUID ASC);
CREATE INDEX SBYN_ASSUMEDMATCH2 ON SBYN_ASSUMEDMATCH (TRANSACTIONNUMBER ASC);
CREATE INDEX SBYN_POTENTIALDUPLICATES1 on SBYN_POTENTIALDUPLICATES (EUID1 ASC);
CREATE INDEX SBYN_POTENTIALDUPLICATES2 on SBYN_POTENTIALDUPLICATES (EUID2 ASC);
CREATE INDEX SBYN_POTENTIALDUPLICATES3 ON SBYN_POTENTIALDUPLICATES (TRANSACTIONNUMBER ASC);
CREATE INDEX SBYN_AUDIT1 on SBYN_AUDIT (EUID ASC);
CREATE INDEX SBYN_AUDIT2 on SBYN_AUDIT (CREATE_DATE ASC);
CREATE INDEX SBYN_MERGE1 on SBYN_MERGE (KEPT_EUID ASC);

CREATE TABLE SBYN_USACITIZEN (
	SYSTEMCODE VARCHAR2(20),
	LID VARCHAR2(25),
	USACITIZENID VARCHAR2(20),
	FIRSTNAME VARCHAR2(40),
	FIRSTNAME_STD VARCHAR2(40),
	FIRSTNAME_PHON VARCHAR2(8),
	MIDDLENAME VARCHAR2(30),
	LASTNAME VARCHAR2(40),
	LASTNAME_STD VARCHAR2(40),
	LASTNAME_PHON VARCHAR2(8),
	SUFFIX VARCHAR2(10),
	TITLE VARCHAR2(8),
	SSN VARCHAR2(16),
	DOB DATE,
	GENDER VARCHAR2(8),
	MSTATUS VARCHAR2(8),
	RACE VARCHAR2(8),
	POBCITY VARCHAR2(30),
	POBSTATECODE VARCHAR2(30),
	POBCOUNTRY VARCHAR2(20),
	DOD DATE,
	HEIGHT FLOAT,
	HAIRCOLOR VARCHAR2(10),
	EYECOLOR VARCHAR2(10),
	OCCUPATION VARCHAR2(40),
	EMPLOYER VARCHAR2(40),
	EMAIL VARCHAR2(40),
	HASBIRTHCERTIFICATE VARCHAR2(1))
		;

ALTER TABLE SBYN_USACITIZEN ADD CONSTRAINT FK_USACITIZEN_SYSTEMCODE_LID FOREIGN KEY (SYSTEMCODE, LID) REFERENCES SBYN_SYSTEMOBJECT(SYSTEMCODE, LID) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE SBYN_USACITIZEN ADD CONSTRAINT PK_USACITIZEN PRIMARY KEY (USACITIZENID);
ALTER TABLE SBYN_USACITIZEN ADD CONSTRAINT U_USACITIZEN UNIQUE (SYSTEMCODE, LID) DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE SBYN_USACITIZENSBR (
	EUID VARCHAR2(20),
	USACITIZENID VARCHAR2(20),
	FIRSTNAME VARCHAR2(40),
	FIRSTNAME_STD VARCHAR2(40),
	FIRSTNAME_PHON VARCHAR2(8),
	MIDDLENAME VARCHAR2(30),
	LASTNAME VARCHAR2(40),
	LASTNAME_STD VARCHAR2(40),
	LASTNAME_PHON VARCHAR2(8),
	SUFFIX VARCHAR2(10),
	TITLE VARCHAR2(8),
	SSN VARCHAR2(16),
	DOB DATE,
	GENDER VARCHAR2(8),
	MSTATUS VARCHAR2(8),
	RACE VARCHAR2(8),
	POBCITY VARCHAR2(30),
	POBSTATECODE VARCHAR2(30),
	POBCOUNTRY VARCHAR2(20),
	DOD DATE,
	HEIGHT FLOAT,
	HAIRCOLOR VARCHAR2(10),
	EYECOLOR VARCHAR2(10),
	OCCUPATION VARCHAR2(40),
	EMPLOYER VARCHAR2(40),
	EMAIL VARCHAR2(40),
	HASBIRTHCERTIFICATE VARCHAR2(1))
		;
	
ALTER TABLE SBYN_USACITIZENSBR ADD CONSTRAINT FK_USACITIZENSBR_EUID FOREIGN KEY (EUID) REFERENCES SBYN_SYSTEMSBR(EUID) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE SBYN_USACITIZENSBR ADD CONSTRAINT PK_USACITIZENSBR PRIMARY KEY (USACITIZENID);
ALTER TABLE SBYN_USACITIZENSBR ADD CONSTRAINT U_USACITIZENSBR UNIQUE (EUID) DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE SBYN_ALIAS (
	USACITIZENID VARCHAR2(20),
	ALIASID VARCHAR2(20),
	FIRSTNAME VARCHAR2(40),
	MIDDLENAME VARCHAR2(30),
	LASTNAME VARCHAR2(40))
		;

ALTER TABLE SBYN_ALIAS ADD CONSTRAINT FK_ALIAS_USACITIZENID FOREIGN KEY (USACITIZENID) REFERENCES SBYN_USACITIZEN(USACITIZENID) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE SBYN_ALIAS ADD CONSTRAINT PK_ALIAS PRIMARY KEY (ALIASID);
ALTER TABLE SBYN_ALIAS ADD CONSTRAINT U_ALIAS UNIQUE (USACITIZENID, FIRSTNAME, MIDDLENAME, LASTNAME) DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE SBYN_ALIASSBR (
	USACITIZENID VARCHAR2(20),
	ALIASID VARCHAR2(20),
	FIRSTNAME VARCHAR2(40),
	MIDDLENAME VARCHAR2(30),
	LASTNAME VARCHAR2(40))
		;

ALTER TABLE SBYN_ALIASSBR ADD CONSTRAINT FK_ALIASSBR_USACITIZENID FOREIGN KEY (USACITIZENID) REFERENCES SBYN_USACITIZENSBR(USACITIZENID) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE SBYN_ALIASSBR ADD CONSTRAINT PK_ALIASSBR PRIMARY KEY (ALIASID);
ALTER TABLE SBYN_ALIASSBR ADD CONSTRAINT U_ALIASSBR UNIQUE (USACITIZENID, FIRSTNAME, MIDDLENAME, LASTNAME) DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE SBYN_ADDRESS (
	USACITIZENID VARCHAR2(20),
	ADDRESSID VARCHAR2(20),
	ADDRESSTYPE VARCHAR2(8),
	ADDRESSLINE1 VARCHAR2(40),
	ADDRESSLINE1_HOUSENO VARCHAR2(10),
	ADDRESSLINE1_STDIR VARCHAR2(5),
	ADDRESSLINE1_STNAME VARCHAR2(40),
	ADDRESSLINE1_STPHON VARCHAR2(8),
	ADDRESSLINE1_STTYPE VARCHAR2(5),
	ADDRESSLINE2 VARCHAR2(40),
	CITY VARCHAR2(30),
	STATECODE VARCHAR2(10),
	POSTALCODE VARCHAR2(8),
	POSTALCODEEXT VARCHAR2(4),
	COUNTY VARCHAR2(20),
	COUNTRYCODE VARCHAR2(20))
		;

ALTER TABLE SBYN_ADDRESS ADD CONSTRAINT FK_ADDRESS_USACITIZENID FOREIGN KEY (USACITIZENID) REFERENCES SBYN_USACITIZEN(USACITIZENID) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE SBYN_ADDRESS ADD CONSTRAINT PK_ADDRESS PRIMARY KEY (ADDRESSID);
ALTER TABLE SBYN_ADDRESS ADD CONSTRAINT U_ADDRESS UNIQUE (USACITIZENID, ADDRESSTYPE) DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE SBYN_ADDRESSSBR (
	USACITIZENID VARCHAR2(20),
	ADDRESSID VARCHAR2(20),
	ADDRESSTYPE VARCHAR2(8),
	ADDRESSLINE1 VARCHAR2(40),
	ADDRESSLINE1_HOUSENO VARCHAR2(10),
	ADDRESSLINE1_STDIR VARCHAR2(5),
	ADDRESSLINE1_STNAME VARCHAR2(40),
	ADDRESSLINE1_STPHON VARCHAR2(8),
	ADDRESSLINE1_STTYPE VARCHAR2(5),
	ADDRESSLINE2 VARCHAR2(40),
	CITY VARCHAR2(30),
	STATECODE VARCHAR2(10),
	POSTALCODE VARCHAR2(8),
	POSTALCODEEXT VARCHAR2(4),
	COUNTY VARCHAR2(20),
	COUNTRYCODE VARCHAR2(20))
		;

ALTER TABLE SBYN_ADDRESSSBR ADD CONSTRAINT FK_ADDRESSSBR_USACITIZENID FOREIGN KEY (USACITIZENID) REFERENCES SBYN_USACITIZENSBR(USACITIZENID) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE SBYN_ADDRESSSBR ADD CONSTRAINT PK_ADDRESSSBR PRIMARY KEY (ADDRESSID);
ALTER TABLE SBYN_ADDRESSSBR ADD CONSTRAINT U_ADDRESSSBR UNIQUE (USACITIZENID, ADDRESSTYPE) DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE SBYN_PHONE (
	USACITIZENID VARCHAR2(20),
	PHONEID VARCHAR2(20),
	PHONETYPE VARCHAR2(8),
	PHONE VARCHAR2(20),
	PHONEEXT VARCHAR2(6))
		;

ALTER TABLE SBYN_PHONE ADD CONSTRAINT FK_PHONE_USACITIZENID FOREIGN KEY (USACITIZENID) REFERENCES SBYN_USACITIZEN(USACITIZENID) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE SBYN_PHONE ADD CONSTRAINT PK_PHONE PRIMARY KEY (PHONEID);
ALTER TABLE SBYN_PHONE ADD CONSTRAINT U_PHONE UNIQUE (USACITIZENID, PHONETYPE) DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE SBYN_PHONESBR (
	USACITIZENID VARCHAR2(20),
	PHONEID VARCHAR2(20),
	PHONETYPE VARCHAR2(8),
	PHONE VARCHAR2(20),
	PHONEEXT VARCHAR2(6))
		;

ALTER TABLE SBYN_PHONESBR ADD CONSTRAINT FK_PHONESBR_USACITIZENID FOREIGN KEY (USACITIZENID) REFERENCES SBYN_USACITIZENSBR(USACITIZENID) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE SBYN_PHONESBR ADD CONSTRAINT PK_PHONESBR PRIMARY KEY (PHONEID);
ALTER TABLE SBYN_PHONESBR ADD CONSTRAINT U_PHONESBR UNIQUE (USACITIZENID, PHONETYPE) DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE SBYN_CONTACT (
	USACITIZENID VARCHAR2(20),
	CONTACTID VARCHAR2(20),
	CONTACTTYPE VARCHAR2(8),
	CONTACTFIRSTNAME VARCHAR2(40),
	CONTACTLASTNAME VARCHAR2(40),
	CONTACTADDRESSLINE1 VARCHAR2(40),
	CONTACTADDRESSLINE2 VARCHAR2(40),
	CONTACTCITY VARCHAR2(40),
	CONTACTSTATECODE VARCHAR2(10),
	CONTACTPOSTALCODEEXT VARCHAR2(4),
	CONTACTPOSTALCODE VARCHAR2(8),
	CONTACTCOUNTY VARCHAR2(20),
	CONTACTPHONE VARCHAR2(20),
	CONTACTPHONEEXT VARCHAR2(6),
	CONTACTEMAIL VARCHAR2(40))
		;

ALTER TABLE SBYN_CONTACT ADD CONSTRAINT FK_CONTACT_USACITIZENID FOREIGN KEY (USACITIZENID) REFERENCES SBYN_USACITIZEN(USACITIZENID) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE SBYN_CONTACT ADD CONSTRAINT PK_CONTACT PRIMARY KEY (CONTACTID);
ALTER TABLE SBYN_CONTACT ADD CONSTRAINT U_CONTACT UNIQUE (USACITIZENID, CONTACTTYPE) DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE SBYN_CONTACTSBR (
	USACITIZENID VARCHAR2(20),
	CONTACTID VARCHAR2(20),
	CONTACTTYPE VARCHAR2(8),
	CONTACTFIRSTNAME VARCHAR2(40),
	CONTACTLASTNAME VARCHAR2(40),
	CONTACTADDRESSLINE1 VARCHAR2(40),
	CONTACTADDRESSLINE2 VARCHAR2(40),
	CONTACTCITY VARCHAR2(40),
	CONTACTSTATECODE VARCHAR2(10),
	CONTACTPOSTALCODEEXT VARCHAR2(4),
	CONTACTPOSTALCODE VARCHAR2(8),
	CONTACTCOUNTY VARCHAR2(20),
	CONTACTPHONE VARCHAR2(20),
	CONTACTPHONEEXT VARCHAR2(6),
	CONTACTEMAIL VARCHAR2(40))
		;

ALTER TABLE SBYN_CONTACTSBR ADD CONSTRAINT FK_CONTACTSBR_USACITIZENID FOREIGN KEY (USACITIZENID) REFERENCES SBYN_USACITIZENSBR(USACITIZENID) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE SBYN_CONTACTSBR ADD CONSTRAINT PK_CONTACTSBR PRIMARY KEY (CONTACTID);
ALTER TABLE SBYN_CONTACTSBR ADD CONSTRAINT U_CONTACTSBR UNIQUE (USACITIZENID, CONTACTTYPE) DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE SBYN_PASSPORT (
	USACITIZENID VARCHAR2(20),
	PASSPORTID VARCHAR2(20),
	BOOKNUMBER VARCHAR2(40),
	ISSUEDATE DATE,
	CARDNUMBER VARCHAR2(40),
	CARDISSUEDATE DATE)
		;

ALTER TABLE SBYN_PASSPORT ADD CONSTRAINT FK_PASSPORT_USACITIZENID FOREIGN KEY (USACITIZENID) REFERENCES SBYN_USACITIZEN(USACITIZENID) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE SBYN_PASSPORT ADD CONSTRAINT PK_PASSPORT PRIMARY KEY (PASSPORTID);
ALTER TABLE SBYN_PASSPORT ADD CONSTRAINT U_PASSPORT UNIQUE (USACITIZENID, PASSPORTID) DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE SBYN_PASSPORTSBR (
	USACITIZENID VARCHAR2(20),
	PASSPORTID VARCHAR2(20),
	BOOKNUMBER VARCHAR2(40),
	ISSUEDATE DATE,
	CARDNUMBER VARCHAR2(40),
	CARDISSUEDATE DATE)
		;

ALTER TABLE SBYN_PASSPORTSBR ADD CONSTRAINT FK_PASSPORTSBR_USACITIZENID FOREIGN KEY (USACITIZENID) REFERENCES SBYN_USACITIZENSBR(USACITIZENID) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE SBYN_PASSPORTSBR ADD CONSTRAINT PK_PASSPORTSBR PRIMARY KEY (PASSPORTID);
ALTER TABLE SBYN_PASSPORTSBR ADD CONSTRAINT U_PASSPORTSBR UNIQUE (USACITIZENID, PASSPORTID) DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE SBYN_SPOUSE (
	USACITIZENID VARCHAR2(20),
	SPOUSEID VARCHAR2(20),
	WASMARRIED VARCHAR2(1),
	FULLNAME VARCHAR2(40),
	SPOUSEDOB DATE,
	SPOUSEPOBCITY VARCHAR2(30),
	SPOUSEPOBSTATECODE VARCHAR2(30),
	SPOUSEPOBCOUNTRY VARCHAR2(20),
	SPOUSEUSCITIZEN VARCHAR2(1),
	SPOUSEWIDOWED VARCHAR2(1),
	SPOUSELASTMARRIAGE DATE,
	SPOUSEDOD DATE,
	SPOUSEDIVORCED VARCHAR2(1))
		;

ALTER TABLE SBYN_SPOUSE ADD CONSTRAINT FK_SPOUSE_USACITIZENID FOREIGN KEY (USACITIZENID) REFERENCES SBYN_USACITIZEN(USACITIZENID) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE SBYN_SPOUSE ADD CONSTRAINT PK_SPOUSE PRIMARY KEY (SPOUSEID);
ALTER TABLE SBYN_SPOUSE ADD CONSTRAINT U_SPOUSE UNIQUE (USACITIZENID, SPOUSEID) DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE SBYN_SPOUSESBR (
	USACITIZENID VARCHAR2(20),
	SPOUSEID VARCHAR2(20),
	WASMARRIED VARCHAR2(1),
	FULLNAME VARCHAR2(40),
	SPOUSEDOB DATE,
	SPOUSEPOBCITY VARCHAR2(30),
	SPOUSEPOBSTATECODE VARCHAR2(30),
	SPOUSEPOBCOUNTRY VARCHAR2(20),
	SPOUSEUSCITIZEN VARCHAR2(1),
	SPOUSEWIDOWED VARCHAR2(1),
	SPOUSELASTMARRIAGE DATE,
	SPOUSEDOD DATE,
	SPOUSEDIVORCED VARCHAR2(1))
		;

ALTER TABLE SBYN_SPOUSESBR ADD CONSTRAINT FK_SPOUSESBR_USACITIZENID FOREIGN KEY (USACITIZENID) REFERENCES SBYN_USACITIZENSBR(USACITIZENID) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE SBYN_SPOUSESBR ADD CONSTRAINT PK_SPOUSESBR PRIMARY KEY (SPOUSEID);
ALTER TABLE SBYN_SPOUSESBR ADD CONSTRAINT U_SPOUSESBR UNIQUE (USACITIZENID, SPOUSEID) DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE SBYN_ID (
	USACITIZENID VARCHAR2(20),
	IDID VARCHAR2(20),
	IDTYPE VARCHAR2(10),
	IDENTIFICATION VARCHAR2(56),
	IDSTATECODE VARCHAR2(30))
		;

ALTER TABLE SBYN_ID ADD CONSTRAINT FK_ID_USACITIZENID FOREIGN KEY (USACITIZENID) REFERENCES SBYN_USACITIZEN(USACITIZENID) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE SBYN_ID ADD CONSTRAINT PK_ID PRIMARY KEY (IDID);
ALTER TABLE SBYN_ID ADD CONSTRAINT U_ID UNIQUE (USACITIZENID, IDTYPE) DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE SBYN_IDSBR (
	USACITIZENID VARCHAR2(20),
	IDID VARCHAR2(20),
	IDTYPE VARCHAR2(10),
	IDENTIFICATION VARCHAR2(56),
	IDSTATECODE VARCHAR2(30))
		;

ALTER TABLE SBYN_IDSBR ADD CONSTRAINT FK_IDSBR_USACITIZENID FOREIGN KEY (USACITIZENID) REFERENCES SBYN_USACITIZENSBR(USACITIZENID) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE SBYN_IDSBR ADD CONSTRAINT PK_IDSBR PRIMARY KEY (IDID);
ALTER TABLE SBYN_IDSBR ADD CONSTRAINT U_IDSBR UNIQUE (USACITIZENID, IDTYPE) DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE SBYN_MEMBER (
	USACITIZENID VARCHAR2(20),
	MEMBERID VARCHAR2(20),
	MEMBERTYPE VARCHAR2(8),
	MEMBERFIRSTNAME VARCHAR2(40),
	MEMBERLASTNAME VARCHAR2(40),
	MEMBERMIDDLENAME VARCHAR2(30),
	MEMBERDOB DATE,
	MEMBERPOBCITY VARCHAR2(30),
	MEMBERPOBSTATECODE VARCHAR2(30),
	MEMBERPOBCOUNTRY VARCHAR2(20),
	MEMBERUSCITIZEN VARCHAR2(1))
		;

ALTER TABLE SBYN_MEMBER ADD CONSTRAINT FK_MEMBER_USACITIZENID FOREIGN KEY (USACITIZENID) REFERENCES SBYN_USACITIZEN(USACITIZENID) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE SBYN_MEMBER ADD CONSTRAINT PK_MEMBER PRIMARY KEY (MEMBERID);
ALTER TABLE SBYN_MEMBER ADD CONSTRAINT U_MEMBER UNIQUE (USACITIZENID, MEMBERTYPE) DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE SBYN_MEMBERSBR (
	USACITIZENID VARCHAR2(20),
	MEMBERID VARCHAR2(20),
	MEMBERTYPE VARCHAR2(8),
	MEMBERFIRSTNAME VARCHAR2(40),
	MEMBERLASTNAME VARCHAR2(40),
	MEMBERMIDDLENAME VARCHAR2(30),
	MEMBERDOB DATE,
	MEMBERPOBCITY VARCHAR2(30),
	MEMBERPOBSTATECODE VARCHAR2(30),
	MEMBERPOBCOUNTRY VARCHAR2(20),
	MEMBERUSCITIZEN VARCHAR2(1))
		;

ALTER TABLE SBYN_MEMBERSBR ADD CONSTRAINT FK_MEMBERSBR_USACITIZENID FOREIGN KEY (USACITIZENID) REFERENCES SBYN_USACITIZENSBR(USACITIZENID) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE SBYN_MEMBERSBR ADD CONSTRAINT PK_MEMBERSBR PRIMARY KEY (MEMBERID);
ALTER TABLE SBYN_MEMBERSBR ADD CONSTRAINT U_MEMBERSBR UNIQUE (USACITIZENID, MEMBERTYPE) DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE SBYN_SEQ_TABLE (
	SEQ_NAME VARCHAR2(20),
	SEQ_COUNT NUMBER(38));

ALTER TABLE SBYN_SEQ_TABLE ADD CONSTRAINT U_SEQ_NAME UNIQUE (SEQ_NAME);

CREATE OR REPLACE FUNCTION SEQMGR (Seq_Name_In IN VARCHAR2, Chunk_Size_In IN INTEGER) RETURN INTEGER
IS
PRAGMA AUTONOMOUS_TRANSACTION;

   Count_out INTEGER := 0;
BEGIN
   Count_out := 0;

   UPDATE SBYN_SEQ_TABLE SET seq_count = seq_count+Chunk_Size_In WHERE seq_name = Seq_Name_In;
   SELECT seq_count-Chunk_Size_In  INTO Count_out FROM SBYN_SEQ_TABLE WHERE seq_name = Seq_Name_In;
   COMMIT;

   RETURN Count_out;
EXCEPTION
    WHEN OTHERS THEN
        RETURN 0;
END SEQMGR;
/

INSERT INTO SBYN_SEQ_TABLE VALUES ('EUID', 0);
INSERT INTO SBYN_SEQ_TABLE VALUES ('POTENTIALDUPLICATE', 0);
INSERT INTO SBYN_SEQ_TABLE VALUES ('TRANSACTIONNUMBER', 0);
INSERT INTO SBYN_SEQ_TABLE VALUES ('ASSUMEDMATCH', 0);
INSERT INTO SBYN_SEQ_TABLE VALUES ('AUDIT', 0);
INSERT INTO SBYN_SEQ_TABLE VALUES ('MERGE', 0);
INSERT INTO SBYN_SEQ_TABLE VALUES ('SBYN_APPL', 2);
INSERT INTO SBYN_SEQ_TABLE VALUES ('SBYN_COMMON_HEADER', 1);
INSERT INTO SBYN_SEQ_TABLE VALUES ('SBYN_COMMON_DETAIL', 1);
INSERT INTO SBYN_SEQ_TABLE VALUES ('ALIAS', 0);
INSERT INTO SBYN_SEQ_TABLE VALUES ('ALIASSBR', 0);
INSERT INTO SBYN_SEQ_TABLE VALUES ('ADDRESS', 0);
INSERT INTO SBYN_SEQ_TABLE VALUES ('ADDRESSSBR', 0);
INSERT INTO SBYN_SEQ_TABLE VALUES ('PHONE', 0);
INSERT INTO SBYN_SEQ_TABLE VALUES ('PHONESBR', 0);
INSERT INTO SBYN_SEQ_TABLE VALUES ('CONTACT', 0);
INSERT INTO SBYN_SEQ_TABLE VALUES ('CONTACTSBR', 0);
INSERT INTO SBYN_SEQ_TABLE VALUES ('PASSPORT', 0);
INSERT INTO SBYN_SEQ_TABLE VALUES ('PASSPORTSBR', 0);
INSERT INTO SBYN_SEQ_TABLE VALUES ('SPOUSE', 0);
INSERT INTO SBYN_SEQ_TABLE VALUES ('SPOUSESBR', 0);
INSERT INTO SBYN_SEQ_TABLE VALUES ('ID', 0);
INSERT INTO SBYN_SEQ_TABLE VALUES ('IDSBR', 0);
INSERT INTO SBYN_SEQ_TABLE VALUES ('MEMBER', 0);
INSERT INTO SBYN_SEQ_TABLE VALUES ('MEMBERSBR', 0);
INSERT INTO SBYN_SEQ_TABLE VALUES ('USACITIZEN', 0);
INSERT INTO SBYN_SEQ_TABLE VALUES ('USACITIZENSBR', 0);

INSERT INTO SBYN_APPL (APPL_ID, CODE, DESCR, READ_ONLY, CREATE_DATE, CREATE_USERID) 
VALUES (1, 'EV', 'eView5.1', 'Y', sysdate, user);

COMMIT;
