/*
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 *
 * Copyright 2003-2007 Sun Microsystems, Inc. All Rights Reserved.
 *
 * The contents of this file are subject to the terms of the Common 
 * Development and Distribution License ("CDDL")(the "License"). You 
 * may not use this file except in compliance with the License.
 *
 * You can obtain a copy of the License at
 * https://open-dm-mi.dev.java.net/cddl.html
 * or open-dm-mi/bootstrap/legal/license.txt. See the License for the 
 * specific language governing permissions and limitations under the  
 * License.  
 *
 * When distributing the Covered Code, include this CDDL Header Notice 
 * in each file and include the License file at
 * open-dm-mi/bootstrap/legal/license.txt.
 * If applicable, add the following below this CDDL Header, with the 
 * fields enclosed by brackets [] replaced by your own identifying 
 * information: "Portions Copyrighted [year] [name of copyright owner]"
 */
package com.sun.mdm.index.project.ui.applicationeditor.standardization;

import java.util.ArrayList;

import com.sun.mdm.index.parser.MatchFieldDef.Encoder;
import com.sun.mdm.index.project.ui.applicationeditor.EntityTree;
import com.sun.mdm.index.project.ui.applicationeditor.EntityTreeSelectionDialog;

public class PhoneticizeFieldEditDialog extends javax.swing.JDialog {
    EntityTree mEntityTree;
    boolean bModified = false;
    
    /** Creates new form PhoneticizeFieldEditDialog */
    public PhoneticizeFieldEditDialog(EntityTree entityTree, ArrayList alEncoders, String unphoneticizedSource, String phoneticizedField, String encodingType) {
        super(org.openide.windows.WindowManager.getDefault().getMainWindow(), true);
        mEntityTree = entityTree;
        initComponents();
        jComboBoxEncodingTypes.removeAllItems();
        for (int i=0; i < alEncoders.size(); i++) {
            Encoder encoder = (Encoder) alEncoders.get(i);
            jComboBoxEncodingTypes.addItem(encoder.getEncodingType());
        }
        
        jComboBoxEncodingTypes.addItemListener(new java.awt.event.ItemListener() {
                public void itemStateChanged(java.awt.event.ItemEvent e) {
                    enableOK();
                }
            });     
            
        this.jTextFieldUnphoneticizedSource.setText(unphoneticizedSource);
        this.jTextFieldPhoneticizedField.setText(phoneticizedField);
        this.jComboBoxEncodingTypes.setSelectedItem(encodingType);   
        
        this.jTextFieldUnphoneticizedSource.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyReleased(java.awt.event.KeyEvent evt) {
                    enableOK();
                }
        });       
        this.jTextFieldPhoneticizedField.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyReleased(java.awt.event.KeyEvent evt) {
                    enableOK();
                }
        });        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelField = new javax.swing.JLabel();
        jLabelSource = new javax.swing.JLabel();
        jTextFieldPhoneticizedField = new javax.swing.JTextField();
        jTextFieldUnphoneticizedSource = new javax.swing.JTextField();
        jLabelEncodingTypes = new javax.swing.JLabel();
        jComboBoxEncodingTypes = new javax.swing.JComboBox();
        jButtonSelectField = new javax.swing.JButton();
        jButtonSelectSource = new javax.swing.JButton();
        jButtonOk = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/sun/mdm/index/project/ui/applicationeditor/standardization/Bundle"); // NOI18N
        setTitle(bundle.getString("LBL_Title_PhoneticizeFieldEdit")); // NOI18N
        java.util.ResourceBundle bundle1 = java.util.ResourceBundle.getBundle("com/sun/mdm/index/project/ui/applicationeditor/blocking/Bundle"); // NOI18N
        setName(bundle1.getString("LBL_Title_BlockBy")); // NOI18N

        jLabelField.setText(bundle.getString("LBL_Phoneticized_Field")); // NOI18N

        jLabelSource.setText(bundle.getString("LBL_Unphoneticized_Source")); // NOI18N

        jTextFieldPhoneticizedField.setEditable(false);

        jTextFieldUnphoneticizedSource.setEditable(false);

        jLabelEncodingTypes.setText(bundle.getString("LBL_Encoding_Type")); // NOI18N

        jButtonSelectField.setText(bundle.getString("LBL_Browse")); // NOI18N
        jButtonSelectField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectPhoneticizedFieldActionPerformed(evt);
            }
        });

        jButtonSelectSource.setText(bundle.getString("LBL_Browse")); // NOI18N
        jButtonSelectSource.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectUnphoneticizedSourceActionPerformed(evt);
            }
        });

        jButtonOk.setText(bundle.getString("LBL_OK")); // NOI18N
        jButtonOk.setEnabled(false);
        jButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        jButtonCancel.setText(bundle.getString("LBL_Cancel")); // NOI18N
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(10, 10, 10)
                .add(jLabelSource, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 140, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(jTextFieldUnphoneticizedSource, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 320, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(11, 11, 11)
                .add(jButtonSelectSource, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 80, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
            .add(layout.createSequentialGroup()
                .add(10, 10, 10)
                .add(jLabelField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 140, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(jTextFieldPhoneticizedField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 320, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(11, 11, 11)
                .add(jButtonSelectField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 80, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
            .add(layout.createSequentialGroup()
                .add(10, 10, 10)
                .add(jLabelEncodingTypes, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 140, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(jComboBoxEncodingTypes, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 90, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
            .add(layout.createSequentialGroup()
                .add(400, 400, 400)
                .add(jButtonOk, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 80, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(jButtonCancel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 80, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(10, 10, 10)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabelSource, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTextFieldUnphoneticizedSource, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButtonSelectSource, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(10, 10, 10)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabelField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTextFieldPhoneticizedField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButtonSelectField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(10, 10, 10)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabelEncodingTypes, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jComboBoxEncodingTypes, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(8, 8, 8)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jButtonOk)
                    .add(jButtonCancel)))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-579)/2, (screenSize.height-158)/2, 579, 158);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        bModified = false;
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        bModified = true;
        this.dispose();
    }//GEN-LAST:event_btnOkActionPerformed

    private void selectPhoneticizedFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectPhoneticizedFieldActionPerformed
        String field = this.jTextFieldPhoneticizedField.getText();
        mEntityTree.clearSelection();
        EntityTreeSelectionDialog entityTreeSelectionDialog = new EntityTreeSelectionDialog(mEntityTree, field, true);                                        
        entityTreeSelectionDialog.setVisible(true);
        if (entityTreeSelectionDialog.isSelected()) {
            this.jTextFieldPhoneticizedField.setText(entityTreeSelectionDialog.getTargetFieldName());        
            enableOK();            
        }
    }//GEN-LAST:event_selectPhoneticizedFieldActionPerformed

    private void selectUnphoneticizedSourceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectUnphoneticizedSourceActionPerformed
        String source = this.jTextFieldUnphoneticizedSource.getText();
        mEntityTree.clearSelection();        
        EntityTreeSelectionDialog entityTreeSelectionDialog = new EntityTreeSelectionDialog(mEntityTree, source, true);                                        
        entityTreeSelectionDialog.setVisible(true);
        if (entityTreeSelectionDialog.isSelected()) {        
            this.jTextFieldUnphoneticizedSource.setText(entityTreeSelectionDialog.getTargetFieldName());                
            enableOK();            
        }
    }//GEN-LAST:event_selectUnphoneticizedSourceActionPerformed
    
    private void enableOK() {
        boolean enabled = this.jTextFieldPhoneticizedField.getText() != null && 
                          !this.jTextFieldPhoneticizedField.getText().equals("") &&
                          this.jTextFieldUnphoneticizedSource.getText() != null && 
                          !this.jTextFieldUnphoneticizedSource.getText().equals("") &&    
                          jComboBoxEncodingTypes.getSelectedItem()!= null;

        this.jButtonOk.setEnabled(enabled);
    }
    
    public String getPhoneticizedField() {
        return this.jTextFieldPhoneticizedField.getText();
    }
    
    public String getUnphoneticizedSource() {
        return this.jTextFieldUnphoneticizedSource.getText();
    }
    
    public String getEncodingType() {
        return (String) this.jComboBoxEncodingTypes.getSelectedItem();
    }
    
    public boolean isModified() {
        return bModified;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PhoneticizeFieldEditDialog(null, null, "field", "encoding", "source");
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonOk;
    private javax.swing.JButton jButtonSelectField;
    private javax.swing.JButton jButtonSelectSource;
    private javax.swing.JComboBox jComboBoxEncodingTypes;
    private javax.swing.JLabel jLabelEncodingTypes;
    private javax.swing.JLabel jLabelField;
    private javax.swing.JLabel jLabelSource;
    private javax.swing.JTextField jTextFieldPhoneticizedField;
    private javax.swing.JTextField jTextFieldUnphoneticizedSource;
    // End of variables declaration//GEN-END:variables
    
}
