/*
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 *
 * Copyright 2003-2007 Sun Microsystems, Inc. All Rights Reserved.
 *
 * The contents of this file are subject to the terms of the Common 
 * Development and Distribution License ("CDDL")(the "License"). You 
 * may not use this file except in compliance with the License.
 *
 * You can obtain a copy of the License at
 * https://open-dm-mi.dev.java.net/cddl.html
 * or open-dm-mi/bootstrap/legal/license.txt. See the License for the 
 * specific language governing permissions and limitations under the  
 * License.  
 *
 * When distributing the Covered Code, include this CDDL Header Notice 
 * in each file and include the License file at
 * open-dm-mi/bootstrap/legal/license.txt.
 * If applicable, add the following below this CDDL Header, with the 
 * fields enclosed by brackets [] replaced by your own identifying 
 * information: "Portions Copyrighted [year] [name of copyright owner]"
 */

package com.sun.mdm.index.project.ui.applicationeditor;

import org.openide.util.NbBundle;

import com.sun.mdm.index.parser.MasterType;

/**
 *
 * @author  kkao
 */
public class TabDeploymentPanel extends javax.swing.JPanel {
    private EviewEditorMainApp mEviewEditorMainApp;
    private MasterType mMasterType;
    private final String TRANSACTION_CONTAINER = NbBundle.getMessage(TabDeploymentPanel.class, "LBL_Transaction_Container");
    private final String TRANSACTION_BEAN = NbBundle.getMessage(TabDeploymentPanel.class, "LBL_Transaction_Bean");
    private final String TRANSACTION_LOCAL = NbBundle.getMessage(TabDeploymentPanel.class, "LBL_Transaction_Local");
    
    /** Creates new form TabDeploymentPanel */
    public TabDeploymentPanel(EviewEditorMainApp eviewEditorMainApp, MasterType masterType) {
        initComponents();
        mEviewEditorMainApp = eviewEditorMainApp;
        mMasterType = masterType;
        jComboBoxTransactions.insertItemAt(TRANSACTION_CONTAINER, 0);
        jComboBoxTransactions.insertItemAt(TRANSACTION_BEAN, 1);
        jComboBoxTransactions.insertItemAt(TRANSACTION_LOCAL, 2);

        String transaction = mMasterType.getTransaction();
        int index = 0;  // default is "CONTAINER"
        if (transaction != null) {
            if (transaction.equals("BEAN")) { // NOI18N
                index = 1;
            } else if (transaction.equals("LOCAL")) { // NOI18N
                index = 2;
            }
        } 
        jComboBoxTransactions.setSelectedIndex(index);
        jComboBoxTransactions.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                mMasterType.setTransaction(getTransaction());
                mMasterType.setModified(true);
                mEviewEditorMainApp.enableSaveAction(true);
            }
        });
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTransaction = new javax.swing.JLabel();
        jComboBoxTransactions = new javax.swing.JComboBox();

        setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        lblTransaction.setText(org.openide.util.NbBundle.getMessage(TabDeploymentPanel.class, "TabDeploymentPanel.lblTransaction")); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(lblTransaction, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 99, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jComboBoxTransactions, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 226, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jComboBoxTransactions, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(lblTransaction))
                .addContainerGap(263, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBoxTransactions;
    private javax.swing.JLabel lblTransaction;
    // End of variables declaration//GEN-END:variables
    
    public String getTransaction() {
        int i = jComboBoxTransactions.getSelectedIndex();
        String transaction = "CONTAINER"; // NOI18N
        if (i == 1) {
            transaction = "BEAN"; // NOI18N
        } else if (i == 2) {
            transaction = "LOCAL"; // NOI18N
        }
        return transaction;
    }
}
