/*
 * This source file was generated by FireStorm/DAO.
 *
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 *
 * For more information please visit http://www.codefutures.com/products/firestorm
 */
package com.sun.mdm.multidomain.hierarchy.ops.impl;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;

import com.sun.mdm.multidomain.hierarchy.ops.dao.AbstractDAO;
import com.sun.mdm.multidomain.hierarchy.ops.dao.HierarchyNodeDao;
import com.sun.mdm.multidomain.hierarchy.ops.dto.HierarchyDefDto;
import com.sun.mdm.multidomain.hierarchy.ops.dto.HierarchyNodeDto;
import com.sun.mdm.multidomain.hierarchy.ops.dto.HierarchyNodeEaDto;
import com.sun.mdm.multidomain.hierarchy.ops.exceptions.*;
import com.sun.mdm.multidomain.sql.InsertBuilder;
import com.sun.mdm.multidomain.sql.SQLBuilder;
import com.sun.mdm.multidomain.sql.SelectBuilder;

import java.util.List;
import static com.sun.mdm.multidomain.sql.DBSchema.*;

public class HierarchyNodeDaoImpl extends AbstractDAO implements HierarchyNodeDao {

    /**
     * The factory class for this DAO has two versions of the create() method - one that
    takes no arguments and one that takes a Connection argument. If the Connection version
    is chosen then the connection will be stored in this attribute and will be used by all
    calls to this DAO, otherwise a new Connection will be allocated for each operation.
     */
    protected java.sql.Connection userConn;
    /**
     * Finder methods will pass this value to the JDBC setMaxRows method
     */
    protected int maxRows;
    private long mPrimaryKey = 0;

    /**
     * Inserts a new row in the HierarchyDto table.
     */
    public long insert(HierarchyNodeDto dto) throws HierarchyDaoException {
        long t1 = System.currentTimeMillis();
        // declare variables
        final boolean isConnSupplied = (userConn != null);
        Connection conn = null;
        PreparedStatement stmt = null;
        ResultSet rs = null;

        try {
            // get the user-specified connection or get a connection from the ResourceManager
            conn = isConnSupplied ? userConn : ResourceManager.getConnection();
            InsertBuilder builder = new InsertBuilder();
            builder.setTable(HIERARCHY_NODE.getTableName());
            for (HIERARCHY_NODE hier : HIERARCHY_NODE.values()) {
                builder.addColumns(hier.columnName);
            }
            String sqlStr = SQLBuilder.buildSQL(builder);
            stmt = conn.prepareStatement(sqlStr);
            int index = 1;
            stmt.setLong(index++, 0);
            stmt.setLong(index++, dto.getHierarchyDefId());
            stmt.setString(index++, dto.getEuid());
            stmt.setString(index++, dto.getParentEuid());
            stmt.setTimestamp(index++, (java.sql.Timestamp) dto.getEffectiveFromDate());
            stmt.setTimestamp(index++, (java.sql.Timestamp) dto.getEffectiveToDate());
            System.out.println("Executing " + sqlStr + " with DTO: " + dto);
            int rows = stmt.executeUpdate();
            //reset(dto);
            rs = stmt.getGeneratedKeys();
            if (rs != null && rs.next()) {
                mPrimaryKey = rs.getLong(1);
            }
            return mPrimaryKey;
        } catch (Exception _e) {
            _e.printStackTrace();
            throw new HierarchyDaoException("Exception: " + _e.getMessage(), _e);
        } finally {
            ResourceManager.close(stmt);
            if (!isConnSupplied) {
                ResourceManager.close(conn);
            }

        }

    }

    public long getPrimaryKey() {
        return mPrimaryKey;
    }

    /**
     * Updates a single row in the HierarchyDto table.
     */
    public void update(long pk, HierarchyNodeDto dto) throws HierarchyDaoException {
        long t1 = System.currentTimeMillis();
        // declare variables
        final boolean isConnSupplied = (userConn != null);
        Connection conn = null;
        PreparedStatement stmt = null;

        try {
            // get the user-specified connection or get a connection from the ResourceManager
            conn = isConnSupplied ? userConn : ResourceManager.getConnection();

            //System.out.println("Executing " + SQL_UPDATE + " with DTO: " + dto);
            // stmt = conn.prepareStatement(SQL_UPDATE);
            int index = 1;
            stmt.setLong(index++, dto.getHierarchyNodeId());
            //stmt.setString(index++, dto.getSourceEuid());
          //  stmt.setString(index++, dto.getTargetEuid());
            stmt.setTimestamp(index++, (java.sql.Timestamp) dto.getEffectiveFromDate());
            stmt.setTimestamp(index++, (java.sql.Timestamp) dto.getEffectiveToDate());
           // stmt.setTimestamp(index++, (java.sql.Timestamp) dto.getPurgeDate());
            stmt.setLong(14, pk);
            int rows = stmt.executeUpdate();
            //reset(dto);
            long t2 = System.currentTimeMillis();
            System.out.println(rows + " rows affected (" + (t2 - t1) + " ms)");
        } catch (Exception _e) {
            _e.printStackTrace();
            throw new HierarchyDaoException("Exception: " + _e.getMessage(), _e);
        } finally {
            ResourceManager.close(stmt);
            if (!isConnSupplied) {
                ResourceManager.close(conn);
            }

        }

    }

    /**
     * Deletes a single row in the HierarchyDto table.
     */
    public void delete(long pk) throws HierarchyDaoException {
        long t1 = System.currentTimeMillis();
        // declare variables
        final boolean isConnSupplied = (userConn != null);
        Connection conn = null;
        PreparedStatement stmt = null;

        try {
            // get the user-specified connection or get a connection from the ResourceManager
            conn = isConnSupplied ? userConn : ResourceManager.getConnection();

            //System.out.println("Executing " + SQL_DELETE + " with PK: " + pk);
            // stmt = conn.prepareStatement(SQL_DELETE);
            stmt.setLong(1, pk);
            int rows = stmt.executeUpdate();
            long t2 = System.currentTimeMillis();
            System.out.println(rows + " rows affected (" + (t2 - t1) + " ms)");
        } catch (Exception _e) {
            _e.printStackTrace();
            throw new HierarchyDaoException("Exception: " + _e.getMessage(), _e);
        } finally {
            ResourceManager.close(stmt);
            if (!isConnSupplied) {
                ResourceManager.close(conn);
            }

        }

    }

    /**
     * Returns all rows from the HierarchyDto table that match the criteria
     *
     */
    public List<HierarchyNodeDto> search(String euid) throws HierarchyDaoException {
        // declare variables
        final boolean isConnSupplied = (userConn != null);
        Connection conn = null;
        PreparedStatement stmt = null;
        ResultSet rs = null;

        try {
            // get the user-specified connection or get a connection from the ResourceManager
            conn = isConnSupplied ? userConn : ResourceManager.getConnection();

            // construct the SQL statement

            HierarchyDefDto attrDefList = getAttributeDefs(conn, euid);
            String sqlStr = BuildSelectSQL(attrDefList);
            System.out.println("Executing " + sqlStr);
            // prepare statement
            stmt = conn.prepareStatement(sqlStr);

            stmt.setLong(1, getPrimaryKey());
            //stmt.setMaxRows(maxRows);

            rs = stmt.executeQuery();

            // fetch the results
            return fetchMultiResults(rs);
        } catch (Exception _e) {
            throw new HierarchyDaoException("Exception: " + _e.getMessage(), _e);
        } finally {
            ResourceManager.close(rs);
            ResourceManager.close(stmt);
            if (!isConnSupplied) {
                ResourceManager.close(conn);
            }

        }
    }

    private HierarchyDefDto getAttributeDefs(Connection conn, String euid) throws SQLException {
        SelectBuilder selectBld = new SelectBuilder();
        String relEATable = HIERARCHY_NODE_EA.getTableName();
        String relTable = HIERARCHY_NODE.getTableName();
        String relDefTable = HIERARCHY_DEF.getTableName();
        selectBld.setTable(relDefTable, relTable, relEATable);
        selectBld.addColumns(HIERARCHY_NODE.HIERARCHY_NODE_ID.prefixedColumnName);
        for (HIERARCHY_DEF hierDef : HIERARCHY_DEF.values()) {
            selectBld.addColumns(hierDef.prefixedColumnName);
        }
        for (HIERARCHY_NODE_EA hierEA : HIERARCHY_NODE_EA.values()) {
            selectBld.addColumns(hierEA.prefixedColumnName);
        }
        selectBld.addCriteria(HIERARCHY_DEF.HIERARCHY_DEF_ID.prefixedColumnName, HIERARCHY_NODE.HIERARCHY_DEF_ID.prefixedColumnName);
        selectBld.addCriteria(HIERARCHY_DEF.HIERARCHY_DEF_ID.prefixedColumnName, RELATIONSHIP_EA.RELATIONSHIP_DEF_ID.prefixedColumnName);
        selectBld.addCriteria(HIERARCHY_NODE.EUID.prefixedColumnName, null);
        String sqlStr = SQLBuilder.buildSQL(selectBld);
        PreparedStatement stmt = conn.prepareStatement(sqlStr);
        int index = 1;
        stmt.setString(index++, euid);
        ResultSet rs = stmt.executeQuery();
        HierarchyDefDto relDefDto = new HierarchyDefDto();
        /*
        while (rs.next()) {
            if (rs.isFirst()) {
                if (mPrimaryKey == 0) {
                    mPrimaryKey = rs.getLong(RELATIONSHIP.RELATIONSHIP_ID.columnName);
                }
                relDefDto.setHierarchyDefId(rs.getLong(RELATIONSHIP_DEF.RELATIONSHIP_DEF_ID.columnName));
                relDefDto.setHierarchyName(rs.getString(RELATIONSHIP_DEF.RELATIONSHIP_NAME.columnName));
                relDefDto.setDescription(rs.getString(RELATIONSHIP_DEF.DESCRIPTION.columnName));
                relDefDto.setSourceDomain(rs.getString(RELATIONSHIP_DEF.SOURCE_DOMAIN.columnName));
                relDefDto.setTargetDomain(rs.getString(RELATIONSHIP_DEF.TARGET_DOMAIN.columnName));
                relDefDto.setBidirectional(rs.getString(RELATIONSHIP_DEF.BIDIRECTIONAL.columnName));
                relDefDto.setEffectiveFromReq(rs.getString(RELATIONSHIP_DEF.EFFECTIVE_FROM_REQ.columnName));
                relDefDto.setEffectiveToReq(rs.getString(RELATIONSHIP_DEF.EFFECTIVE_TO_REQ.columnName));
                relDefDto.setPurgeDateReq(rs.getString(RELATIONSHIP_DEF.PURGE_DATE_REQ.columnName));
                relDefDto.setPlugIn(rs.getString(RELATIONSHIP_DEF.PLUGIN.columnName));
            }
            HierarchyEaDto relEa = new HierarchyEaDto();
            relEa.setEaId(rs.getLong(RELATIONSHIP_EA.EA_ID.columnName));
            relEa.setHierarchyDefId(rs.getLong(RELATIONSHIP_EA.RELATIONSHIP_DEF_ID.columnName));
            relEa.setAttributeName(rs.getString(RELATIONSHIP_EA.ATTRIBUTE_NAME.columnName));
            relEa.setColumnName(rs.getString(RELATIONSHIP_EA.COLUMN_NAME.columnName));
            relEa.setColumnType(rs.getString(RELATIONSHIP_EA.COLUMN_TYPE.columnName));
            relEa.setDefaultValue(rs.getString(RELATIONSHIP_EA.DEFAULT_VALUE.columnName));
            relEa.setIsSearchable(rs.getString(RELATIONSHIP_EA.IS_SEARCHABLE.columnName).equalsIgnoreCase("Y") ? true : false);
            relEa.setIsRequired(rs.getString(RELATIONSHIP_EA.IS_REQUIRED.columnName).equalsIgnoreCase("Y") ? true : false);
            relEa.setIsIncluded(rs.getString(RELATIONSHIP_EA.IS_INCLUDED.columnName).equalsIgnoreCase("Y") ? true : false);
            relDefDto.getAttributeDefs().add(relEa);
        }
         * */
        return relDefDto;
    }

    private String BuildSelectSQL(HierarchyDefDto relDef) {
        SelectBuilder builder = new SelectBuilder();
        builder.setTable(RELATIONSHIP.getTableName(), RELATIONSHIP_EAV.getTableName());

        for (RELATIONSHIP rel : RELATIONSHIP.values()) {
            builder.addColumns(rel.prefixedColumnName);
        }
        for (RELATIONSHIP_EAV ea : RELATIONSHIP_EAV.values()) {
            builder.addColumns(ea.prefixedColumnName);
        }
        for (HierarchyNodeEaDto eaDto : relDef.getAttributeDefs()) {
            builder.addColumns(eaDto.getColumnName());
        }
        builder.addCriteria(RELATIONSHIP.RELATIONSHIP_ID.prefixedColumnName, null);
        builder.addCriteria(RELATIONSHIP.RELATIONSHIP_ID.prefixedColumnName, RELATIONSHIP_EAV.RELATIONSHIP_ID.prefixedColumnName);
        String sqlStr = SQLBuilder.buildSQL(builder);
        return sqlStr;
    }

    /**
     * Method 'HierarchyNodeDaoImpl'
     *
     */
    public HierarchyNodeDaoImpl() {
    }

    /**
     * Method 'HierarchyNodeDaoImpl'
     *
     * @param userConn
     */
    public HierarchyNodeDaoImpl(final java.sql.Connection userConn) {
        this.userConn = userConn;
    }

    /**
     * Sets the value of maxRows
     */
    public void setMaxRows(int maxRows) {
        this.maxRows = maxRows;
    }

    /**
     * Gets the value of maxRows
     */
    public int getMaxRows() {
        return maxRows;
    }

    /**
     * Fetches multiple rows from the result set
     */
    protected List<HierarchyNodeDto> fetchMultiResults(ResultSet rs) throws SQLException {
         ArrayList<HierarchyNodeDto> resultList = new ArrayList<HierarchyNodeDto>();
          /*
           while (rs.next()) {
            HierarchyDto dto = new HierarchyDto();
            populateDto(rs, dto, relDef.getAttributeDefs());
            resultList.add(dto);
        }
*/
        HierarchyNodeDto ret[] = new HierarchyNodeDto[resultList.size()];

        resultList.toArray(ret);

        return resultList;
    }

    /**
     * Populates a DTO with data from a ResultSet
     */
    protected void populateDto(ResultSet rs, HierarchyDefDto relDto, List<HierarchyNodeEaDto> attrDefList) throws SQLException {
/*
        relDto.setHierarchyId(rs.getLong(RELATIONSHIP.RELATIONSHIP_ID.columnName));
        relDto.setHierarchyDefId(rs.getLong(RELATIONSHIP.RELATIONSHIP_DEF_ID.columnName));
        relDto.setSourceEuid(rs.getString(RELATIONSHIP.SOURCE_EUID.columnName));
        relDto.setTargetEuid(rs.getString(RELATIONSHIP.TARGET_EUID.columnName));
        relDto.setEffectiveFromDate(rs.getDate(RELATIONSHIP.EFFECTIVE_FROM_DATE.columnName));
        relDto.setEffectiveToDate(rs.getDate(RELATIONSHIP.EFFECTIVE_TO_DATE.columnName));
        relDto.setPurgeDate(rs.getDate(RELATIONSHIP.PURGE_DATE.columnName));
        Map attrValueList = relDto.getHierarchyAttributes();
        for (HierarchyEaDto attr : attrDefList) {
            AttributeType attrType = AttributeType.valueOf(attr.getColumnType());
            String attrValue = null;
            switch (attrType) {
                case STRING:
                    attrValue = rs.getString(attr.getColumnName());
                    break;
                case INTEGER:
                    long longVal = rs.getLong(attr.getColumnName());
                    attrValue = Long.toString(longVal);
                    break;
                default:
            }
            attrValueList.put(attr, attrValue);
        }
*/
    }

    /**
     * Resets the modified attributes in the DTO
     */
    protected void reset(HierarchyDefDto dto) {
    }
}
