CREATE TABLE CLUSTER_BUCKET
(
  ID          int identity(1,1),
  BUCKETNAME  VARCHAR(100)                NOT NULL,
  LOADERNAME  VARCHAR(100),
  TYPE        int,
  STATE       int,
  VERSIONNO   int,
  CONSTRAINT PK_CLUSTER_BUCKET PRIMARY KEY (ID),
  CONSTRAINT CLUSTER_BUCKET_UK UNIQUE (BUCKETNAME, LOADERNAME)
)
GO



CREATE UNIQUE INDEX CLUSTER_BUCKET_LOADER ON  CLUSTER_BUCKET (BUCKETNAME, LOADERNAME)
GO






CREATE TABLE LOADER
(
  NAME         VARCHAR(100)               NOT NULL,
  MACHINENAME  VARCHAR(100),
  RMIPORT      int,
  ISMASTER     int,
  STATE        int,
  WORKINGDIR   VARCHAR(200)               NOT NULL,
  CONSTRAINT PK_LOADER PRIMARY KEY (NAME)
)
GO



CREATE TABLE ANALYSIS_STATE
(
  STATE       int,
  ISMASTER    int,
  LOADERNAME  VARCHAR(100),
  DONE        int,
  CONSTRAINT PK_ANALYSIS_STATE PRIMARY KEY (LOADERNAME)
)
GO
