/*
 * DomainRecordDetailDialog.java
 *
 * Created on October 17, 2008, 10:42 AM
 */

package com.sun.mdm.multidomain.project.editor;

import com.sun.mdm.multidomain.parser.FieldGroup;
import com.sun.mdm.multidomain.parser.RecordDetail;
import java.util.ArrayList;
import javax.swing.table.AbstractTableModel;
import org.openide.DialogDisplayer;
import org.openide.NotifyDescriptor;
import org.openide.util.NbBundle;

/**
 *
 * @author  wee
 */
public class DomainRecordDetailDialog extends javax.swing.JDialog {

    private RecordDetail mRecordDetail = null;
    
    private boolean bModified = false;
    /** Creates new form DomainRecordDetailDialog */
    public DomainRecordDetailDialog(RecordDetail recDet, boolean isNew) {
        super(org.openide.windows.WindowManager.getDefault().getMainWindow(), true);
        mRecordDetail = recDet;
        initComponents();
        if (isNew) {
            loadNewRecordDetail();
        } else {
            loadRecordDetail();
        }
        
        jTableFieldGroup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int selectedRow = jTableFieldGroup.getSelectedRow();
                FieldGroup fieldGroup = ((TableModelFieldGroup) jTableFieldGroup.getModel()).getRow(selectedRow);
                TableModelField fieldModel = new TableModelField(fieldGroup);
                 jTableField.setModel(fieldModel);

            }
        });
        
    }
    
   private void loadNewRecordDetail() {
        this.jTxtRecordDetail.setText(mRecordDetail.getDisplayName());
        TableModelFieldGroup fieldGroupModel = new TableModelFieldGroup(mRecordDetail.getFieldGroups());
        jTableFieldGroup.setModel(fieldGroupModel);
        
        //jTableFieldGroup.setRowSelectionInterval(0, 0);
        TableModelField fieldModel = new TableModelField(new FieldGroup());
        this.jTableField.setModel(fieldModel);
        
        
    }
   
    private void loadRecordDetail() {
        this.jTxtRecordDetail.setText(mRecordDetail.getDisplayName());
        TableModelFieldGroup fieldGroupModel = new TableModelFieldGroup(mRecordDetail.getFieldGroups());
        jTableFieldGroup.setModel(fieldGroupModel);
        
        jTableFieldGroup.setRowSelectionInterval(0, 0);
        TableModelField fieldModel = new TableModelField(mRecordDetail.getFieldGroups().get(0));
        this.jTableField.setModel(fieldModel);
        
        
    }

    public boolean isModifed() {
        return this.bModified;
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTxtRecordDetail = new javax.swing.JTextField();
        jPanelFieldGroup = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableFieldGroup = new javax.swing.JTable();
        jBtnAddGroup = new javax.swing.JButton();
        jBtnRemoveGroup = new javax.swing.JButton();
        jPanelField = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableField = new javax.swing.JTable();
        jBtnAddField = new javax.swing.JButton();
        jBtnRemoveField = new javax.swing.JButton();
        jBtnOK = new javax.swing.JButton();
        jBtnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText(org.openide.util.NbBundle.getMessage(DomainRecordDetailDialog.class, "LBL_DOMAIN_RECORD_DETAIL_FIELD")); // NOI18N

        jTxtRecordDetail.setText(org.openide.util.NbBundle.getMessage(DomainRecordDetailDialog.class, "DomainRecordDetailDialog.jTxtRecordDetail.text")); // NOI18N

        jPanelFieldGroup.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(DomainRecordDetailDialog.class, "DomainRecordDetailDialog.jPanelFieldGroup.border.title"))); // NOI18N

        jTableFieldGroup.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "Field Group"
            }
        ));
        jScrollPane1.setViewportView(jTableFieldGroup);
        jTableFieldGroup.getColumnModel().getColumn(0).setHeaderValue(org.openide.util.NbBundle.getMessage(DomainRecordDetailDialog.class, "DomainRecordDetailDialog.jTableFieldGroup.columnModel.title0")); // NOI18N

        jBtnAddGroup.setText(org.openide.util.NbBundle.getMessage(DomainRecordDetailDialog.class, "LBL_Add")); // NOI18N
        jBtnAddGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onAddGroup(evt);
            }
        });

        jBtnRemoveGroup.setText(org.openide.util.NbBundle.getMessage(DomainRecordDetailDialog.class, "LBL_Remove")); // NOI18N
        jBtnRemoveGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onRemoveGroup(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanelFieldGroupLayout = new org.jdesktop.layout.GroupLayout(jPanelFieldGroup);
        jPanelFieldGroup.setLayout(jPanelFieldGroupLayout);
        jPanelFieldGroupLayout.setHorizontalGroup(
            jPanelFieldGroupLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelFieldGroupLayout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .add(jBtnAddGroup)
                .add(18, 18, 18)
                .add(jBtnRemoveGroup)
                .addContainerGap())
            .add(jPanelFieldGroupLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(jPanelFieldGroupLayout.createSequentialGroup()
                    .addContainerGap()
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 187, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanelFieldGroupLayout.setVerticalGroup(
            jPanelFieldGroupLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelFieldGroupLayout.createSequentialGroup()
                .addContainerGap(148, Short.MAX_VALUE)
                .add(jPanelFieldGroupLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jBtnRemoveGroup)
                    .add(jBtnAddGroup)))
            .add(jPanelFieldGroupLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(jPanelFieldGroupLayout.createSequentialGroup()
                    .addContainerGap()
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 129, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(31, Short.MAX_VALUE)))
        );

        jPanelField.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(DomainRecordDetailDialog.class, "DomainRecordDetailDialog.jPanelField.border.title"))); // NOI18N

        jTableField.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "Field"
            }
        ));
        jScrollPane2.setViewportView(jTableField);
        jTableField.getColumnModel().getColumn(0).setHeaderValue(org.openide.util.NbBundle.getMessage(DomainRecordDetailDialog.class, "DomainRecordDetailDialog.jTableField.columnModel.title0")); // NOI18N

        jBtnAddField.setText(org.openide.util.NbBundle.getMessage(DomainRecordDetailDialog.class, "LBL_Add")); // NOI18N
        jBtnAddField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onAddField(evt);
            }
        });

        jBtnRemoveField.setText(org.openide.util.NbBundle.getMessage(DomainRecordDetailDialog.class, "LBL_Remove")); // NOI18N
        jBtnRemoveField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onRemoveField(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanelFieldLayout = new org.jdesktop.layout.GroupLayout(jPanelField);
        jPanelField.setLayout(jPanelFieldLayout);
        jPanelFieldLayout.setHorizontalGroup(
            jPanelFieldLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelFieldLayout.createSequentialGroup()
                .add(55, 55, 55)
                .add(jBtnAddField)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jBtnRemoveField)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(jPanelFieldLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(jPanelFieldLayout.createSequentialGroup()
                    .addContainerGap()
                    .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 177, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanelFieldLayout.setVerticalGroup(
            jPanelFieldLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelFieldLayout.createSequentialGroup()
                .addContainerGap(148, Short.MAX_VALUE)
                .add(jPanelFieldLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jBtnAddField)
                    .add(jBtnRemoveField)))
            .add(jPanelFieldLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(jPanelFieldLayout.createSequentialGroup()
                    .add(7, 7, 7)
                    .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 130, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(34, Short.MAX_VALUE)))
        );

        jBtnOK.setText(org.openide.util.NbBundle.getMessage(DomainRecordDetailDialog.class, "LBL_OK")); // NOI18N
        jBtnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onOK(evt);
            }
        });

        jBtnCancel.setText(org.openide.util.NbBundle.getMessage(DomainRecordDetailDialog.class, "LBL_Cancel")); // NOI18N
        jBtnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onCancel(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(21, 21, 21)
                        .add(jLabel1)
                        .add(18, 18, 18)
                        .add(jTxtRecordDetail, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 179, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jPanelFieldGroup, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 215, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jPanelField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 205, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(285, 285, 285)
                        .add(jBtnOK)
                        .add(31, 31, 31)
                        .add(jBtnCancel)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(jTxtRecordDetail, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(63, 63, 63)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jPanelField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jPanelFieldGroup, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jBtnOK)
                    .add(jBtnCancel))
                .add(31, 31, 31))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-468)/2, (screenSize.height-397)/2, 468, 397);
    }// </editor-fold>//GEN-END:initComponents

private void onAddGroup(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onAddGroup
// TODO add your handling code here:
    TableModelFieldGroup fieldGroupModel = (TableModelFieldGroup) this.jTableFieldGroup.getModel();
    int iInsertRow = fieldGroupModel.getRowCount();
    FieldGroup newFieldGroup = new FieldGroup();
    //Parameter newParam = mSearchType.getSearchOption().createParameter("", "");
    fieldGroupModel.addRow(iInsertRow, newFieldGroup);
    jTableFieldGroup.setModel(fieldGroupModel);
    jTableFieldGroup.clearSelection();
    jTableFieldGroup.addRowSelectionInterval(iInsertRow, iInsertRow);
    jTableFieldGroup.setEditingRow(iInsertRow);
    jTableFieldGroup.setFocusTraversalKeysEnabled(true);
    
}//GEN-LAST:event_onAddGroup

private void onRemoveGroup(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onRemoveGroup
// TODO add your handling code here:
// TODO add your handling code here:
    int rs[] = this.jTableFieldGroup.getSelectedRows();
    int length = rs.length;
    String prompt = (length == 1) ? NbBundle.getMessage(DomainRecordDetailDialog.class, "MSG_Confirm_Remove_Row_Prompt")
            : NbBundle.getMessage(DomainRecordDetailDialog.class, "MSG_Confirm_Remove_Rows_Prompt");
        NotifyDescriptor d = new NotifyDescriptor.Confirmation(
                                 prompt, 
                                 NbBundle.getMessage(DomainRecordDetailDialog.class, "MSG_Confirm_Remove_Row_Title"), 
                                 NotifyDescriptor.YES_NO_OPTION);
        if (DialogDisplayer.getDefault().notify(d) == NotifyDescriptor.YES_OPTION) {
            TableModelFieldGroup model = (TableModelFieldGroup) jTableFieldGroup.getModel();
            for (int i=length - 1; i>=0 && i < length; i--) {
                int j = rs[i];
                Object fieldGroup = (Object) model.getValueAt(j, model.iColRecordDetailName);
                model.removeRow(j);
            }
            if (jTableFieldGroup.getRowCount() > 0) {
                this.jBtnRemoveGroup.setEnabled(true);
                jTableFieldGroup.setRowSelectionInterval(0, 0);
            }
            this.bModified = true;
        }
    
}//GEN-LAST:event_onRemoveGroup

private void onAddField(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onAddField
// TODO add your handling code here:
}//GEN-LAST:event_onAddField

private void onRemoveField(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onRemoveField
// TODO add your handling code here:
// TODO add your handling code here:
    int rs[] = jTableField.getSelectedRows();
    int length = rs.length;
    String prompt = (length == 1) ? NbBundle.getMessage(DomainRecordDetailDialog.class, "MSG_Confirm_Remove_Row_Prompt")
            : NbBundle.getMessage(DomainRecordDetailDialog.class, "MSG_Confirm_Remove_Rows_Prompt");
        NotifyDescriptor d = new NotifyDescriptor.Confirmation(
                                 prompt, 
                                 NbBundle.getMessage(DomainRecordDetailDialog.class, "MSG_Confirm_Remove_Row_Title"), 
                                 NotifyDescriptor.YES_NO_OPTION);
        if (DialogDisplayer.getDefault().notify(d) == NotifyDescriptor.YES_OPTION) {
            TableModelField model = (TableModelField) jTableField.getModel();
            for (int i=length - 1; i>=0 && i < length; i--) {
                int j = rs[i];
                Object standardizationType = (Object) model.getValueAt(j, model.iColFieldName);
                model.removeRow(j);
            }
            
            
            if (jTableField.getRowCount() > 0) {
                this.jBtnRemoveField.setEnabled(true);
                jTableField.setRowSelectionInterval(0, 0);
            }

            this.bModified = true;
        }
    
}//GEN-LAST:event_onRemoveField

private void onOK(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onOK
// TODO add your handling code here:
    bModified = true;
    this.mRecordDetail.setDisplayName(this.jTxtRecordDetail.getText());
    TableModelFieldGroup fieldGroupModel = (TableModelFieldGroup) this.jTableFieldGroup.getModel();
    this.mRecordDetail.setFieldGroups(fieldGroupModel.fieldRows);
    this.dispose();

}//GEN-LAST:event_onOK

private void onCancel(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onCancel
// TODO add your handling code here:
    bModified = false;
    this.dispose();
}//GEN-LAST:event_onCancel

    class TableModelFieldGroup extends AbstractTableModel {

        private String columnNames[] = {NbBundle.getMessage(TabWebManagerDomains.class, "LBL_FIELD_GROUP"),};
        ArrayList fieldRows;
        final static int iColRecordDetailName = 0;

        TableModelFieldGroup(ArrayList rows) {
            fieldRows = rows;
        }

        public int getColumnCount() {
            return columnNames.length;
        }

        public int getRowCount() {
            if (fieldRows != null) {
                return fieldRows.size();
            }
            return 0;
        }

        public String getColumnName(int col) {
            return columnNames[col];
        }

        public Object getValueAt(int row, int col) {
            if (fieldRows != null) {
                FieldGroup singleRow = (FieldGroup) fieldRows.get(row);
                if (singleRow != null) {
                    switch (col) {
                        case iColRecordDetailName:
                            int rowIdx = row + 1;
                            return "FieldGroup-" + rowIdx;
                            //return singleRow.getDisplayName();
                        default:
                            return null;
                    }
                }
            }
            return null;
        }

        public FieldGroup getRow(int row) {
            if (fieldRows != null) {
                FieldGroup singleRow = (FieldGroup) fieldRows.get(row);
                return singleRow;
            }
            return null;
        }

        public Class getColumnClass(int c) {
            Object colNameObj = getValueAt(0, c);
            return colNameObj.getClass();
        }

        /*
         * Don't need to implement this method unless your table's
         * editable.
         */
        public boolean isCellEditable(int row, int col) {
            //Note that the data/cell address is constant,
            //no matter where the cell appears onscreen.
            return true;
        }

        /*
         * Don't need to implement this method unless your table's
         * data can change.
         */
        public void setValueAt(Object value, int row, int col) {
            switch (col) {
                case iColRecordDetailName:
                    ((RecordDetail) fieldRows.get(row)).setDisplayName((String) value);
                    //((RecordDetail) fieldRows.get(row)).setRecordDetailId(Integer.parseInt((String) value));
                    break;

            }

            //fieldRows.set(row, value);
            fireTableCellUpdated(row, col);

        }

        public void removeRow(int index) {
            fieldRows.remove(index);
            this.fireTableRowsDeleted(index, index);
        }

        public void addRow(int index, FieldGroup row) {
            //fieldRows.add(row);
            fieldRows.add(index, row);
            this.fireTableRowsInserted(index, index);
        }

        /**
        public MatchRuleRowPerProbType getRow(int index) {
        //MatchRuleRowPerProbType row = (MatchRuleRowPerProbType) matchRuleRows.get(index);
        return row;
        }
         */
        public int findRowByFieldName(String fieldName) {
            for (int i = 0; i < fieldRows.size(); i++) {
                if (getValueAt(i, iColRecordDetailName).equals(fieldName)) {
                    return i;
                }
            }
            return -1;
        }

        public FieldGroup findRelTypeByFieldName(String fieldName) {
            for (int i = 0; i < fieldRows.size(); i++) {
                if (getValueAt(i, iColRecordDetailName).equals(fieldName)) {
                    return (FieldGroup) fieldRows.get(i);
                }
            }
            return null;
        }
    }


     class TableModelField extends AbstractTableModel {

        private String columnNames[] = {NbBundle.getMessage(TabWebManagerDomains.class, "LBL_FIELD"),};
        ArrayList fieldRows;
        final static int iColFieldName = 0;
        private FieldGroup mFieldGroup = null;

        TableModelField(FieldGroup fieldGroup) {
            mFieldGroup = fieldGroup;
            fieldRows = fieldGroup.getFeildRefs();
        }

        public int getColumnCount() {
            return columnNames.length;
        }

        public int getRowCount() {
            if (fieldRows != null) {
                return fieldRows.size();
            }
            return 0;
        }

        public String getColumnName(int col) {
            return columnNames[col];
        }

        public Object getValueAt(int row, int col) {
            if (fieldRows != null) {
                FieldGroup.FieldRef singleRow = (FieldGroup.FieldRef) fieldRows.get(row);
                if (singleRow != null) {
                    switch (col) {
                        case iColFieldName:
                            return singleRow.getFieldName();
                        default:
                            return null;
                    }
                }
            }
            return null;
        }

        public RecordDetail getRow(int row) {
            if (fieldRows != null) {
                RecordDetail singleRow = (RecordDetail) fieldRows.get(row);
                return singleRow;
            }
            return null;
        }

        public Class getColumnClass(int c) {
            Object colNameObj = getValueAt(0, c);
            return colNameObj.getClass();
        }

        /*
         * Don't need to implement this method unless your table's
         * editable.
         */
        public boolean isCellEditable(int row, int col) {
            //Note that the data/cell address is constant,
            //no matter where the cell appears onscreen.
            return true;
        }

        /*
         * Don't need to implement this method unless your table's
         * data can change.
         */
        public void setValueAt(Object value, int row, int col) {
            switch (col) {
                case iColFieldName:
                    mFieldGroup.createFieldRef((String) value);
                    break;

            }

            //fieldRows.set(row, value);
            fireTableCellUpdated(row, col);

        }

        public void removeRow(int index) {
            fieldRows.remove(index);
            this.fireTableRowsDeleted(index, index);
        }

        public void addRow(int index, FieldGroup.FieldRef row) {
            //fieldRows.add(row);
            fieldRows.add(index, row);
            this.fireTableRowsInserted(index, index);
        }

        /**
        public MatchRuleRowPerProbType getRow(int index) {
        //MatchRuleRowPerProbType row = (MatchRuleRowPerProbType) matchRuleRows.get(index);
        return row;
        }
         */
        public int findRowByFieldName(String fieldName) {
            for (int i = 0; i < fieldRows.size(); i++) {
                if (getValueAt(i, iColFieldName).equals(fieldName)) {
                    return i;
                }
            }
            return -1;
        }

        public FieldGroup.FieldRef findRelTypeByFieldName(String fieldName) {
            for (int i = 0; i < fieldRows.size(); i++) {
                if (getValueAt(i, iColFieldName).equals(fieldName)) {
                    return (FieldGroup.FieldRef) fieldRows.get(i);
                }
            }
            return null;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAddField;
    private javax.swing.JButton jBtnAddGroup;
    private javax.swing.JButton jBtnCancel;
    private javax.swing.JButton jBtnOK;
    private javax.swing.JButton jBtnRemoveField;
    private javax.swing.JButton jBtnRemoveGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanelField;
    private javax.swing.JPanel jPanelFieldGroup;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableField;
    private javax.swing.JTable jTableFieldGroup;
    private javax.swing.JTextField jTxtRecordDetail;
    // End of variables declaration//GEN-END:variables

}
