/*
 * FieldGroupDialog.java
 *
 * Created on October 28, 2008, 11:08 AM
 */
package com.sun.mdm.multidomain.project.editor;

import com.sun.mdm.multidomain.parser.FieldGroup;
import com.sun.mdm.multidomain.project.editor.nodes.DomainNode;
import java.util.ArrayList;
import javax.swing.table.AbstractTableModel;
import org.openide.DialogDisplayer;
import org.openide.NotifyDescriptor;
import org.openide.util.NbBundle;

/**
 *
 * @author  wee
 */
public class FieldGroupDialog extends javax.swing.JDialog {

    private boolean bModified = false;
    private DomainNode mDomainNode = null;
    private FieldGroup mGroup = null;

    /** Creates new form FieldGroupDialog */
    public FieldGroupDialog(FieldGroup group, DomainNode domainNode) {
        super(org.openide.windows.WindowManager.getDefault().getMainWindow(), true);
        mGroup = group;
        mDomainNode = domainNode;
        //super(parent, modal);
        initComponents();
        this.jTxtGroupDescription.setText(group.getDescription());
        loadFields();
        jTableField.addMouseListener(new java.awt.event.MouseAdapter() {

            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnRemove.setEnabled(true);
            }
        });
        
        this.jBtnOK.setEnabled(enabledOKBtn());
        
        jTxtGroupDescription.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jBtnOK.setEnabled(enabledOKBtn());
            }
        });

    }
    
    private void loadFields() {
        ArrayList<FieldRow> fieldRows = new ArrayList<FieldRow>();
        for (FieldGroup.FieldRef field : mGroup.getFieldRefs()) {
            FieldRow fieldRow = new FieldRow(field.getFieldName());
            fieldRows.add(fieldRow);
        }
        TableModelField model = new TableModelField(fieldRows);
        jTableField.setModel(model);
        
    }

    private boolean enabledOKBtn() {
         boolean setEnabled = true;
         
         if (jTxtGroupDescription.getText() == null || jTxtGroupDescription.getText().length() == 0) {
             return !setEnabled;
         }
    
         if (this.jTableField.getRowCount() == 0 ) {
             return !setEnabled;
         }
                  
         return setEnabled;        
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTxtGroupDescription = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableField = new javax.swing.JTable();
        jBtnAdd = new javax.swing.JButton();
        jBtnRemove = new javax.swing.JButton();
        jBtnOK = new javax.swing.JButton();
        jBtnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(org.openide.util.NbBundle.getMessage(FieldGroupDialog.class, "LBL_FIELD_GROUP_DEFINITION")); // NOI18N
        setResizable(false);

        jLabel1.setText(org.openide.util.NbBundle.getMessage(FieldGroupDialog.class, "LBL_Description")); // NOI18N

        jTxtGroupDescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtGroupDescriptionActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(FieldGroupDialog.class, "LBL_FIELD_PROPERTIES"))); // NOI18N

        jTableField.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "Field"
            }
        ));
        jScrollPane1.setViewportView(jTableField);
        jTableField.getColumnModel().getColumn(0).setHeaderValue(org.openide.util.NbBundle.getMessage(FieldGroupDialog.class, "LBL_FIELD")); // NOI18N

        jBtnAdd.setText(org.openide.util.NbBundle.getMessage(FieldGroupDialog.class, "LBL_Add")); // NOI18N
        jBtnAdd.setMaximumSize(new java.awt.Dimension(71, 23));
        jBtnAdd.setMinimumSize(new java.awt.Dimension(71, 23));
        jBtnAdd.setPreferredSize(new java.awt.Dimension(71, 23));
        jBtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onBtnAddField(evt);
            }
        });

        jBtnRemove.setText(org.openide.util.NbBundle.getMessage(FieldGroupDialog.class, "LBL_Remove")); // NOI18N
        jBtnRemove.setEnabled(false);
        jBtnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onBtnRemove(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 433, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                        .add(jBtnAdd, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 93, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jBtnRemove, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 93, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 137, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jBtnRemove)
                    .add(jBtnAdd, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
        );

        jBtnOK.setText(org.openide.util.NbBundle.getMessage(FieldGroupDialog.class, "LBL_OK")); // NOI18N
        jBtnOK.setEnabled(false);
        jBtnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onBtnOK(evt);
            }
        });

        jBtnCancel.setText(org.openide.util.NbBundle.getMessage(FieldGroupDialog.class, "LBL_Cancel")); // NOI18N
        jBtnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onBtnCancel(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(18, 18, 18)
                        .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 108, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(133, 133, 133)
                        .add(jTxtGroupDescription, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(287, Short.MAX_VALUE)
                        .add(jBtnOK, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 93, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jBtnCancel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 93, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(jTxtGroupDescription, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jBtnCancel)
                    .add(jBtnOK))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-497)/2, (screenSize.height-339)/2, 497, 339);
    }// </editor-fold>//GEN-END:initComponents

    public boolean isModified() {
        return bModified;
    }
private void onBtnAddField(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onBtnAddField
    EntityTreeDialog entityDlg = new EntityTreeDialog(mDomainNode.getEntityTree(), mGroup);
    entityDlg.setVisible(true);
    if (entityDlg.isSelected()) {
        if (entityDlg.getFieldList().size() > 0) {
            TableModelField fieldModel = (TableModelField) jTableField.getModel();
            for (String fieldName : entityDlg.getFieldList()) {
                FieldRow fieldRef = new FieldRow(fieldName);
                fieldModel.addRow(fieldModel.getRowCount(), fieldRef);
            }
            jTableField.setModel(fieldModel);
            jBtnOK.setEnabled(true);
        }
    }
}//GEN-LAST:event_onBtnAddField

private void onBtnRemove(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onBtnRemove
// TODO add your handling code here:
    //int rs[] = jTableField.getSelectedRows();
   // int length = rs.length;
    int rs = jTableField.getSelectedRow();
    int length = jTableField.getSelectedRowCount();
    String type = (length == 1) ? NbBundle.getMessage(FieldGroupDialog.class, "LBL_FIELD")
                                : NbBundle.getMessage(FieldGroupDialog.class, "LBL_FIELDS");
    String prompt = (length == 1) ? NbBundle.getMessage(FieldGroupDialog.class, "MSG_Confirm_Remove_Prompt", type)
                                  : NbBundle.getMessage(FieldGroupDialog.class, "MSG_Confirm_Remove_Multiple_Prompt", length, type);;
    String title = NbBundle.getMessage(FieldGroupDialog.class, "MSG_Confirm_Remove_Title", type);

    NotifyDescriptor d = new NotifyDescriptor.Confirmation(
            prompt,
            title,
            NotifyDescriptor.YES_NO_OPTION);
    if (DialogDisplayer.getDefault().notify(d) == NotifyDescriptor.YES_OPTION) {
        TableModelField model = (TableModelField) jTableField.getModel();
        model.removeRow(rs);

        if (jTableField.getRowCount() > 0) {
            jBtnRemove.setEnabled(true);
            jTableField.setRowSelectionInterval(0, 0);
        } else {
            jBtnOK.setEnabled(false);
        }

        this.bModified = true;
    }
    
}//GEN-LAST:event_onBtnRemove

private void onBtnOK(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onBtnOK
// TODO add your handling code here:
    bModified = true;
    mGroup.getFieldRefs().clear();
    mGroup.setDescription(this.jTxtGroupDescription.getText());
    TableModelField fieldModel = (TableModelField) jTableField.getModel();
    for (FieldRow field : fieldModel.fieldRows) {
        mGroup.addFieldRef(mGroup.createFieldRef(field.getFieldName()));

    }
    this.dispose();
}//GEN-LAST:event_onBtnOK

private void onBtnCancel(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onBtnCancel
// TODO add your handling code here:
    bModified = false;
    this.dispose();
}//GEN-LAST:event_onBtnCancel

private void jTxtGroupDescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtGroupDescriptionActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jTxtGroupDescriptionActionPerformed

    class FieldRow {

        private String fieldName;

        public FieldRow(String name) {
            fieldName = name;
        }

        public String getFieldName() {
            return fieldName;
        }

        public void setFieldName(String fieldName) {
            this.fieldName = fieldName;
        }
    }

    class GroupRow {

        private String groupName;
        private int groupId;
        private ArrayList<FieldRow> fieldRows = null;

        public GroupRow(String groupName) {
            this.groupName = groupName;
        }

        public String getGroupName() {
            return groupName;
        }

        public void setGroupName(String groupName) {
            this.groupName = groupName;
        }

        public ArrayList<FieldRow> getFieldRows() {
            return fieldRows;
        }

        public void setFieldRows(ArrayList<FieldRow> fieldRows) {
            this.fieldRows = fieldRows;
        }

        public int getGroupId() {
            return groupId;
        }

        public void setGroupId(int groupId) {
            this.groupId = groupId;
        }
    }

    class TableModelField extends AbstractTableModel {

        private String columnNames[] = {NbBundle.getMessage(FieldGroupDialog.class, "LBL_FIELD"),};
        ArrayList<FieldRow> fieldRows;
        final static int iColFieldName = 0;
 
        TableModelField(ArrayList<FieldRow> rows) {
            fieldRows = rows;
        }

        public int getColumnCount() {
            return columnNames.length;
        }

        public int getRowCount() {
            if (fieldRows != null) {
                return fieldRows.size();
            }
            return 0;
        }

        public String getColumnName(int col) {
            return columnNames[col];
        }

        public Object getValueAt(int row, int col) {
            if (fieldRows != null) {
                FieldRow singleRow = (FieldRow) fieldRows.get(row);
                if (singleRow != null) {
                    switch (col) {
                        case iColFieldName:
                            return singleRow.getFieldName();
                        default:
                            return null;
                    }
                }
            }
            return null;
        }

        public FieldRow getRow(int row) {
            if (fieldRows != null) {
                return fieldRows.get(row);
            }
            return null;
        }

        public Class getColumnClass(int c) {
            Object colNameObj = getValueAt(0, c);
            return colNameObj.getClass();
        }

        /*
         * Don't need to implement this method unless your table's
         * editable.
         */
        public boolean isCellEditable(int row, int col) {
            //Note that the data/cell address is constant,
            //no matter where the cell appears onscreen.
            return false;
        }

        /*
         * Don't need to implement this method unless your table's
         * data can change.
         */
        public void setValueAt(Object value, int row, int col) {
            switch (col) {
                case iColFieldName:
                    fieldRows.set(row, (FieldRow) value);
                    break;

            }

            //fieldRows.set(row, value);
            fireTableCellUpdated(row, col);

        }

        public void removeRow(int index) {
            fieldRows.remove(index);
            this.fireTableRowsDeleted(index, index);
        }

        public void addRow(int index, FieldRow row) {
            //fieldRows.add(row);
            fieldRows.add(index, row);
            this.fireTableRowsInserted(index, index);
        }

        /**
        public MatchRuleRowPerProbType getRow(int index) {
        //MatchRuleRowPerProbType row = (MatchRuleRowPerProbType) matchRuleRows.get(index);
        return row;
        }
         */
        public int findRowByFieldName(String fieldName) {
            for (int i = 0; i < fieldRows.size(); i++) {
                if (getValueAt(i, iColFieldName).equals(fieldName)) {
                    return i;
                }
            }
            return -1;
        }

        public FieldRow findRelTypeByFieldName(String fieldName) {
            for (int i = 0; i < fieldRows.size(); i++) {
                if (getValueAt(i, iColFieldName).equals(fieldName)) {
                    return fieldRows.get(i);
                }
            }
            return null;
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAdd;
    private javax.swing.JButton jBtnCancel;
    private javax.swing.JButton jBtnOK;
    private javax.swing.JButton jBtnRemove;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableField;
    private javax.swing.JTextField jTxtGroupDescription;
    // End of variables declaration//GEN-END:variables
}
