/*
 * TabRelationshipTypes.java
 *
 * Created on October 1, 2008, 9:54 AM
 */

package com.sun.mdm.multidomain.project.editor;

import java.util.ArrayList;
import com.sun.mdm.multidomain.parser.RelationshipType;
/**
 *
 * @author  kkao
 */
public class TabListRelationshipTypes extends javax.swing.JPanel {

    /** Creates new form TabRelationshipTypes */
    public TabListRelationshipTypes(ArrayList <RelationshipType> alRelationshipTypes) {
        initComponents();
        
        //ToDo
        //Load relationship type list
        javax.swing.table.TableModel model = this.jTableRelationshipTypes.getModel();
        for (int i=0; i < alRelationshipTypes.size(); i++) {
            RelationshipType type = alRelationshipTypes.get(i);
            String relationshipTypeName = type.getName();
            String sourceDomain = type.getSourceDomain();
            String targetDomain = type.getTargetDomain();
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPaneRelationshipTypes = new javax.swing.JScrollPane();
        jTableRelationshipTypes = new javax.swing.JTable();

        setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), org.openide.util.NbBundle.getMessage(TabListRelationshipTypes.class, "LBL_Relationship_Types"))); // NOI18N

        jTableRelationshipTypes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Source Domain", "Target Domain"
            }
        ));
        jScrollPaneRelationshipTypes.setViewportView(jTableRelationshipTypes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneRelationshipTypes, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPaneRelationshipTypes, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPaneRelationshipTypes;
    private javax.swing.JTable jTableRelationshipTypes;
    // End of variables declaration//GEN-END:variables

}
