/*
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 *
 * Copyright 2003-2007 Sun Microsystems, Inc. All Rights Reserved.
 *
 * The contents of this file are subject to the terms of the Common 
 * Development and Distribution License ("CDDL")(the "License"). You 
 * may not use this file except in compliance with the License.
 *
 * You can obtain a copy of the License at
 * https://open-dm-mi.dev.java.net/cddl.html
 * or open-dm-mi/bootstrap/legal/license.txt. See the License for the 
 * specific language governing permissions and limitations under the  
 * License.  
 *
 * When distributing the Covered Code, include this CDDL Header Notice 
 * in each file and include the License file at
 * open-dm-mi/bootstrap/legal/license.txt.
 * If applicable, add the following below this CDDL Header, with the 
 * fields enclosed by brackets [] replaced by your own identifying 
 * information: "Portions Copyrighted [year] [name of copyright owner]"
 */

package com.sun.mdm.multidomain.project.editor;

import org.openide.util.NbBundle;
import java.util.Map;
import java.util.HashMap;
import java.util.ArrayList;
import javax.swing.table.TableColumn;
import javax.swing.table.AbstractTableModel;

import com.sun.mdm.multidomain.project.editor.nodes.DomainNode;
import com.sun.mdm.multidomain.parser.RelationshipType;
/**
 *
 * @author  kkao
 */
public class TabOverview extends javax.swing.JPanel {
    private final String ALL_DOMAINS = org.openide.util.NbBundle.getMessage(TabOverview.class, "All_Domains");
    private ArrayList <DomainNode> mAlDomainNodes;
    private ArrayList <RelationshipType> mAlRelationshipTypes;
    private Map <String, DomainNode> mMapDomainNodes = new HashMap();  // domainName, DomainNode
    /** Creates new form TabOverview */
    public TabOverview(ArrayList <DomainNode> alDomainNodes) {
        initComponents();
        mAlDomainNodes = alDomainNodes;
        jComboBoxAllDomains.removeAllItems();
        jComboBoxAssociatedDomains.removeAllItems();
        jComboBoxAssociatedDomains.addItem(ALL_DOMAINS);

        DomainNode domainNode;
        String domainName;
        for (int i=0; mAlDomainNodes != null && i < mAlDomainNodes.size(); i++) {
            domainNode = mAlDomainNodes.get(i);
            domainName = domainNode.getName();
            mMapDomainNodes.put(domainName, domainNode);
            jComboBoxAllDomains.addItem(domainName);
        }
        
        ArrayList rows = new ArrayList();
        if (mAlDomainNodes != null) {
            domainNode = mAlDomainNodes.get(0);
            domainName = domainNode.getName();
            mAlRelationshipTypes = domainNode.getRelationshipTypes();

            for (int j=0; mAlRelationshipTypes != null && j < mAlRelationshipTypes.size(); j++) {
                RelationshipType type = mAlRelationshipTypes.get(j);
                String sourceDomain = type.getSourceDomain();
                String targetDomain = type.getTargetDomain();
                String domainWithRelationship = (domainName.equals(sourceDomain)) ? targetDomain : sourceDomain;
                jComboBoxAssociatedDomains.addItem(domainWithRelationship);
                RelationshipTypeRow r = new RelationshipTypeRow(type.getName(), type.getType(), type.getSourceDomain(), type.getTargetDomain());
                rows.add(r);
            }
        }
        jComboBoxAssociatedDomains.setSelectedIndex(0);
        TableModelRelationshipType model = new TableModelRelationshipType(rows);
        this.jTableRelationshipTypes.setModel(model);
        
        
        jComboBoxAllDomains.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                onAllDomainsItemStateChanged(evt);
            }
        });
        jComboBoxAssociatedDomains.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                onDomainsItemStateChanged(evt);
            }
        });


    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelDomainName = new javax.swing.JLabel();
        jLabelAssociated = new javax.swing.JLabel();
        jComboBoxAssociatedDomains = new javax.swing.JComboBox();
        jScrollPaneRelationshipTypes = new javax.swing.JScrollPane();
        jTableRelationshipTypes = new javax.swing.JTable();
        jComboBoxAllDomains = new javax.swing.JComboBox();

        setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), org.openide.util.NbBundle.getMessage(TabOverview.class, "LBL_Participating_Domains"))); // NOI18N
        setLayout(null);

        jLabelDomainName.setText(org.openide.util.NbBundle.getMessage(TabOverview.class, "LBL_Domain")); // NOI18N
        add(jLabelDomainName);
        jLabelDomainName.setBounds(10, 20, 39, 14);
        jLabelDomainName.getAccessibleContext().setAccessibleName(org.openide.util.NbBundle.getMessage(TabOverview.class, "TabListRelationshipTypes.jLabelDomainName.AccessibleContext.accessibleName")); // NOI18N

        jLabelAssociated.setText(org.openide.util.NbBundle.getMessage(TabOverview.class, "LBL_Associated_Domains")); // NOI18N
        add(jLabelAssociated);
        jLabelAssociated.setBounds(10, 50, 99, 14);

        add(jComboBoxAssociatedDomains);
        jComboBoxAssociatedDomains.setBounds(120, 50, 110, 20);

        jTableRelationshipTypes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Source Domain", "Target Domain"
            }
        ));
        jScrollPaneRelationshipTypes.setViewportView(jTableRelationshipTypes);

        add(jScrollPaneRelationshipTypes);
        jScrollPaneRelationshipTypes.setBounds(10, 90, 470, 230);

        add(jComboBoxAllDomains);
        jComboBoxAllDomains.setBounds(120, 20, 110, 20);
    }// </editor-fold>//GEN-END:initComponents

    private void onAllDomainsItemStateChanged(java.awt.event.ItemEvent evt) {
        String domainName = (String) jComboBoxAllDomains.getSelectedItem();
        DomainNode domainNode = mMapDomainNodes.get(domainName);
        mAlRelationshipTypes = domainNode.getRelationshipTypes();
        if (jComboBoxAssociatedDomains.getItemCount() > 0) {
            jComboBoxAssociatedDomains.removeAllItems();
        }
        jComboBoxAssociatedDomains.addItem(ALL_DOMAINS);
        for (int j=0; mAlRelationshipTypes != null && j < mAlRelationshipTypes.size(); j++) {
            RelationshipType type = mAlRelationshipTypes.get(j);
            String sourceDomain = type.getSourceDomain();
            String targetDomain = type.getTargetDomain();
            String domainWithRelationship = (domainName.equals(sourceDomain)) ? targetDomain : sourceDomain;
            jComboBoxAssociatedDomains.addItem(domainWithRelationship);
        }
        jComboBoxAssociatedDomains.setSelectedIndex(0);
    }

    private void onDomainsItemStateChanged(java.awt.event.ItemEvent evt) {
        String associatedDomain = (String) jComboBoxAssociatedDomains.getSelectedItem();
        TableModelRelationshipType model = (TableModelRelationshipType) jTableRelationshipTypes.getModel();
        model.rows.clear();
        int index = 0;

        for (int i=0; mAlRelationshipTypes != null && i < mAlRelationshipTypes.size(); i++) {
            RelationshipType type = mAlRelationshipTypes.get(i);
            String sourceDomain = type.getSourceDomain();
            String targetDomain = type.getTargetDomain();
            boolean associated = false;
            if (associatedDomain != null) {
                associated = (associatedDomain.equals(sourceDomain)) | (associatedDomain.equals(targetDomain));
            }
            if (jComboBoxAssociatedDomains.getSelectedIndex() == 0 || associated) {
                RelationshipTypeRow r = new RelationshipTypeRow(type.getName(), type.getType(), type.getSourceDomain(), type.getTargetDomain());
                model.addRow(index++, r);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBoxAllDomains;
    private javax.swing.JComboBox jComboBoxAssociatedDomains;
    private javax.swing.JLabel jLabelAssociated;
    private javax.swing.JLabel jLabelDomainName;
    private javax.swing.JScrollPane jScrollPaneRelationshipTypes;
    private javax.swing.JTable jTableRelationshipTypes;
    // End of variables declaration//GEN-END:variables
    
    class RelationshipTypeRow {

        private String relationshipTypeName;
        private String type;
        private String sourceDomain;
        private String targetDomain;

        public RelationshipTypeRow(String relationshipTypeName, String type, String sourceDomain, String targetDomain) {
            this.relationshipTypeName = relationshipTypeName;
            this.type = type;
            this.sourceDomain = sourceDomain;
            this.targetDomain = targetDomain;
        }

        public String getRelationshipTypeName() {
            return relationshipTypeName;
        }

        public void setRelationshipTypeName(String relationshipTypeName) {
            this.relationshipTypeName = relationshipTypeName;
        }
        
        public String getRelationshipTypeType() {
            return type;
        }

        public void setRelationshipTypeType(String type) {
            this.type = type;
        }

        public String getSourceDomain() {
            return sourceDomain;
        }

        public void setSourceDomain(String sourceDomain) {
            this.sourceDomain = sourceDomain;
        }

        public String getTargetDomain() {
            return targetDomain;
        }

        public void setTargetDomain(String targetDomain) {
            this.targetDomain = targetDomain;
        }
    }

    // Table model for Relationship Type
    class TableModelRelationshipType extends AbstractTableModel {
        private	String columnNames [] = {NbBundle.getMessage(TabOverview.class, "LBL_RelationshipType_Name"),
                                         NbBundle.getMessage(TabOverview.class, "LBL_RelationshipType_Type"), 
                                         NbBundle.getMessage(TabOverview.class, "LBL_Source_Domain"), 
                                         NbBundle.getMessage(TabOverview.class, "LBL_Target_Domain"), 
                                        };
        ArrayList rows;
        final static int iColRelationshipTypeName = 0;
        final static int iColRelationshipTypeType = 1;
        final static int iColSourceDomain = 2;
        final static int iColTargetDomain = 3;
        
        TableModelRelationshipType(ArrayList rows) {
            this.rows = rows;
        }
        
        public int getColumnCount() {
            return columnNames.length;
        }

        public int getRowCount() {
            if (rows != null) {
                return rows.size();
            }
            return 0;
        }

        public String getColumnName(int col) {
            return columnNames[col];
        }

        public Object getValueAt(int row, int col) {
            if (rows != null) {
                RelationshipTypeRow singleRow = (RelationshipTypeRow) rows.get(row);
                if (singleRow != null) {
                    switch (col) {
                        case iColRelationshipTypeName:
                            return singleRow.getRelationshipTypeName();
                        case iColRelationshipTypeType:
                            return singleRow.getRelationshipTypeType();
                        case iColSourceDomain:
                           return singleRow.getSourceDomain();
                        case iColTargetDomain:
                           return singleRow.getTargetDomain();
                        default:
                            return null;
                    }
                }
            }
            return null;
        }

        /*
         * Don't need to implement this method unless your table's
         * editable.
         */
        public boolean isCellEditable(int row, int col) {
            //Note that the data/cell address is constant,
            //no matter where the cell appears onscreen.
            return false;
        }

        /*
         * Don't need to implement this method unless your table's
         * data can change.
         */
        public void setValueAt(Object value, int row, int col) {
            if (rows != null && row >=0 && row < rows.size()) {
                RelationshipTypeRow singleRow = (RelationshipTypeRow) rows.get(row);
                if (singleRow != null) {
                    switch (col) {
                        case iColRelationshipTypeName:
                            singleRow.setRelationshipTypeName((String) value);                            
                            break;
                        case iColRelationshipTypeType:
                            singleRow.setRelationshipTypeType((String) value);                            
                            break;
                        case iColSourceDomain:
                            singleRow.setSourceDomain((String) value);                            
                            break;
                        case iColTargetDomain:
                            singleRow.setTargetDomain((String) value);                            
                            break;
                        default:
                            return;
                    }
                }
                fireTableCellUpdated(row, col);
            }
        }
        
        public void removeRow(int index) {
            rows.remove(index);
            this.fireTableRowsDeleted(index, index);
        }
        
        public void addRow(int index, RelationshipTypeRow row) {
            rows.add(row);
            this.fireTableRowsInserted(index, index);
        }

        public RelationshipTypeRow getRow(int index) {
            RelationshipTypeRow row = (RelationshipTypeRow) rows.get(index);
            return row;
        }
    }
}
