/*
 * TabRelationshipWebManager.java
 *
 * Created on September 22, 2008, 1:48 PM
 */

package com.sun.mdm.multidomain.project.editor;

import com.sun.mdm.multidomain.parser.RelationshipType;
import com.sun.mdm.multidomain.parser.RelationshipWebManager;
import java.util.ArrayList;
import org.openide.util.NbBundle;

/**
 *
 * @author  wee
 */
public class TabRelationshipWebManager extends javax.swing.JPanel {
    
    private TabWebManagerRelationshipTypes mTabRelationshipTyps = null;
    
    private TabWebManagerDomains mTabDomains = null;
    
    ArrayList<RelationshipType> mRelationshipTypes = new ArrayList<RelationshipType>();
    
    RelationshipWebManager mRelationshipWebManager = null;
    
    private EditorMainApp mEditorMainApp = null;
    
    private boolean mModified = false;
    
    static final String TAB_RELATIONSHIP_TYPES = NbBundle.getMessage(TabRelationshipWebManager.class,
            "MSG_TAB_WEB_MANAGER_REL_TYPE");
    static final String TAB_DOMAINS = NbBundle.getMessage(TabRelationshipWebManager.class,
            "MSG_TAB_WEB_MANAGER_Domains");


    /** Creates new form TabRelationshipWebManager */
    public TabRelationshipWebManager(EditorMainApp editorMainApp, RelationshipWebManager relationshipWebManager) {  
        mEditorMainApp = editorMainApp;
        mRelationshipWebManager = relationshipWebManager;
        mRelationshipTypes = mRelationshipWebManager.getRelationshipTypes();
        initComponents();
        generateTabs();
        createRelationshipTypes();
    }
    
    
    private void createRelationshipTypes() {
        
    }
    
    public void generateTabs() {
        getRelationshipTypesTab();
        getDoaminsTab();
        jTabbedPaneRelWebManager.addTab(TAB_RELATIONSHIP_TYPES, mTabRelationshipTyps);
        jTabbedPaneRelWebManager.addTab(TAB_DOMAINS, mTabDomains);
    }
    
    protected TabWebManagerRelationshipTypes getRelationshipTypesTab() {
        if (mTabRelationshipTyps == null) {
            mTabRelationshipTyps = new TabWebManagerRelationshipTypes(mEditorMainApp, mRelationshipTypes);
        }
        
        return mTabRelationshipTyps;
    }

    protected TabWebManagerDomains getDoaminsTab() {
        if (mTabDomains == null) {
            mTabDomains = new TabWebManagerDomains();
        }
        
        return mTabDomains;
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneRelWebManager = new javax.swing.JTabbedPane();

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jTabbedPaneRelWebManager, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jTabbedPaneRelWebManager, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPaneRelWebManager;
    // End of variables declaration//GEN-END:variables

}
