/*
 * TabRelationshipWebManager.java
 *
 * Created on September 22, 2008, 1:48 PM
 */

package com.sun.mdm.multidomain.project.editor;

import com.sun.mdm.multidomain.parser.Definition;
import com.sun.mdm.multidomain.parser.MultiDomainWebManager;
import com.sun.mdm.multidomain.parser.RelationshipType;
import java.util.ArrayList;
import org.openide.util.NbBundle;

/**
 *
 * @author  wee
 */
public class TabRelationshipWebManager extends javax.swing.JPanel {
    
    private TabWebManagerRelationshipTypes mTabRelationshipTyps = null;
    
    private TabDomainSearch mTabDomains = null;
    

    private TabDomainView mTabDomainView = null;
    
    ArrayList<RelationshipType> mRelationshipTypes = new ArrayList<RelationshipType>();
    //ArrayList<RelationshipType> mLinkTypes = new ArrayList<LinkType>();
    
    MultiDomainWebManager mMultiDomainWebManager = null;
    
    private EditorMainApp mEditorMainApp = null;
    
    private boolean mModified = false;
    
    static final String TAB_RELATIONSHIP_TYPES = NbBundle.getMessage(TabRelationshipWebManager.class,
            "MSG_TAB_WEB_MANAGER_REL_TYPE");
    static final String TAB_DOMAIN_SERCH = NbBundle.getMessage(TabRelationshipWebManager.class,
            "MSG_TAB_WEB_MANAGER_Domain_SEARCH");
    static final String TAB_DOMAIN_VIEW = NbBundle.getMessage(TabRelationshipWebManager.class,
            "MSG_TAB_WEB_MANAGER_Domain_VIEW");


    /** Creates new form TabRelationshipWebManager */
    public TabRelationshipWebManager(EditorMainApp editorMainApp, MultiDomainWebManager multiDomainWebManager) {  
        mEditorMainApp = editorMainApp;
        mMultiDomainWebManager = multiDomainWebManager;
        mRelationshipTypes = mMultiDomainWebManager.getRelationshipTypes();
        initComponents();
        generateTabs();
        createLinkTypes();
    }
    
    
    private void createLinkTypes() {
        
    }
    
    public void generateTabs() {
        getRelationshipTypesTab();
        getDoaminsTab();
        getDomainViewTab();
        jTabbedPaneRelWebManager.addTab(TAB_RELATIONSHIP_TYPES, mTabRelationshipTyps);
        jTabbedPaneRelWebManager.addTab(TAB_DOMAIN_VIEW, mTabDomainView);
        jTabbedPaneRelWebManager.addTab(TAB_DOMAIN_SERCH, mTabDomains);
    }
    
    protected TabWebManagerRelationshipTypes getRelationshipTypesTab() {
        if (mTabRelationshipTyps == null) {
            //mTabRelationshipTyps = new TabWebManagerRelationshipTypes(mEditorMainApp, mRelationshipTypes);
        }
        
        return mTabRelationshipTyps;
    }

    protected TabDomainSearch getDoaminsTab() {
        /**
        if (mTabDomains == null) {
            mTabDomains = new TabDomainSearch(mEditorMainApp, mMultiDomainWebManager.getDomains());
        }
         */ 
        
        return mTabDomains;
    }
    
    
    protected TabDomainView getDomainViewTab() {
        /**
        if (mTabDomainView == null) {
            mTabDomainView = new TabDomainView(mEditorMainApp, mMultiDomainWebManager.getDomains());
        }
        */
        return mTabDomainView;
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneRelWebManager = new javax.swing.JTabbedPane();

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jTabbedPaneRelWebManager, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jTabbedPaneRelWebManager, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPaneRelWebManager;
    // End of variables declaration//GEN-END:variables

}
