/*
 * WebScreenPropertiesDialog.java
 *
 * Created on November 11, 2008, 2:20 PM
 */

package com.sun.mdm.multidomain.project.editor;

import com.sun.mdm.multidomain.parser.PageDefinition;
import com.sun.mdm.multidomain.parser.ScreenDefinition;
import javax.swing.InputVerifier;
import javax.swing.JComponent;
import javax.swing.JTextField;
import javax.swing.SpinnerNumberModel;
import org.openide.util.NbBundle;

/**
 *
 * @author  wee
 */
public class WebScreenPropertiesDialog extends javax.swing.JDialog {
    private final String SCREEN_RELATIONSHIP = NbBundle.getMessage(WebScreenPropertiesDialog.class, "MSG_TAB_RELATIONSHIP");
    private final String SCREEN_HIERARCHY = NbBundle.getMessage(WebScreenPropertiesDialog.class, "MSG_TAB_HIERARCHY");
    private final String SCREEN_GROUP = NbBundle.getMessage(WebScreenPropertiesDialog.class, "MSG_TAB_GROUP");
    private final String SCREEN_CATEGORY = NbBundle.getMessage(WebScreenPropertiesDialog.class, "MSG_TAB_CATEGORY");

    private NumbericVerifier verifier = new NumbericVerifier();
    
    private PageDefinition mPageDefinition = null;
    
    private boolean bModified = false;
    
    /** Creates new form WebScreenPropertiesDialog */
    public WebScreenPropertiesDialog(PageDefinition pageDefinition) {
        super(org.openide.windows.WindowManager.getDefault().getMainWindow(), true);
        mPageDefinition = pageDefinition;
        initComponents();
        loadScreenList();
        jSpinnerItemPerPage.setModel(new SpinnerNumberModel(1, 1, 300000, 1));
        jSpinnerMaxItems.setModel(new SpinnerNumberModel(1, 1, 300000, 1));
        jSpinnerItemPerPage.setInputVerifier(verifier);
        jSpinnerMaxItems.setInputVerifier(verifier);
        
        
        loadScreenProperties();


        jCBScreenList.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                loadScreenProperties();
            }
        });
    }
    
    private void loadScreenList() {
        jCBScreenList.addItem(SCREEN_RELATIONSHIP);
        jCBScreenList.addItem(SCREEN_HIERARCHY);
        jCBScreenList.addItem(SCREEN_GROUP);  
        jCBScreenList.addItem(SCREEN_CATEGORY);
        
        String screenType = mPageDefinition.getScreenDefs().get(0).getIdentifier();
        jCBScreenList.setSelectedItem(screenType);     
        
    }
    
    private void loadScreenProperties() {
        String selectedScreenType = (String) jCBScreenList.getSelectedItem();
        ScreenDefinition screenDef = mPageDefinition.getScreenDefintion(selectedScreenType);
        if (screenDef != null) {
            
        }
        
    }

    public boolean isModified() {
        return bModified;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jCBScreenList = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanelSubScreen = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTxtScreenTitle = new javax.swing.JTextField();
        jLabelItemPerPage = new javax.swing.JLabel();
        jSpinnerItemPerPage = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jSpinnerMaxItems = new javax.swing.JSpinner();
        jBtnOK = new javax.swing.JButton();
        jBtnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(org.openide.util.NbBundle.getMessage(WebScreenPropertiesDialog.class, "LBL_SCREEN_PROPERTIES")); // NOI18N
        setResizable(false);

        jLabel1.setText(org.openide.util.NbBundle.getMessage(WebScreenPropertiesDialog.class, "LBL_INITIAL_SCREEN")); // NOI18N

        jCBScreenList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onCBScreenList(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null}
            },
            new String [] {
                "Subscreen"
            }
        ));
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getColumn(0).setHeaderValue(org.openide.util.NbBundle.getMessage(WebScreenPropertiesDialog.class, "LBL_SUBSCREEN_NAME")); // NOI18N

        jPanelSubScreen.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(WebScreenPropertiesDialog.class, "LBL_SUBSCREEN_PROPERTIES"))); // NOI18N

        jLabel2.setText(org.openide.util.NbBundle.getMessage(WebScreenPropertiesDialog.class, "LBL_SUBSCREEN_TITLE")); // NOI18N

        jLabelItemPerPage.setText(org.openide.util.NbBundle.getMessage(WebScreenPropertiesDialog.class, "LBL_ITEM_PER_PAGE")); // NOI18N

        jLabel3.setText(org.openide.util.NbBundle.getMessage(WebScreenPropertiesDialog.class, "LBL_MAX_ITEMS")); // NOI18N

        org.jdesktop.layout.GroupLayout jPanelSubScreenLayout = new org.jdesktop.layout.GroupLayout(jPanelSubScreen);
        jPanelSubScreen.setLayout(jPanelSubScreenLayout);
        jPanelSubScreenLayout.setHorizontalGroup(
            jPanelSubScreenLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelSubScreenLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanelSubScreenLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabelItemPerPage)
                    .add(jLabel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 82, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelSubScreenLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jTxtScreenTitle, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 244, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanelSubScreenLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, jSpinnerItemPerPage)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, jSpinnerMaxItems, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        jPanelSubScreenLayout.setVerticalGroup(
            jPanelSubScreenLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelSubScreenLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanelSubScreenLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(jTxtScreenTitle, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPanelSubScreenLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelItemPerPage)
                    .add(jSpinnerItemPerPage, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(31, 31, 31)
                .add(jPanelSubScreenLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(jSpinnerMaxItems, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jBtnOK.setText(org.openide.util.NbBundle.getMessage(WebScreenPropertiesDialog.class, "LBL_OK")); // NOI18N
        jBtnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onBtnOK(evt);
            }
        });

        jBtnCancel.setText(org.openide.util.NbBundle.getMessage(WebScreenPropertiesDialog.class, "LBL_Cancel")); // NOI18N
        jBtnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onBtnCancel(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(34, 34, 34)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, jScrollPane1)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                            .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 116, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                            .add(jCBScreenList, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 216, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                        .add(layout.createSequentialGroup()
                            .add(jBtnOK, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 93, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(18, 18, 18)
                            .add(jBtnCancel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 93, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(jPanelSubScreen, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(25, 25, 25)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(jCBScreenList, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(27, 27, 27)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 115, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jPanelSubScreen, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jBtnCancel)
                    .add(jBtnOK))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-520)/2, (screenSize.height-479)/2, 520, 479);
    }// </editor-fold>//GEN-END:initComponents

private void onCBScreenList(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onCBScreenList
// TODO add your handling code here:
}//GEN-LAST:event_onCBScreenList

private void onBtnOK(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onBtnOK
// TODO add your handling code here:
    bModified = true;
    this.dispose();
}//GEN-LAST:event_onBtnOK

private void onBtnCancel(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onBtnCancel
// TODO add your handling code here:
    this.dispose();
}//GEN-LAST:event_onBtnCancel


    class NumbericVerifier extends InputVerifier {

        public boolean verify(JComponent input) {
            JTextField tf = (JTextField) input;
            String numStr = tf.getText();
            if (Integer.parseInt(numStr) > 0) {
                return true;
            }
            return false;
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCancel;
    private javax.swing.JButton jBtnOK;
    private javax.swing.JComboBox jCBScreenList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelItemPerPage;
    private javax.swing.JPanel jPanelSubScreen;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinnerItemPerPage;
    private javax.swing.JSpinner jSpinnerMaxItems;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTxtScreenTitle;
    // End of variables declaration//GEN-END:variables

}
