CREATE TABLE SBYN_SYSTEMS
(
    SYSTEMCODE		varchar(20)	NOT NULL,
    DESCRIPTION		varchar(50)	NOT NULL,
    STATUS		char		NOT NULL,
    ID_LENGTH		numeric(38)		NOT NULL,
    FORMAT		varchar(60)	NULL    ,
    INPUT_MASK		varchar(60)	NULL    ,
    VALUE_MASK		varchar(60)	NULL    ,
    CREATE_DATE		datetime		NOT NULL,
    CREATE_USERID	varchar(20)	NOT NULL,
    UPDATE_DATE		datetime		NULL    ,
    UPDATE_USERID	varchar(20)	NULL    ,
    CONSTRAINT PK_SBYN_SYSTEM PRIMARY KEY (SYSTEMCODE)
)
GO

CREATE TABLE SBYN_USER_CODE
(
    CODE_LIST		varchar(20)	NOT NULL,
    CODE			varchar(20)	NOT NULL,
    DESCR			varchar(50)	NOT NULL,
    FORMAT			varchar(60)	NULL    ,
    INPUT_MASK		varchar(60)	NULL    ,
    VALUE_MASK		varchar(60)	NULL    ,
    CONSTRAINT PK_SBYN_USER_CODE PRIMARY KEY (CODE_LIST, CODE)
)
GO

CREATE TABLE SBYN_SYSTEMOBJECT (
    SYSTEMCODE varchar(20),
    LID varchar(25),
    CHILDTYPE varchar(20),
    CREATEUSER varchar(30),
    CREATEFUNCTION varchar(20),
    CREATEDATE datetime,
    UPDATEUSER varchar(30),
    UPDATEFUNCTION varchar(20),
    UPDATEDATE datetime,
    STATUS varchar(15),
    CONSTRAINT PK_SBYNSYSTEMOBJECT PRIMARY KEY(SYSTEMCODE, LID))
GO	

ALTER TABLE SBYN_SYSTEMOBJECT ADD CONSTRAINT FK_SYSTEMOBJECT_SYSTEMCODE FOREIGN KEY (SYSTEMCODE) REFERENCES SBYN_SYSTEMS(SYSTEMCODE)
GO

CREATE TABLE SBYN_SYSTEMSBR (
    EUID varchar(20),
    CHILDTYPE varchar(20),
    CREATESYSTEM varchar(20),
    CREATEUSER varchar(30),
    CREATEFUNCTION varchar(20),
    CREATEDATE datetime,
    UPDATESYSTEM varchar(20),
    UPDATEUSER varchar(30),
    UPDATEFUNCTION varchar(20),
    UPDATEDATE datetime,
    STATUS varchar(15),
    REVISIONNUMBER numeric(38),
    CONSTRAINT PK_SBYNSYSTEMSBR PRIMARY KEY(EUID))
GO      

CREATE TABLE SBYN_OVERWRITE (
    EUID varchar(20),
    PATH varchar(200),
    TYPE varchar(20),
    INTEGERDATA numeric(38),
    BOOLEANDATA numeric(38),
    STRINGDATA varchar(200),
    BYTEDATA char(2),
    LONGDATA varchar(max),
    DATEDATA datetime,
    FLOATDATA numeric(38, 4),
    TIMESTAMPDATA datetime,
    CONSTRAINT PK_SBROVERWRITE PRIMARY KEY(EUID, PATH))
GO	

ALTER TABLE SBYN_OVERWRITE ADD CONSTRAINT FK_SYSTEMSBR_EUID FOREIGN KEY (EUID) REFERENCES SBYN_SYSTEMSBR(EUID)
GO

CREATE TABLE SBYN_ENTERPRISE (
    SYSTEMCODE varchar(20),
    LID varchar(25),
    EUID varchar(20),
    CONSTRAINT PK_ENTERPRISE PRIMARY KEY(SYSTEMCODE, LID, EUID))
GO	

ALTER TABLE SBYN_ENTERPRISE ADD CONSTRAINT FK_ENTERPRISE_SYSTEMCODE_LID FOREIGN KEY (SYSTEMCODE, LID) REFERENCES SBYN_SYSTEMOBJECT(SYSTEMCODE, LID)
GO
ALTER TABLE SBYN_ENTERPRISE ADD CONSTRAINT FK_ENTERPRISE_EUID FOREIGN KEY (EUID) REFERENCES SBYN_SYSTEMSBR(EUID)
GO

CREATE TABLE SBYN_TRANSACTION (
    TRANSACTIONNUMBER varchar(20),
    LID1 varchar(25),
    LID2 varchar(25),
    EUID1 varchar(20),
    EUID2 varchar(20),
    OPERATION varchar(20),
    SYSTEMUSER varchar(30),
    TIMESTAMP datetime,
    DELTA varbinary(max),
    SYSTEMCODE varchar(20),
    LID varchar(25),
    EUID varchar(20),
    CONSTRAINT PK_TRANSACTION PRIMARY KEY(TRANSACTIONNUMBER))
GO	

ALTER TABLE SBYN_TRANSACTION ADD CONSTRAINT AK_TRANSACTION UNIQUE (EUID, EUID2, TRANSACTIONNUMBER)
GO

CREATE TABLE SBYN_ASSUMEDMATCH (
    ASSUMEDMATCHID varchar(20),
    EUID varchar(20),
    SYSTEMCODE varchar(20),
	LID varchar(25),
    WEIGHT varchar(20),
    TRANSACTIONNUMBER varchar(20),
    CONSTRAINT PK_ASSUMEDMATCH PRIMARY KEY (ASSUMEDMATCHID))
GO    
    

ALTER TABLE SBYN_ASSUMEDMATCH ADD CONSTRAINT FK_AM_TRANSACTIONNUMBER FOREIGN KEY (TRANSACTIONNUMBER) REFERENCES SBYN_TRANSACTION(TRANSACTIONNUMBER)
GO

CREATE TABLE SBYN_POTENTIALDUPLICATES (
    POTENTIALDUPLICATEID varchar(20),
    WEIGHT varchar(20),
    TYPE varchar(15),
    DESCRIPTION varchar(120),
    STATUS varchar(15),
    HIGHMATCHFLAG varchar(15),
    RESOLVEDUSER varchar(30),
    RESOLVEDDATE datetime,
    RESOLVEDCOMMENT varchar(120),
    EUID2 varchar(20),
    TRANSACTIONNUMBER varchar(20),
    EUID1 varchar(20),
    CONSTRAINT PK_POTENTIALDUPLICATES PRIMARY KEY(POTENTIALDUPLICATEID))
GO	

CREATE TABLE SBYN_AUDIT (
    AUDIT_ID varchar(20) NOT NULL,
    PRIMARY_OBJECT_TYPE varchar(20) ,
    EUID varchar(20) ,
    EUID_AUX varchar(20),
    OPERATION varchar(32) NOT NULL,
    DETAIL varchar(120),
    CREATE_DATE datetime NOT NULL,
    CREATE_BY varchar(20) NOT NULL,
    CONSTRAINT PK_SBYN_AUDIT PRIMARY KEY(AUDIT_ID))
GO	


CREATE TABLE SBYN_MERGE (
    MERGE_ID varchar(20) NOT NULL,
    KEPT_EUID varchar(20) NOT NULL,
    MERGED_EUID varchar(20),
    MERGE_TRANSACTIONNUM varchar(20) NOT NULL,
    UNMERGE_TRANSACTIONNUM varchar(20),
    CONSTRAINT PK_SBYN_MERGE PRIMARY KEY(MERGE_ID))
GO    

ALTER TABLE SBYN_MERGE ADD CONSTRAINT FK_SBYN_MERGE FOREIGN KEY (KEPT_EUID, MERGED_EUID, MERGE_TRANSACTIONNUM) REFERENCES SBYN_TRANSACTION(EUID, EUID2, TRANSACTIONNUMBER)
GO

CREATE TABLE SBYN_APPL
(
    APPL_ID                  numeric(10)            NOT NULL,
    CODE                     varchar(8)             NOT NULL,
    DESCR                    varchar(30)            NOT NULL,
    READ_ONLY                char(1)                DEFAULT 'N' NOT NULL
        CONSTRAINT CHK_SBYN_APPL CHECK (READ_ONLY IN ('Y','N')),
    CREATE_DATE              datetime               NOT NULL,
    CREATE_USERID            varchar(20)            NOT NULL,
    CONSTRAINT PK_UP_SBYN_APPL PRIMARY KEY (APPL_ID)
)
GO

CREATE UNIQUE INDEX SBYN_APPL_IDX1 ON SBYN_APPL (CODE ASC)
GO

CREATE TABLE SBYN_COMMON_HEADER
(
    COMMON_HEADER_ID         numeric(10)            NOT NULL,
    APPL_ID                  numeric(10)            NOT NULL,
    CODE                     varchar(8)             NOT NULL,
    DESCR                    varchar(50)            NOT NULL,
    READ_ONLY                char(1)                DEFAULT 'N' NOT NULL,
    MAX_INPUT_LEN            numeric(10)            DEFAULT 1 NOT NULL,
    TYP_TABLE_CODE           varchar(3)             NOT NULL,
    CREATE_DATE              datetime               NOT NULL,
    CREATE_USERID            varchar(20)            NOT NULL,
    CONSTRAINT PK_SBYN_COMMON_HEADER PRIMARY KEY (COMMON_HEADER_ID)
)
GO

CREATE INDEX FK_SBYN_COMMON_HEADER ON SBYN_COMMON_HEADER (APPL_ID ASC)
GO
CREATE UNIQUE INDEX SBYN_COMMOM_HEADER_IDX1 ON SBYN_COMMON_HEADER (APPL_ID ASC, CODE ASC)
GO

CREATE TABLE SBYN_COMMON_DETAIL
(
    COMMON_DETAIL_ID         numeric(10)            NOT NULL
        CONSTRAINT CHK_COMMON_DETAIL_ID CHECK (COMMON_DETAIL_ID >= 0),
    COMMON_HEADER_ID         numeric(10)            NOT NULL,
    CODE                     varchar(20)            NOT NULL,
    DESCR                    varchar(50)            NOT NULL,
    READ_ONLY                char(1)                DEFAULT 'N' NOT NULL
        CONSTRAINT CHK_SBYN_COMMON_DETAIL CHECK (READ_ONLY IN ('Y','N')),
    CREATE_DATE              datetime               NOT NULL,
    CREATE_USERID            varchar(20)            NOT NULL,
    CONSTRAINT PK_SBYN_COMMON_DETAIL PRIMARY KEY (COMMON_DETAIL_ID)
)
GO

CREATE UNIQUE INDEX SBYN_COMMOM_DETAIL_IDX1 ON SBYN_COMMON_DETAIL (COMMON_HEADER_ID ASC, CODE ASC)
GO

ALTER TABLE SBYN_COMMON_DETAIL
    ADD CONSTRAINT FK_COMM_DET_COMM_HEAD FOREIGN KEY  (COMMON_HEADER_ID)
       REFERENCES SBYN_COMMON_HEADER (COMMON_HEADER_ID)
GO

CREATE INDEX SBYN_ENTERPRISE1 on SBYN_ENTERPRISE (EUID ASC)
GO
CREATE INDEX SBYN_TRANSACTION1 on SBYN_TRANSACTION (TIMESTAMP ASC)
GO
CREATE INDEX SBYN_TRANSACTION2 on SBYN_TRANSACTION (OPERATION ASC)
GO
CREATE INDEX SBYN_TRANSACTION3 on SBYN_TRANSACTION (TIMESTAMP ASC, TRANSACTIONNUMBER ASC)
GO
CREATE INDEX SBYN_ASSUMEDMATCH1 on SBYN_ASSUMEDMATCH (EUID ASC)
GO
CREATE INDEX SBYN_POTENTIALDUPLICATES1 on SBYN_POTENTIALDUPLICATES (EUID1 ASC)
GO
CREATE INDEX SBYN_POTENTIALDUPLICATES2 on SBYN_POTENTIALDUPLICATES (EUID2 ASC)
GO
CREATE INDEX SBYN_AUDIT1 on SBYN_AUDIT (EUID ASC)
GO
CREATE INDEX SBYN_AUDIT2 on SBYN_AUDIT (CREATE_DATE ASC)
GO
CREATE INDEX SBYN_MERGE1 on SBYN_MERGE (KEPT_EUID ASC)
GO

CREATE TABLE SBYN_PERSON (
	SYSTEMCODE varchar(20),
	LID varchar(25),
	PERSONID varchar(20),
	PERSONCATCODE varchar(8),
	LASTNAME varchar(40),
	FIRSTNAME varchar(40),
	MIDDLENAME varchar(30),
	SUFFIX varchar(10),
	TITLE varchar(8),
	DOB datetime,
	DEATH varchar(1),
	GENDER varchar(8),
	MSTATUS varchar(8),
	SSN varchar(16),
	RACE varchar(8),
	ETHNIC varchar(8),
	RELIGION varchar(8),
	LANGUAGE varchar(8),
	SPOUSENAME varchar(100),
	MOTHERNAME varchar(100),
	MOTHERMN varchar(40),
	FATHERNAME varchar(100),
	MAIDEN varchar(40),
	POBCITY varchar(30),
	POBSTATE varchar(10),
	POBCOUNTRY varchar(20),
	VIPFLAG varchar(8),
	VETSTATUS varchar(8),
	FNAMEPHONETICCODE varchar(8),
	LNAMEPHONETICCODE varchar(8),
	MNAMEPHONETICCODE varchar(8),
	MOTHERMNPHONETICCODE varchar(8),
	MAIDENPHONETICCODE varchar(8),
	SPOUSEPHONETICCODE varchar(8),
	MOTHERPHONETICCODE varchar(8),
	FATHERPHONETICCODE varchar(8),
	DRIVERSLICENSE varchar(20),
	DRIVERSLICENSEST varchar(10),
	DOD datetime,
	DEATHCERTIFICATE varchar(10),
	NATIONALITY varchar(8),
	CITIZENSHIP varchar(8),
	PENSIONNO varchar(15),
	PENSIONEXPDATE datetime,
	REPATRIATIONNO varchar(16),
	DISTRICTOFRESIDENCE varchar(8),
	LGACODE varchar(4),
	MILITARYBRANCH varchar(4),
	MILITARYRANK varchar(4),
	MILITARYSTATUS varchar(4),
	DUMMYDATE datetime,
	CLASS1 varchar(20),
	CLASS2 varchar(20),
	CLASS3 varchar(20),
	CLASS4 varchar(20),
	CLASS5 varchar(20),
	STRING1 varchar(40),
	STRING2 varchar(40),
	STRING3 varchar(40),
	STRING4 varchar(40),
	STRING5 varchar(40),
	STRING6 varchar(40),
	STRING7 varchar(100),
	STRING8 varchar(100),
	STRING9 varchar(100),
	STRING10 varchar(255),
	DATE1 datetime,
	DATE2 datetime,
	DATE3 datetime,
	DATE4 datetime,
	DATE5 datetime,
	STDFIRSTNAME varchar(40),
	STDLASTNAME varchar(40),
	STDMIDDLENAME varchar(30),
    CONSTRAINT PK_PERSON PRIMARY KEY (PERSONID))
GO		

ALTER TABLE SBYN_PERSON ADD CONSTRAINT FK_PERSON_SYSTEMCODE_LID FOREIGN KEY (SYSTEMCODE, LID) REFERENCES SBYN_SYSTEMOBJECT(SYSTEMCODE, LID)
GO
ALTER TABLE SBYN_PERSON ADD CONSTRAINT U_PERSON UNIQUE (SYSTEMCODE, LID)
GO

CREATE TABLE SBYN_PERSONSBR (
	EUID varchar(20),
	PERSONID varchar(20),
	PERSONCATCODE varchar(8),
	LASTNAME varchar(40),
	FIRSTNAME varchar(40),
	MIDDLENAME varchar(30),
	SUFFIX varchar(10),
	TITLE varchar(8),
	DOB datetime,
	DEATH varchar(1),
	GENDER varchar(8),
	MSTATUS varchar(8),
	SSN varchar(16),
	RACE varchar(8),
	ETHNIC varchar(8),
	RELIGION varchar(8),
	LANGUAGE varchar(8),
	SPOUSENAME varchar(100),
	MOTHERNAME varchar(100),
	MOTHERMN varchar(40),
	FATHERNAME varchar(100),
	MAIDEN varchar(40),
	POBCITY varchar(30),
	POBSTATE varchar(10),
	POBCOUNTRY varchar(20),
	VIPFLAG varchar(8),
	VETSTATUS varchar(8),
	FNAMEPHONETICCODE varchar(8),
	LNAMEPHONETICCODE varchar(8),
	MNAMEPHONETICCODE varchar(8),
	MOTHERMNPHONETICCODE varchar(8),
	MAIDENPHONETICCODE varchar(8),
	SPOUSEPHONETICCODE varchar(8),
	MOTHERPHONETICCODE varchar(8),
	FATHERPHONETICCODE varchar(8),
	DRIVERSLICENSE varchar(20),
	DRIVERSLICENSEST varchar(10),
	DOD datetime,
	DEATHCERTIFICATE varchar(10),
	NATIONALITY varchar(8),
	CITIZENSHIP varchar(8),
	PENSIONNO varchar(15),
	PENSIONEXPDATE datetime,
	REPATRIATIONNO varchar(16),
	DISTRICTOFRESIDENCE varchar(8),
	LGACODE varchar(4),
	MILITARYBRANCH varchar(4),
	MILITARYRANK varchar(4),
	MILITARYSTATUS varchar(4),
	DUMMYDATE datetime,
	CLASS1 varchar(20),
	CLASS2 varchar(20),
	CLASS3 varchar(20),
	CLASS4 varchar(20),
	CLASS5 varchar(20),
	STRING1 varchar(40),
	STRING2 varchar(40),
	STRING3 varchar(40),
	STRING4 varchar(40),
	STRING5 varchar(40),
	STRING6 varchar(40),
	STRING7 varchar(100),
	STRING8 varchar(100),
	STRING9 varchar(100),
	STRING10 varchar(255),
	DATE1 datetime,
	DATE2 datetime,
	DATE3 datetime,
	DATE4 datetime,
	DATE5 datetime,
	STDFIRSTNAME varchar(40),
	STDLASTNAME varchar(40),
	STDMIDDLENAME varchar(30),
    CONSTRAINT PK_PERSONSBR PRIMARY KEY (PERSONID))
GO		
	
ALTER TABLE SBYN_PERSONSBR ADD CONSTRAINT FK_PERSONSBR_EUID FOREIGN KEY (EUID) REFERENCES SBYN_SYSTEMSBR(EUID)
GO
ALTER TABLE SBYN_PERSONSBR ADD CONSTRAINT U_PERSONSBR UNIQUE (EUID)
GO

CREATE TABLE SBYN_PHONE (
	PERSONID varchar(20),
	PHONEID varchar(20),
	PHONETYPE varchar(8),
	PHONE varchar(20),
	PHONEEXT varchar(6),
    CONSTRAINT PK_PHONE PRIMARY KEY (PHONEID))
GO		

ALTER TABLE SBYN_PHONE ADD CONSTRAINT FK_PHONE_PERSONID FOREIGN KEY (PERSONID) REFERENCES SBYN_PERSON(PERSONID)
GO
ALTER TABLE SBYN_PHONE ADD CONSTRAINT U_PHONE UNIQUE (PERSONID, PHONETYPE)
GO

CREATE TABLE SBYN_PHONESBR (
	PERSONID varchar(20),
	PHONEID varchar(20),
	PHONETYPE varchar(8),
	PHONE varchar(20),
	PHONEEXT varchar(6),
    CONSTRAINT PK_PHONESBR PRIMARY KEY (PHONEID))
GO

ALTER TABLE SBYN_PHONESBR ADD CONSTRAINT FK_PHONESBR_PERSONID FOREIGN KEY (PERSONID) REFERENCES SBYN_PERSONSBR(PERSONID)
GO
ALTER TABLE SBYN_PHONESBR ADD CONSTRAINT U_PHONESBR UNIQUE (PERSONID, PHONETYPE)
GO

CREATE TABLE SBYN_ALIAS (
	PERSONID varchar(20),
	ALIASID varchar(20),
	LASTNAME varchar(40),
	FIRSTNAME varchar(40),
	MIDDLENAME varchar(30),
	LNAMEPHONETICCODE varchar(8),
	FNAMEPHONETICCODE varchar(8),
	MNAMEPHONETICCODE varchar(8),
	STDFIRSTNAME varchar(40),
	STDLASTNAME varchar(40),
	STDMIDDLENAME varchar(30),
	MYCHARFIELD char,
	MYBOOLEANFIELD smallint,
    CONSTRAINT PK_ALIAS PRIMARY KEY (ALIASID))
GO		

ALTER TABLE SBYN_ALIAS ADD CONSTRAINT FK_ALIAS_PERSONID FOREIGN KEY (PERSONID) REFERENCES SBYN_PERSON(PERSONID)
GO
ALTER TABLE SBYN_ALIAS ADD CONSTRAINT U_ALIAS UNIQUE (PERSONID, LASTNAME, FIRSTNAME, MIDDLENAME)
GO

CREATE TABLE SBYN_ALIASSBR (
	PERSONID varchar(20),
	ALIASID varchar(20),
	LASTNAME varchar(40),
	FIRSTNAME varchar(40),
	MIDDLENAME varchar(30),
	LNAMEPHONETICCODE varchar(8),
	FNAMEPHONETICCODE varchar(8),
	MNAMEPHONETICCODE varchar(8),
	STDFIRSTNAME varchar(40),
	STDLASTNAME varchar(40),
	STDMIDDLENAME varchar(30),
	MYCHARFIELD char,
	MYBOOLEANFIELD smallint,
    CONSTRAINT PK_ALIASSBR PRIMARY KEY (ALIASID))
GO

ALTER TABLE SBYN_ALIASSBR ADD CONSTRAINT FK_ALIASSBR_PERSONID FOREIGN KEY (PERSONID) REFERENCES SBYN_PERSONSBR(PERSONID)
GO
ALTER TABLE SBYN_ALIASSBR ADD CONSTRAINT U_ALIASSBR UNIQUE (PERSONID, LASTNAME, FIRSTNAME, MIDDLENAME)
GO

CREATE TABLE SBYN_ADDRESS (
	PERSONID varchar(20),
	ADDRESSID varchar(20),
	ADDRESSTYPE varchar(8),
	ADDRESSLINE1 varchar(40),
	ADDRESSLINE2 varchar(40),
	ADDRESSLINE3 varchar(40),
	ADDRESSLINE4 varchar(40),
	CITY varchar(30),
	STATECODE varchar(10),
	POSTALCODE varchar(8),
	POSTALCODEEXT varchar(4),
	COUNTY varchar(20),
	COUNTRYCODE varchar(20),
	HOUSENUMBER varchar(10),
	STREETDIR varchar(5),
	STREETNAME varchar(40),
	STREETNAMEPHONETICCODE varchar(8),
	STREETTYPE varchar(5),
    CONSTRAINT PK_ADDRESS PRIMARY KEY (ADDRESSID))
GO		

ALTER TABLE SBYN_ADDRESS ADD CONSTRAINT FK_ADDRESS_PERSONID FOREIGN KEY (PERSONID) REFERENCES SBYN_PERSON(PERSONID)
GO
ALTER TABLE SBYN_ADDRESS ADD CONSTRAINT U_ADDRESS UNIQUE (PERSONID, ADDRESSTYPE)
GO

CREATE TABLE SBYN_ADDRESSSBR (
	PERSONID varchar(20),
	ADDRESSID varchar(20),
	ADDRESSTYPE varchar(8),
	ADDRESSLINE1 varchar(40),
	ADDRESSLINE2 varchar(40),
	ADDRESSLINE3 varchar(40),
	ADDRESSLINE4 varchar(40),
	CITY varchar(30),
	STATECODE varchar(10),
	POSTALCODE varchar(8),
	POSTALCODEEXT varchar(4),
	COUNTY varchar(20),
	COUNTRYCODE varchar(20),
	HOUSENUMBER varchar(10),
	STREETDIR varchar(5),
	STREETNAME varchar(40),
	STREETNAMEPHONETICCODE varchar(8),
	STREETTYPE varchar(5),
    CONSTRAINT PK_ADDRESSSBR PRIMARY KEY (ADDRESSID))
GO

ALTER TABLE SBYN_ADDRESSSBR ADD CONSTRAINT FK_ADDRESSSBR_PERSONID FOREIGN KEY (PERSONID) REFERENCES SBYN_PERSONSBR(PERSONID)
GO
ALTER TABLE SBYN_ADDRESSSBR ADD CONSTRAINT U_ADDRESSSBR UNIQUE (PERSONID, ADDRESSTYPE)
GO

CREATE TABLE SBYN_AUXID (
	PERSONID varchar(20),
	AUXIDID varchar(20),
	AUXIDDEF varchar(10),
	ID varchar(40),
    CONSTRAINT PK_AUXID PRIMARY KEY (AUXIDID))
GO		

ALTER TABLE SBYN_AUXID ADD CONSTRAINT FK_AUXID_PERSONID FOREIGN KEY (PERSONID) REFERENCES SBYN_PERSON(PERSONID)
GO
ALTER TABLE SBYN_AUXID ADD CONSTRAINT U_AUXID UNIQUE (PERSONID, AUXIDDEF, ID)
GO

CREATE TABLE SBYN_AUXIDSBR (
	PERSONID varchar(20),
	AUXIDID varchar(20),
	AUXIDDEF varchar(10),
	ID varchar(40),
    CONSTRAINT PK_AUXIDSBR PRIMARY KEY (AUXIDID))
GO

ALTER TABLE SBYN_AUXIDSBR ADD CONSTRAINT FK_AUXIDSBR_PERSONID FOREIGN KEY (PERSONID) REFERENCES SBYN_PERSONSBR(PERSONID)
GO
ALTER TABLE SBYN_AUXIDSBR ADD CONSTRAINT U_AUXIDSBR UNIQUE (PERSONID, AUXIDDEF, ID)
GO

CREATE TABLE SBYN_COMMENT (
	PERSONID varchar(20),
	COMMENTID varchar(20),
	COMMENTCODE varchar(8),
	ENTERDATE datetime,
	COMMENTTEXT varchar(1000),
    CONSTRAINT PK_COMMENT PRIMARY KEY (COMMENTID))
GO		

ALTER TABLE SBYN_COMMENT ADD CONSTRAINT FK_COMMENT_PERSONID FOREIGN KEY (PERSONID) REFERENCES SBYN_PERSON(PERSONID)
GO
ALTER TABLE SBYN_COMMENT ADD CONSTRAINT U_COMMENT UNIQUE (PERSONID, COMMENTCODE)
GO

CREATE TABLE SBYN_COMMENTSBR (
	PERSONID varchar(20),
	COMMENTID varchar(20),
	COMMENTCODE varchar(8),
	ENTERDATE datetime,
	COMMENTTEXT varchar(1000),
    CONSTRAINT PK_COMMENTSBR PRIMARY KEY (COMMENTID))
GO

ALTER TABLE SBYN_COMMENTSBR ADD CONSTRAINT FK_COMMENTSBR_PERSONID FOREIGN KEY (PERSONID) REFERENCES SBYN_PERSONSBR(PERSONID)
GO
ALTER TABLE SBYN_COMMENTSBR ADD CONSTRAINT U_COMMENTSBR UNIQUE (PERSONID, COMMENTCODE)
GO

CREATE TABLE SBYN_SEQ_TABLE (
	SEQ_NAME varchar(20),
	SEQ_COUNT numeric(38))
GO	

ALTER TABLE SBYN_SEQ_TABLE ADD CONSTRAINT U_SEQ_NAME UNIQUE (SEQ_NAME)
GO



CREATE PROCEDURE SEQMGR
    @seq_name_in varchar(30), 
    @chunk_size_in int,
    @seq_num_out int output
AS
BEGIN
    -- SET NOCOUNT ON added to prevent extra result sets from
    -- interfering with SELECT statements.
    SET NOCOUNT ON

    -- Update sequence number
    update SBYN_SEQ_TABLE set SEQ_COUNT = SEQ_COUNT + @chunk_size_in where SEQ_NAME = @seq_name_in

    -- if error return -1
    if @@error = 0
        select @seq_num_out = SEQ_COUNT - @chunk_size_in from SBYN_SEQ_TABLE where SEQ_NAME = @seq_name_in
    else
	select @seq_num_out = -1
END
GO

INSERT INTO SBYN_SEQ_TABLE VALUES ('EUID', 0)
GO
INSERT INTO SBYN_SEQ_TABLE VALUES ('POTENTIALDUPLICATE', 0)
GO
INSERT INTO SBYN_SEQ_TABLE VALUES ('TRANSACTIONNUMBER', 0)
GO
INSERT INTO SBYN_SEQ_TABLE VALUES ('ASSUMEDMATCH', 0)
GO
INSERT INTO SBYN_SEQ_TABLE VALUES ('AUDIT', 0)
GO
INSERT INTO SBYN_SEQ_TABLE VALUES ('MERGE', 0)
GO
INSERT INTO SBYN_SEQ_TABLE VALUES ('SBYN_APPL', 2)
GO
INSERT INTO SBYN_SEQ_TABLE VALUES ('SBYN_COMMON_HEADER', 1)
GO
INSERT INTO SBYN_SEQ_TABLE VALUES ('SBYN_COMMON_DETAIL', 1)
GO
INSERT INTO SBYN_SEQ_TABLE VALUES ('PHONE', 0)
GO
INSERT INTO SBYN_SEQ_TABLE VALUES ('PHONESBR', 0)
GO
INSERT INTO SBYN_SEQ_TABLE VALUES ('ALIAS', 0)
GO
INSERT INTO SBYN_SEQ_TABLE VALUES ('ALIASSBR', 0)
GO
INSERT INTO SBYN_SEQ_TABLE VALUES ('ADDRESS', 0)
GO
INSERT INTO SBYN_SEQ_TABLE VALUES ('ADDRESSSBR', 0)
GO
INSERT INTO SBYN_SEQ_TABLE VALUES ('AUXID', 0)
GO
INSERT INTO SBYN_SEQ_TABLE VALUES ('AUXIDSBR', 0)
GO
INSERT INTO SBYN_SEQ_TABLE VALUES ('COMMENT', 0)
GO
INSERT INTO SBYN_SEQ_TABLE VALUES ('COMMENTSBR', 0)
GO
INSERT INTO SBYN_SEQ_TABLE VALUES ('PERSON', 0)
GO
INSERT INTO SBYN_SEQ_TABLE VALUES ('PERSONSBR', 0)
GO

INSERT INTO SBYN_APPL (APPL_ID, CODE, DESCR, READ_ONLY, CREATE_DATE, CREATE_USERID) 
VALUES (1, 'EV', 'eView5.1', 'Y', getdate(), user)
GO

COMMIT
