CREATE INDEX SBYN_PERSONSBR1 ON SBYN_AUSPATIENT (LASTNAME_PHON ASC, FIRSTNAME_PHON ASC);

CREATE INDEX SBYN_PERSONSBR2 ON SBYN_AUSPATIENT (MEDICARENO ASC, FIRSTNAME_PHON ASC);

CREATE INDEX SBYN_PERSONSBR3 ON SBYN_AUSPATIENT (FIRSTNAME_PHON ASC, DOB ASC, GENDER ASC);

COMMIT;  