/*
 * TabEDMPropertiesJPanel.java
 *
 * Created on February 12, 2008, 10:36 AM
 */

package com.sun.mdm.index.project.ui.wizards;

/**
 *
 */
public class TabEDMPropertiesJPanel extends javax.swing.JPanel {
    
    /** Creates new form TabEDMPropertiesJPanel */
    public TabEDMPropertiesJPanel(String displayName, String inputMask, String valueMask,
                                    boolean searchScreen, boolean searchResult, 
                                    boolean generateReport, String searchRequired) {
        initComponents();
        this.txtDisplayName.setText(displayName);
        this.txtInputMask.setText(inputMask);
        this.txtValueMask.setText(valueMask);
        this.jComboBoxSearchResult.setSelectedItem(searchResult ? "true" : "false");
        this.jComboBoxReport.setSelectedItem(generateReport ? "true" : "false");
        this.jComboBoxSearchRequired.setSelectedItem(searchRequired);
        this.jComboBoxSearchRequired.setEnabled(searchScreen);
        
        jComboBoxSearchScreen.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    if (jComboBoxSearchScreen.getSelectedItem().equals("true")) {
                        jComboBoxSearchRequired.setEnabled(true);
                    } else {
                    jComboBoxSearchRequired.setSelectedItem("false");
                    jComboBoxSearchRequired.setEnabled(false);
                    }
                }
            });
        this.jComboBoxSearchScreen.setSelectedItem(searchScreen ? "true" : "false");
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelDisplayName = new javax.swing.JLabel();
        jLabelInputMask = new javax.swing.JLabel();
        jLabelValueMask = new javax.swing.JLabel();
        jLabelSearchScreen = new javax.swing.JLabel();
        jLabelSearchRequired = new javax.swing.JLabel();
        jLabelSearchResult = new javax.swing.JLabel();
        jLabelGenerateReport = new javax.swing.JLabel();
        txtDisplayName = new javax.swing.JTextField();
        txtInputMask = new javax.swing.JTextField();
        txtValueMask = new javax.swing.JTextField();
        jComboBoxSearchRequired = new javax.swing.JComboBox();
        jComboBoxSearchScreen = new javax.swing.JComboBox();
        jComboBoxSearchResult = new javax.swing.JComboBox();
        jComboBoxReport = new javax.swing.JComboBox();

        jLabelDisplayName.setText(org.openide.util.NbBundle.getMessage(TabEDMPropertiesJPanel.class, "MSG_DisplayName")); // NOI18N

        jLabelInputMask.setText(org.openide.util.NbBundle.getMessage(TabEDMPropertiesJPanel.class, "MSG_InputMask")); // NOI18N

        jLabelValueMask.setText(org.openide.util.NbBundle.getMessage(TabEDMPropertiesJPanel.class, "MSG_ValueMask")); // NOI18N

        jLabelSearchScreen.setText(org.openide.util.NbBundle.getMessage(TabEDMPropertiesJPanel.class, "MSG_SearchScreen")); // NOI18N
        jLabelSearchScreen.setMaximumSize(new java.awt.Dimension(59, 14));
        jLabelSearchScreen.setMinimumSize(new java.awt.Dimension(59, 14));

        jLabelSearchRequired.setText(org.openide.util.NbBundle.getMessage(TabEDMPropertiesJPanel.class, "MSG_SearchRequired")); // NOI18N

        jLabelSearchResult.setText(org.openide.util.NbBundle.getMessage(TabEDMPropertiesJPanel.class, "MSG_SearchResult")); // NOI18N

        jLabelGenerateReport.setText(org.openide.util.NbBundle.getMessage(TabEDMPropertiesJPanel.class, "MSG_GenerateReport")); // NOI18N

        jComboBoxSearchRequired.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "true", "false", "oneof" }));
        jComboBoxSearchRequired.setPreferredSize(new java.awt.Dimension(48, 20));

        jComboBoxSearchScreen.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "true", "false" }));

        jComboBoxSearchResult.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "true", "false" }));

        jComboBoxReport.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "true", "false" }));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabelSearchScreen, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                    .add(jLabelSearchRequired, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                    .add(jLabelSearchResult, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                    .add(jLabelInputMask, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                    .add(jLabelGenerateReport, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                    .add(jLabelValueMask, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                    .add(jLabelDisplayName, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(txtInputMask, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                    .add(txtDisplayName, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, txtValueMask, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                        .add(jComboBoxReport, 0, 0, Short.MAX_VALUE)
                        .add(jComboBoxSearchResult, 0, 0, Short.MAX_VALUE)
                        .add(org.jdesktop.layout.GroupLayout.TRAILING, jComboBoxSearchScreen, 0, 60, Short.MAX_VALUE)
                        .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                            .add(jComboBoxSearchRequired, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(txtDisplayName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabelDisplayName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(txtInputMask, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabelInputMask, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelValueMask, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(txtValueMask, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelSearchScreen, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jComboBoxSearchScreen, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelSearchRequired, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jComboBoxSearchRequired, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 19, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelSearchResult, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jComboBoxSearchResult, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelGenerateReport, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 18, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jComboBoxReport, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(113, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBoxReport;
    private javax.swing.JComboBox jComboBoxSearchRequired;
    private javax.swing.JComboBox jComboBoxSearchResult;
    private javax.swing.JComboBox jComboBoxSearchScreen;
    private javax.swing.JLabel jLabelDisplayName;
    private javax.swing.JLabel jLabelGenerateReport;
    private javax.swing.JLabel jLabelInputMask;
    private javax.swing.JLabel jLabelSearchRequired;
    private javax.swing.JLabel jLabelSearchResult;
    private javax.swing.JLabel jLabelSearchScreen;
    private javax.swing.JLabel jLabelValueMask;
    private javax.swing.JTextField txtDisplayName;
    private javax.swing.JTextField txtInputMask;
    private javax.swing.JTextField txtValueMask;
    // End of variables declaration//GEN-END:variables
    
    private void addListeners() {
        /*
        txtDisplayName.addFocusListener(new java.awt.event.FocusListener() {
                String oldName;
                public void focusGained(java.awt.event.FocusEvent ev) {
                    oldName = txtDisplayName.getText();
                }

                public void focusLost(java.awt.event.FocusEvent ev) {
                    String newName = txtDisplayName.getText();
                }
            });
         */
        txtDisplayName.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyReleased(java.awt.event.KeyEvent evt) {
                    onTextFieldKeyReleased(evt);
                    char c = evt.getKeyChar();
                    if (c == '\n') {
                        txtInputMask.requestFocus();
                    }
                }
                public void keyTyped(java.awt.event.KeyEvent evt) {
                    onTextFieldKeyTyped(evt);
                }
        });
        
        txtInputMask.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyReleased(java.awt.event.KeyEvent evt) {
                    onTextFieldKeyReleased(evt);
                    char c = evt.getKeyChar();
                    if (c == '\n') {
                        txtValueMask.requestFocus();
                    }
                }
                public void keyTyped(java.awt.event.KeyEvent evt) {
                    onTextFieldKeyTyped(evt);
                }
        });
        
        txtValueMask.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyReleased(java.awt.event.KeyEvent evt) {
                    onTextFieldKeyReleased(evt);
                    char c = evt.getKeyChar();
                    if (c == '\n') {
                        jComboBoxSearchScreen.requestFocus();
                    }
                }
                public void keyTyped(java.awt.event.KeyEvent evt) {
                    onTextFieldKeyTyped(evt);
                }
        });
                
        this.jComboBoxSearchRequired.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent e) {
            }
        });
    }
    
    /*
     * Check if char entered will cause xml to break
     * such as < > /
     */
    private void onTextFieldKeyTyped(java.awt.event.KeyEvent evt) {
        char c = evt.getKeyChar();
        if (!Character.isLetterOrDigit(c) && 
                c != '-' && c != '_'&& 
                c != '(' && c != ')' && 
                c != '[' && c != ']' && 
                c != '{' && c != '}' && 
                c != '\b' && c != '\n') {
            java.awt.Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }
    }
    
    private void onTextFieldKeyReleased(java.awt.event.KeyEvent evt) {
    }

    /**
     *@return DisplayName
     */
    public String getDisplayName() {
        return txtDisplayName.getText();
    }

    /**
     *@return InputMask
     */
    public String getInputMask() {
        return txtInputMask.getText();
    }

    /**
     *@return ValueMask
     */
    public String getValueMask() {
        return txtValueMask.getText();
    }

    /**
     *@param order gui display order
     */
    public void setDisplayOrder(int order) {
        //mDisplayOrder = order;
    }

    /**
     *@return DisplayOrder
     */
    public int getDisplayOrder() {
        return 0;
    }

    /**
     *@return UsedInSearchScreen
     */
    public boolean getUsedInSearchScreen() {
        return jComboBoxSearchScreen.getSelectedItem().equals("true");
    }

    /**
     *@return SearchRequired
     */
    public String getSearchRequired() {
        return this.jComboBoxSearchRequired.getSelectedItem().toString();
    }

    /**
     *@return DisplayedInSearchResult
     */
    public boolean getDisplayedInSearchResult() {
        return jComboBoxSearchResult.getSelectedItem().equals("true");
    }

    /**
     *@return GenerateReport
     */
    public boolean getGenerateReport() {
        return jComboBoxReport.getSelectedItem().equals("true");
    }
    
    /**
     * setDisplayName
     * @param oldName
     * @param newName
     */
    public void updateDefaultDisplayName(String oldName, String newName) {
        if (this.txtDisplayName.getText().equals(oldName)) {
            this.txtDisplayName.setText(newName);
        }
    }
}
