CREATE INDEX SBYN_PATIENTBR1 ON SBYN_NAME (FAMILYNAME_PHON ASC, GIVENNAME_PHON ASC);

CREATE INDEX SBYN_PATIENTSBR2 ON SBYN_UKPATIENT (DOB ASC, GENDER ASC);

CREATE INDEX SBYN_PATIENTSBR3 ON SBYN_ADDRESS (POSTCODE ASC);

COMMIT;  