CREATE INDEX SBYN_PERSONSBR1 ON SBYN_PERSONSBR (LNAMEPHONETICCODE ASC, FNAMEPHONETICCODE ASC);

CREATE INDEX SBYN_PERSONSBR2 ON SBYN_PERSONSBR (FNAMEPHONETICCODE ASC, DOB ASC);

CREATE INDEX SBYN_PERSONSBR3 ON SBYN_PERSONSBR (SSN ASC);

CREATE INDEX SBYN_PERSONSBR4 ON SBYN_PERSONSBR (LNAMEPHONETICCODE ASC, MOTHERMNPHONETICCODE ASC);

CREATE INDEX SBYN_ALIASSBR1 ON SBYN_ALIASSBR (LNAMEPHONETICCODE ASC, FNAMEPHONETICCODE ASC);

CREATE INDEX SBYN_ADDRESSSBR1 ON SBYN_ADDRESSSBR (STREETNAMEPHONETICCODE ASC, HOUSENUMBER ASC);

COMMIT;  