CREATE TABLE SBYN_SYSTEMS
(
    SYSTEMCODE		VARCHAR2(20)	NOT NULL,
    DESCRIPTION		VARCHAR2(50)	NOT NULL,
    STATUS		CHAR		NOT NULL,
    ID_LENGTH		INTEGER		NOT NULL,
    FORMAT		VARCHAR2(60)	NULL    ,
    INPUT_MASK		VARCHAR2(60)	NULL    ,
    VALUE_MASK		VARCHAR2(60)	NULL    ,
    CREATE_DATE		DATE		NOT NULL,
    CREATE_USERID	VARCHAR2(20)	NOT NULL,
    UPDATE_DATE		DATE		NULL    ,
    UPDATE_USERID	VARCHAR2(20)	NULL    ,
    CONSTRAINT PK_SBYN_SYSTEM PRIMARY KEY (SYSTEMCODE)
        USING INDEX
);

CREATE TABLE SBYN_USER_CODE
(
    CODE_LIST		VARCHAR2(20)	NOT NULL,
    CODE			VARCHAR2(20)	NOT NULL,
    DESCR			VARCHAR2(50)	NOT NULL,
    FORMAT			VARCHAR2(60)	NULL    ,
    INPUT_MASK		VARCHAR2(60)	NULL    ,
    VALUE_MASK		VARCHAR2(60)	NULL    ,
    CONSTRAINT PK_SBYN_USER_CODE PRIMARY KEY (CODE_LIST, CODE)
        USING INDEX
);

CREATE TABLE SBYN_SYSTEMOBJECT (
	SYSTEMCODE VARCHAR2(20),
	LID VARCHAR2(25),
	CHILDTYPE VARCHAR2(20),
	CREATEUSER VARCHAR2(30),
	CREATEFUNCTION VARCHAR2(20),
	CREATEDATE DATE,
	UPDATEUSER VARCHAR2(30),
	UPDATEFUNCTION VARCHAR2(20),
	UPDATEDATE DATE,
	STATUS VARCHAR2(15));

ALTER TABLE SBYN_SYSTEMOBJECT ADD CONSTRAINT PK_SBYNSYSTEMOBJECT PRIMARY KEY (SYSTEMCODE, LID);
ALTER TABLE SBYN_SYSTEMOBJECT ADD CONSTRAINT FK_SYSTEMOBJECT_SYSTEMCODE FOREIGN KEY (SYSTEMCODE) REFERENCES SBYN_SYSTEMS(SYSTEMCODE);

CREATE TABLE SBYN_SYSTEMSBR (
	EUID VARCHAR2(20),
	CHILDTYPE VARCHAR2(20),
	CREATESYSTEM VARCHAR2(20),
	CREATEUSER VARCHAR2(30),
	CREATEFUNCTION VARCHAR2(20),
	CREATEDATE DATE,
	UPDATESYSTEM VARCHAR2(20),
	UPDATEUSER VARCHAR2(30),
	UPDATEFUNCTION VARCHAR2(20),
	UPDATEDATE DATE,
	STATUS VARCHAR2(15),
      REVISIONNUMBER NUMBER(38));

ALTER TABLE SBYN_SYSTEMSBR ADD CONSTRAINT PK_SBYNSYSTEMSBR PRIMARY KEY (EUID);

CREATE TABLE SBYN_OVERWRITE (
	EUID VARCHAR2(20),
	PATH VARCHAR2(200),
	TYPE VARCHAR2(20),
	INTEGERDATA NUMBER(38),
	BOOLEANDATA NUMBER(38),
	STRINGDATA VARCHAR2(200),
	BYTEDATA CHAR(2),
	LONGDATA LONG,
	DATEDATA DATE,
	FLOATDATA NUMBER(38, 4),
	TIMESTAMPDATA DATE);

ALTER TABLE SBYN_OVERWRITE ADD CONSTRAINT FK_SYSTEMSBR_EUID FOREIGN KEY (EUID) REFERENCES SBYN_SYSTEMSBR(EUID) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE SBYN_OVERWRITE ADD CONSTRAINT PK_SBROVERWRITE PRIMARY KEY (EUID, PATH);

CREATE TABLE SBYN_ENTERPRISE (
	SYSTEMCODE VARCHAR2(20),
	LID VARCHAR2(25),
	EUID VARCHAR2(20));

ALTER TABLE SBYN_ENTERPRISE ADD CONSTRAINT FK_ENTERPRISE_SYSTEMCODE_LID FOREIGN KEY (SYSTEMCODE, LID) REFERENCES SBYN_SYSTEMOBJECT(SYSTEMCODE, LID) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE SBYN_ENTERPRISE ADD CONSTRAINT FK_ENTERPRISE_EUID FOREIGN KEY (EUID) REFERENCES SBYN_SYSTEMSBR(EUID) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE SBYN_ENTERPRISE ADD CONSTRAINT PK_ENTERPRISE PRIMARY KEY (SYSTEMCODE, LID, EUID);

CREATE TABLE SBYN_TRANSACTION (
	TRANSACTIONNUMBER VARCHAR2(20),
	LID1 VARCHAR2(25),
	LID2 VARCHAR2(25),
	EUID1 VARCHAR2(20),
	EUID2 VARCHAR2(20),
	FUNCTION VARCHAR2(20),
	SYSTEMUSER VARCHAR2(30),
	TIMESTAMP TIMESTAMP,
	DELTA BLOB,
	SYSTEMCODE VARCHAR2(20),
	LID VARCHAR2(25),
	EUID VARCHAR2(20));

ALTER TABLE SBYN_TRANSACTION ADD CONSTRAINT PK_TRANSACTION PRIMARY KEY (TRANSACTIONNUMBER);
ALTER TABLE SBYN_TRANSACTION ADD CONSTRAINT AK_TRANSACTION UNIQUE (EUID, EUID2, TRANSACTIONNUMBER);

CREATE TABLE SBYN_ASSUMEDMATCH (
    ASSUMEDMATCHID VARCHAR2(20),
    EUID VARCHAR2(20),
    SYSTEMCODE VARCHAR2(20),
	LID VARCHAR2(25),
    WEIGHT VARCHAR2(20),
    TRANSACTIONNUMBER VARCHAR(20));
    

ALTER TABLE SBYN_ASSUMEDMATCH ADD CONSTRAINT FK_AM_TRANSACTIONNUMBER FOREIGN KEY (TRANSACTIONNUMBER) REFERENCES SBYN_TRANSACTION(TRANSACTIONNUMBER);

CREATE TABLE SBYN_POTENTIALDUPLICATES (
	POTENTIALDUPLICATEID VARCHAR2(20),
	WEIGHT VARCHAR2(20),
	TYPE VARCHAR2(15),
	DESCRIPTION VARCHAR2(120),
	STATUS VARCHAR2(15),
	HIGHMATCHFLAG VARCHAR2(15),
	RESOLVEDUSER VARCHAR2(30),
	RESOLVEDDATE DATE,
	RESOLVEDCOMMENT VARCHAR2(120),
	EUID2 VARCHAR2(20),
	TRANSACTIONNUMBER VARCHAR2(20),
	EUID1 VARCHAR2(20));

ALTER TABLE SBYN_POTENTIALDUPLICATES ADD CONSTRAINT PK_POTENTIALDUPLICATES PRIMARY KEY (POTENTIALDUPLICATEID);

CREATE TABLE SBYN_AUDIT (
	AUDIT_ID VARCHAR2(20) NOT NULL,
	PRIMARY_OBJECT_TYPE VARCHAR2(20) ,
	EUID VARCHAR2(20) ,
	EUID_AUX VARCHAR2(20),
	FUNCTION VARCHAR2(32) NOT NULL,
	DETAIL VARCHAR2(120),
	CREATE_DATE DATE NOT NULL,
	CREATE_BY VARCHAR2(20) NOT NULL);

ALTER TABLE SBYN_AUDIT ADD CONSTRAINT PK_SBYN_AUDIT PRIMARY KEY (AUDIT_ID);

CREATE TABLE SBYN_MERGE (
	MERGE_ID VARCHAR2(20) NOT NULL,
    KEPT_EUID VARCHAR2(20) NOT NULL,
    MERGED_EUID VARCHAR2(20),
    MERGE_TRANSACTIONNUM VARCHAR2(20) NOT NULL,
    UNMERGE_TRANSACTIONNUM VARCHAR2(20));

ALTER TABLE SBYN_MERGE ADD CONSTRAINT FK_SBYN_MERGE FOREIGN KEY (KEPT_EUID, MERGED_EUID, MERGE_TRANSACTIONNUM) REFERENCES SBYN_TRANSACTION(EUID, EUID2, TRANSACTIONNUMBER) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE SBYN_MERGE ADD CONSTRAINT PK_SBYN_MERGE PRIMARY KEY (MERGE_ID);

CREATE TABLE SBYN_APPL
(
    APPL_ID                  NUMBER(10)             NOT NULL,
    CODE                     VARCHAR2(8)            NOT NULL,
    DESCR                    VARCHAR2(30)           NOT NULL,
    READ_ONLY                CHAR(1)                DEFAULT 'N' NOT NULL
        CONSTRAINT CHK_SBYN_APPL CHECK (READ_ONLY IN ('Y','N')),
    CREATE_DATE              DATE                   NOT NULL,
    CREATE_USERID            VARCHAR2(20)           NOT NULL,
    CONSTRAINT PK_UP_SBYN_APPL PRIMARY KEY (APPL_ID)
)
;
CREATE UNIQUE INDEX SBYN_APPL_IDX1 ON SBYN_APPL (CODE ASC);

CREATE TABLE SBYN_COMMON_HEADER
(
    COMMON_HEADER_ID         NUMBER(10)             NOT NULL,
    APPL_ID                  NUMBER(10)             NOT NULL,
    CODE                     VARCHAR2(8)            NOT NULL,
    DESCR                    VARCHAR2(50)           NOT NULL,
    READ_ONLY                CHAR(1)                DEFAULT 'N' NOT NULL,
    MAX_INPUT_LEN            NUMBER(10)             DEFAULT 1 NOT NULL,
    TYP_TABLE_CODE           VARCHAR2(3)            NOT NULL,
    CREATE_DATE              DATE                   NOT NULL,
    CREATE_USERID            VARCHAR2(20)           NOT NULL,
    CONSTRAINT PK_SBYN_COMMON_HEADER PRIMARY KEY (COMMON_HEADER_ID)
)
;
CREATE INDEX FK_SBYN_COMMON_HEADER ON SBYN_COMMON_HEADER (APPL_ID ASC);
CREATE UNIQUE INDEX SBYN_COMMOM_HEADER_IDX1 ON SBYN_COMMON_HEADER (APPL_ID ASC, CODE ASC);

CREATE TABLE SBYN_COMMON_DETAIL
(
    COMMON_DETAIL_ID         NUMBER(10)             NOT NULL
        CONSTRAINT CHK_COMMON_DETAIL_ID CHECK (COMMON_DETAIL_ID >= 0),
    COMMON_HEADER_ID         NUMBER(10)             NOT NULL,
    CODE                     VARCHAR2(20)           NOT NULL,
    DESCR                    VARCHAR2(50)           NOT NULL,
    READ_ONLY                CHAR(1)                DEFAULT 'N' NOT NULL
        CONSTRAINT CHK_SBYN_COMMON_DETAIL CHECK (READ_ONLY IN ('Y','N')),
    CREATE_DATE              DATE                   NOT NULL,
    CREATE_USERID            VARCHAR2(20)           NOT NULL,
    CONSTRAINT PK_SBYN_COMMON_DETAIL PRIMARY KEY (COMMON_DETAIL_ID)
)
;
CREATE UNIQUE INDEX SBYN_COMMOM_DETAIL_IDX1 ON SBYN_COMMON_DETAIL (COMMON_HEADER_ID ASC, CODE ASC);

ALTER TABLE SBYN_COMMON_DETAIL
    ADD CONSTRAINT FK_COMM_DET_COMM_HEAD FOREIGN KEY  (COMMON_HEADER_ID)
       REFERENCES SBYN_COMMON_HEADER (COMMON_HEADER_ID)
;

CREATE INDEX SBYN_ENTERPRISE1 on SBYN_ENTERPRISE (EUID ASC);
CREATE INDEX SBYN_TRANSACTION1 on SBYN_TRANSACTION (TIMESTAMP ASC);
CREATE INDEX SBYN_TRANSACTION2 on SBYN_TRANSACTION (FUNCTION ASC);
CREATE INDEX SBYN_TRANSACTION4 on SBYN_TRANSACTION (EUID2 ASC, TIMESTAMP ASC);
CREATE INDEX SBYN_TRANSACTION3 on SBYN_TRANSACTION (TIMESTAMP ASC, TRANSACTIONNUMBER ASC);
ALTER TABLE SBYN_ASSUMEDMATCH ADD CONSTRAINT PK_ASSUMEDMATCH PRIMARY KEY (ASSUMEDMATCHID);
CREATE INDEX SBYN_ASSUMEDMATCH1 on SBYN_ASSUMEDMATCH (EUID ASC);
CREATE INDEX SBYN_ASSUMEDMATCH2 ON SBYN_ASSUMEDMATCH (TRANSACTIONNUMBER ASC);
CREATE INDEX SBYN_POTENTIALDUPLICATES1 on SBYN_POTENTIALDUPLICATES (EUID1 ASC);
CREATE INDEX SBYN_POTENTIALDUPLICATES2 on SBYN_POTENTIALDUPLICATES (EUID2 ASC);
CREATE INDEX SBYN_POTENTIALDUPLICATES3 ON SBYN_POTENTIALDUPLICATES (TRANSACTIONNUMBER ASC);
CREATE INDEX SBYN_AUDIT1 on SBYN_AUDIT (EUID ASC);
CREATE INDEX SBYN_AUDIT2 on SBYN_AUDIT (CREATE_DATE ASC);
CREATE INDEX SBYN_MERGE1 on SBYN_MERGE (KEPT_EUID ASC);

CREATE TABLE SBYN_PERSON (
	SYSTEMCODE VARCHAR2(20),
	LID VARCHAR2(25),
	PERSONID VARCHAR2(20),
	PERSONCATCODE VARCHAR2(8),
	LASTNAME VARCHAR2(40),
	FIRSTNAME VARCHAR2(40),
	MIDDLENAME VARCHAR2(30),
	SUFFIX VARCHAR2(10),
	TITLE VARCHAR2(8),
	DOB DATE,
	DEATH VARCHAR2(1),
	GENDER VARCHAR2(8),
	MSTATUS VARCHAR2(8),
	SSN VARCHAR2(16),
	RACE VARCHAR2(8),
	ETHNIC VARCHAR2(8),
	RELIGION VARCHAR2(8),
	LANGUAGE VARCHAR2(8),
	SPOUSENAME VARCHAR2(100),
	MOTHERNAME VARCHAR2(100),
	MOTHERMN VARCHAR2(40),
	FATHERNAME VARCHAR2(100),
	MAIDEN VARCHAR2(40),
	POBCITY VARCHAR2(30),
	POBSTATE VARCHAR2(10),
	POBCOUNTRY VARCHAR2(20),
	VIPFLAG VARCHAR2(8),
	VETSTATUS VARCHAR2(8),
	FNAMEPHONETICCODE VARCHAR2(8),
	LNAMEPHONETICCODE VARCHAR2(8),
	MNAMEPHONETICCODE VARCHAR2(8),
	MOTHERMNPHONETICCODE VARCHAR2(8),
	MAIDENPHONETICCODE VARCHAR2(8),
	SPOUSEPHONETICCODE VARCHAR2(8),
	MOTHERPHONETICCODE VARCHAR2(8),
	FATHERPHONETICCODE VARCHAR2(8),
	DRIVERSLICENSE VARCHAR2(20),
	DRIVERSLICENSEST VARCHAR2(10),
	DOD DATE,
	DEATHCERTIFICATE VARCHAR2(10),
	NATIONALITY VARCHAR2(8),
	CITIZENSHIP VARCHAR2(8),
	PENSIONNO VARCHAR2(15),
	PENSIONEXPDATE DATE,
	REPATRIATIONNO VARCHAR2(16),
	DISTRICTOFRESIDENCE VARCHAR2(8),
	LGACODE VARCHAR2(4),
	MILITARYBRANCH VARCHAR2(4),
	MILITARYRANK VARCHAR2(4),
	MILITARYSTATUS VARCHAR2(4),
	DUMMYDATE DATE,
	CLASS1 VARCHAR2(20),
	CLASS2 VARCHAR2(20),
	CLASS3 VARCHAR2(20),
	CLASS4 VARCHAR2(20),
	CLASS5 VARCHAR2(20),
	STRING1 VARCHAR2(40),
	STRING2 VARCHAR2(40),
	STRING3 VARCHAR2(40),
	STRING4 VARCHAR2(40),
	STRING5 VARCHAR2(40),
	STRING6 VARCHAR2(40),
	STRING7 VARCHAR2(100),
	STRING8 VARCHAR2(100),
	STRING9 VARCHAR2(100),
	STRING10 VARCHAR2(255),
	DATE1 DATE,
	DATE2 DATE,
	DATE3 DATE,
	DATE4 DATE,
	DATE5 DATE,
	STDFIRSTNAME VARCHAR2(40),
	STDLASTNAME VARCHAR2(40),
	STDMIDDLENAME VARCHAR2(30))
		;

ALTER TABLE SBYN_PERSON ADD CONSTRAINT FK_PERSON_SYSTEMCODE_LID FOREIGN KEY (SYSTEMCODE, LID) REFERENCES SBYN_SYSTEMOBJECT(SYSTEMCODE, LID) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE SBYN_PERSON ADD CONSTRAINT PK_PERSON PRIMARY KEY (PERSONID);
ALTER TABLE SBYN_PERSON ADD CONSTRAINT U_PERSON UNIQUE (SYSTEMCODE, LID) DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE SBYN_PERSONSBR (
	EUID VARCHAR2(20),
	PERSONID VARCHAR2(20),
	PERSONCATCODE VARCHAR2(8),
	LASTNAME VARCHAR2(40),
	FIRSTNAME VARCHAR2(40),
	MIDDLENAME VARCHAR2(30),
	SUFFIX VARCHAR2(10),
	TITLE VARCHAR2(8),
	DOB DATE,
	DEATH VARCHAR2(1),
	GENDER VARCHAR2(8),
	MSTATUS VARCHAR2(8),
	SSN VARCHAR2(16),
	RACE VARCHAR2(8),
	ETHNIC VARCHAR2(8),
	RELIGION VARCHAR2(8),
	LANGUAGE VARCHAR2(8),
	SPOUSENAME VARCHAR2(100),
	MOTHERNAME VARCHAR2(100),
	MOTHERMN VARCHAR2(40),
	FATHERNAME VARCHAR2(100),
	MAIDEN VARCHAR2(40),
	POBCITY VARCHAR2(30),
	POBSTATE VARCHAR2(10),
	POBCOUNTRY VARCHAR2(20),
	VIPFLAG VARCHAR2(8),
	VETSTATUS VARCHAR2(8),
	FNAMEPHONETICCODE VARCHAR2(8),
	LNAMEPHONETICCODE VARCHAR2(8),
	MNAMEPHONETICCODE VARCHAR2(8),
	MOTHERMNPHONETICCODE VARCHAR2(8),
	MAIDENPHONETICCODE VARCHAR2(8),
	SPOUSEPHONETICCODE VARCHAR2(8),
	MOTHERPHONETICCODE VARCHAR2(8),
	FATHERPHONETICCODE VARCHAR2(8),
	DRIVERSLICENSE VARCHAR2(20),
	DRIVERSLICENSEST VARCHAR2(10),
	DOD DATE,
	DEATHCERTIFICATE VARCHAR2(10),
	NATIONALITY VARCHAR2(8),
	CITIZENSHIP VARCHAR2(8),
	PENSIONNO VARCHAR2(15),
	PENSIONEXPDATE DATE,
	REPATRIATIONNO VARCHAR2(16),
	DISTRICTOFRESIDENCE VARCHAR2(8),
	LGACODE VARCHAR2(4),
	MILITARYBRANCH VARCHAR2(4),
	MILITARYRANK VARCHAR2(4),
	MILITARYSTATUS VARCHAR2(4),
	DUMMYDATE DATE,
	CLASS1 VARCHAR2(20),
	CLASS2 VARCHAR2(20),
	CLASS3 VARCHAR2(20),
	CLASS4 VARCHAR2(20),
	CLASS5 VARCHAR2(20),
	STRING1 VARCHAR2(40),
	STRING2 VARCHAR2(40),
	STRING3 VARCHAR2(40),
	STRING4 VARCHAR2(40),
	STRING5 VARCHAR2(40),
	STRING6 VARCHAR2(40),
	STRING7 VARCHAR2(100),
	STRING8 VARCHAR2(100),
	STRING9 VARCHAR2(100),
	STRING10 VARCHAR2(255),
	DATE1 DATE,
	DATE2 DATE,
	DATE3 DATE,
	DATE4 DATE,
	DATE5 DATE,
	STDFIRSTNAME VARCHAR2(40),
	STDLASTNAME VARCHAR2(40),
	STDMIDDLENAME VARCHAR2(30))
		;
	
ALTER TABLE SBYN_PERSONSBR ADD CONSTRAINT FK_PERSONSBR_EUID FOREIGN KEY (EUID) REFERENCES SBYN_SYSTEMSBR(EUID) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE SBYN_PERSONSBR ADD CONSTRAINT PK_PERSONSBR PRIMARY KEY (PERSONID);
ALTER TABLE SBYN_PERSONSBR ADD CONSTRAINT U_PERSONSBR UNIQUE (EUID) DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE SBYN_PHONE (
	PERSONID VARCHAR2(20),
	PHONEID VARCHAR2(20),
	PHONETYPE VARCHAR2(8),
	PHONE VARCHAR2(20),
	PHONEEXT VARCHAR2(6))
		;

ALTER TABLE SBYN_PHONE ADD CONSTRAINT FK_PHONE_PERSONID FOREIGN KEY (PERSONID) REFERENCES SBYN_PERSON(PERSONID) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE SBYN_PHONE ADD CONSTRAINT PK_PHONE PRIMARY KEY (PHONEID);
ALTER TABLE SBYN_PHONE ADD CONSTRAINT U_PHONE UNIQUE (PERSONID, PHONETYPE) DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE SBYN_PHONESBR (
	PERSONID VARCHAR2(20),
	PHONEID VARCHAR2(20),
	PHONETYPE VARCHAR2(8),
	PHONE VARCHAR2(20),
	PHONEEXT VARCHAR2(6))
		;

ALTER TABLE SBYN_PHONESBR ADD CONSTRAINT FK_PHONESBR_PERSONID FOREIGN KEY (PERSONID) REFERENCES SBYN_PERSONSBR(PERSONID) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE SBYN_PHONESBR ADD CONSTRAINT PK_PHONESBR PRIMARY KEY (PHONEID);
ALTER TABLE SBYN_PHONESBR ADD CONSTRAINT U_PHONESBR UNIQUE (PERSONID, PHONETYPE) DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE SBYN_ALIAS (
	PERSONID VARCHAR2(20),
	ALIASID VARCHAR2(20),
	LASTNAME VARCHAR2(40),
	FIRSTNAME VARCHAR2(40),
	MIDDLENAME VARCHAR2(30),
	LNAMEPHONETICCODE VARCHAR2(8),
	FNAMEPHONETICCODE VARCHAR2(8),
	MNAMEPHONETICCODE VARCHAR2(8),
	STDFIRSTNAME VARCHAR2(40),
	STDLASTNAME VARCHAR2(40),
	STDMIDDLENAME VARCHAR2(30),
	MYCHARFIELD CHAR,
	MYBOOLEANFIELD SMALLINT)
		;

ALTER TABLE SBYN_ALIAS ADD CONSTRAINT FK_ALIAS_PERSONID FOREIGN KEY (PERSONID) REFERENCES SBYN_PERSON(PERSONID) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE SBYN_ALIAS ADD CONSTRAINT PK_ALIAS PRIMARY KEY (ALIASID);
ALTER TABLE SBYN_ALIAS ADD CONSTRAINT U_ALIAS UNIQUE (PERSONID, LASTNAME, FIRSTNAME, MIDDLENAME) DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE SBYN_ALIASSBR (
	PERSONID VARCHAR2(20),
	ALIASID VARCHAR2(20),
	LASTNAME VARCHAR2(40),
	FIRSTNAME VARCHAR2(40),
	MIDDLENAME VARCHAR2(30),
	LNAMEPHONETICCODE VARCHAR2(8),
	FNAMEPHONETICCODE VARCHAR2(8),
	MNAMEPHONETICCODE VARCHAR2(8),
	STDFIRSTNAME VARCHAR2(40),
	STDLASTNAME VARCHAR2(40),
	STDMIDDLENAME VARCHAR2(30),
	MYCHARFIELD CHAR,
	MYBOOLEANFIELD SMALLINT)
		;

ALTER TABLE SBYN_ALIASSBR ADD CONSTRAINT FK_ALIASSBR_PERSONID FOREIGN KEY (PERSONID) REFERENCES SBYN_PERSONSBR(PERSONID) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE SBYN_ALIASSBR ADD CONSTRAINT PK_ALIASSBR PRIMARY KEY (ALIASID);
ALTER TABLE SBYN_ALIASSBR ADD CONSTRAINT U_ALIASSBR UNIQUE (PERSONID, LASTNAME, FIRSTNAME, MIDDLENAME) DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE SBYN_ADDRESS (
	PERSONID VARCHAR2(20),
	ADDRESSID VARCHAR2(20),
	ADDRESSTYPE VARCHAR2(8),
	ADDRESSLINE1 VARCHAR2(40),
	ADDRESSLINE2 VARCHAR2(40),
	ADDRESSLINE3 VARCHAR2(40),
	ADDRESSLINE4 VARCHAR2(40),
	CITY VARCHAR2(30),
	STATECODE VARCHAR2(10),
	POSTALCODE VARCHAR2(8),
	POSTALCODEEXT VARCHAR2(4),
	COUNTY VARCHAR2(20),
	COUNTRYCODE VARCHAR2(20),
	HOUSENUMBER VARCHAR2(10),
	STREETDIR VARCHAR2(5),
	STREETNAME VARCHAR2(40),
	STREETNAMEPHONETICCODE VARCHAR2(8),
	STREETTYPE VARCHAR2(5))
		;

ALTER TABLE SBYN_ADDRESS ADD CONSTRAINT FK_ADDRESS_PERSONID FOREIGN KEY (PERSONID) REFERENCES SBYN_PERSON(PERSONID) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE SBYN_ADDRESS ADD CONSTRAINT PK_ADDRESS PRIMARY KEY (ADDRESSID);
ALTER TABLE SBYN_ADDRESS ADD CONSTRAINT U_ADDRESS UNIQUE (PERSONID, ADDRESSTYPE) DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE SBYN_ADDRESSSBR (
	PERSONID VARCHAR2(20),
	ADDRESSID VARCHAR2(20),
	ADDRESSTYPE VARCHAR2(8),
	ADDRESSLINE1 VARCHAR2(40),
	ADDRESSLINE2 VARCHAR2(40),
	ADDRESSLINE3 VARCHAR2(40),
	ADDRESSLINE4 VARCHAR2(40),
	CITY VARCHAR2(30),
	STATECODE VARCHAR2(10),
	POSTALCODE VARCHAR2(8),
	POSTALCODEEXT VARCHAR2(4),
	COUNTY VARCHAR2(20),
	COUNTRYCODE VARCHAR2(20),
	HOUSENUMBER VARCHAR2(10),
	STREETDIR VARCHAR2(5),
	STREETNAME VARCHAR2(40),
	STREETNAMEPHONETICCODE VARCHAR2(8),
	STREETTYPE VARCHAR2(5))
		;

ALTER TABLE SBYN_ADDRESSSBR ADD CONSTRAINT FK_ADDRESSSBR_PERSONID FOREIGN KEY (PERSONID) REFERENCES SBYN_PERSONSBR(PERSONID) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE SBYN_ADDRESSSBR ADD CONSTRAINT PK_ADDRESSSBR PRIMARY KEY (ADDRESSID);
ALTER TABLE SBYN_ADDRESSSBR ADD CONSTRAINT U_ADDRESSSBR UNIQUE (PERSONID, ADDRESSTYPE) DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE SBYN_AUXID (
	PERSONID VARCHAR2(20),
	AUXIDID VARCHAR2(20),
	AUXIDDEF VARCHAR2(10),
	ID VARCHAR2(40))
		;

ALTER TABLE SBYN_AUXID ADD CONSTRAINT FK_AUXID_PERSONID FOREIGN KEY (PERSONID) REFERENCES SBYN_PERSON(PERSONID) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE SBYN_AUXID ADD CONSTRAINT PK_AUXID PRIMARY KEY (AUXIDID);
ALTER TABLE SBYN_AUXID ADD CONSTRAINT U_AUXID UNIQUE (PERSONID, AUXIDDEF, ID) DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE SBYN_AUXIDSBR (
	PERSONID VARCHAR2(20),
	AUXIDID VARCHAR2(20),
	AUXIDDEF VARCHAR2(10),
	ID VARCHAR2(40))
		;

ALTER TABLE SBYN_AUXIDSBR ADD CONSTRAINT FK_AUXIDSBR_PERSONID FOREIGN KEY (PERSONID) REFERENCES SBYN_PERSONSBR(PERSONID) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE SBYN_AUXIDSBR ADD CONSTRAINT PK_AUXIDSBR PRIMARY KEY (AUXIDID);
ALTER TABLE SBYN_AUXIDSBR ADD CONSTRAINT U_AUXIDSBR UNIQUE (PERSONID, AUXIDDEF, ID) DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE SBYN_COMMENT (
	PERSONID VARCHAR2(20),
	COMMENTID VARCHAR2(20),
	COMMENTCODE VARCHAR2(8),
	ENTERDATE DATE,
	COMMENTTEXT VARCHAR2(1000))
		;

ALTER TABLE SBYN_COMMENT ADD CONSTRAINT FK_COMMENT_PERSONID FOREIGN KEY (PERSONID) REFERENCES SBYN_PERSON(PERSONID) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE SBYN_COMMENT ADD CONSTRAINT PK_COMMENT PRIMARY KEY (COMMENTID);
ALTER TABLE SBYN_COMMENT ADD CONSTRAINT U_COMMENT UNIQUE (PERSONID, COMMENTCODE) DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE SBYN_COMMENTSBR (
	PERSONID VARCHAR2(20),
	COMMENTID VARCHAR2(20),
	COMMENTCODE VARCHAR2(8),
	ENTERDATE DATE,
	COMMENTTEXT VARCHAR2(1000))
		;

ALTER TABLE SBYN_COMMENTSBR ADD CONSTRAINT FK_COMMENTSBR_PERSONID FOREIGN KEY (PERSONID) REFERENCES SBYN_PERSONSBR(PERSONID) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE SBYN_COMMENTSBR ADD CONSTRAINT PK_COMMENTSBR PRIMARY KEY (COMMENTID);
ALTER TABLE SBYN_COMMENTSBR ADD CONSTRAINT U_COMMENTSBR UNIQUE (PERSONID, COMMENTCODE) DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE SBYN_SEQ_TABLE (
	SEQ_NAME VARCHAR2(20),
	SEQ_COUNT NUMBER(38));

ALTER TABLE SBYN_SEQ_TABLE ADD CONSTRAINT U_SEQ_NAME UNIQUE (SEQ_NAME);

CREATE OR REPLACE FUNCTION SEQMGR (Seq_Name_In IN VARCHAR2, Chunk_Size_In IN INTEGER) RETURN INTEGER
IS
PRAGMA AUTONOMOUS_TRANSACTION;

   Count_out INTEGER := 0;
BEGIN
   Count_out := 0;

   UPDATE SBYN_SEQ_TABLE SET seq_count = seq_count+Chunk_Size_In WHERE seq_name = Seq_Name_In;
   SELECT seq_count-Chunk_Size_In  INTO Count_out FROM SBYN_SEQ_TABLE WHERE seq_name = Seq_Name_In;
   COMMIT;

   RETURN Count_out;
EXCEPTION
    WHEN OTHERS THEN
        RETURN 0;
END SEQMGR;
/

INSERT INTO SBYN_SEQ_TABLE VALUES ('EUID', 0);
INSERT INTO SBYN_SEQ_TABLE VALUES ('POTENTIALDUPLICATE', 0);
INSERT INTO SBYN_SEQ_TABLE VALUES ('TRANSACTIONNUMBER', 0);
INSERT INTO SBYN_SEQ_TABLE VALUES ('ASSUMEDMATCH', 0);
INSERT INTO SBYN_SEQ_TABLE VALUES ('AUDIT', 0);
INSERT INTO SBYN_SEQ_TABLE VALUES ('MERGE', 0);
INSERT INTO SBYN_SEQ_TABLE VALUES ('SBYN_APPL', 2);
INSERT INTO SBYN_SEQ_TABLE VALUES ('SBYN_COMMON_HEADER', 1);
INSERT INTO SBYN_SEQ_TABLE VALUES ('SBYN_COMMON_DETAIL', 1);
INSERT INTO SBYN_SEQ_TABLE VALUES ('PHONE', 0);
INSERT INTO SBYN_SEQ_TABLE VALUES ('PHONESBR', 0);
INSERT INTO SBYN_SEQ_TABLE VALUES ('ALIAS', 0);
INSERT INTO SBYN_SEQ_TABLE VALUES ('ALIASSBR', 0);
INSERT INTO SBYN_SEQ_TABLE VALUES ('ADDRESS', 0);
INSERT INTO SBYN_SEQ_TABLE VALUES ('ADDRESSSBR', 0);
INSERT INTO SBYN_SEQ_TABLE VALUES ('AUXID', 0);
INSERT INTO SBYN_SEQ_TABLE VALUES ('AUXIDSBR', 0);
INSERT INTO SBYN_SEQ_TABLE VALUES ('COMMENT', 0);
INSERT INTO SBYN_SEQ_TABLE VALUES ('COMMENTSBR', 0);
INSERT INTO SBYN_SEQ_TABLE VALUES ('PERSON', 0);
INSERT INTO SBYN_SEQ_TABLE VALUES ('PERSONSBR', 0);

INSERT INTO SBYN_APPL (APPL_ID, CODE, DESCR, READ_ONLY, CREATE_DATE, CREATE_USERID) 
VALUES (1, 'EV', 'eView5.1', 'Y', sysdate, user);

COMMIT;
